#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 050."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

CARDS = [
card("record-a592ef38f18db604", "arXiv v2 manuscript", "https://arxiv.org/pdf/2005.03769",
     "A Data-Driven Approach for Discovering Stochastic Dynamical Systems with Non-Gaussian Lévy Noise", "发现含非高斯Lévy噪声随机动力系统的数据驱动方法",
     "theory_numerics", "a592ef38f18db604", "Active Matter",
     {"doi":"10.1016/j.physd.2020.132830","arxiv_id":"2005.03769","version":"arXiv v2 full text","title":"A Data-Driven Approach for Discovering Stochastic Dynamical Systems with Non-Gaussian Lévy Noise","authors":["Yang Li","Jinqiao Duan"],"journal":"Physica D: Nonlinear Phenomena","volume":"417","pages":"132830","published":"2021","abstract":"Small-time transition probabilities identify symmetric Lévy jump parameters, drift and Gaussian diffusion from sample-path pairs.","comment":"Physica D article cross-checked with arXiv full text"},
     [sec("作者信息", "作者 Yang Li、Jinqiao Duan；Physica D 417, 132830 (2021)，DOI:10.1016/j.physd.2020.132830。核验 arXiv:2005.03769v2 全文36页，含主文、表格与补充推导。"),
      sec("研究问题", "由短时间成对样本(x(t),x(t+h))反推随机微分方程时，传统Kramers–Moyal主要面向Brownian diffusion。若系统同时受heavy-tailed、带跳跃的symmetric α-stable Lévy noise驱动，如何分别识别稳定指数α、jump intensity、drift和Gaussian diffusion？"),
      sec("背景", "模型dX=b(X)dt+Λ(X)dB+σdL^α同时含连续Brownian项与非局域jumps。跳跃使transition density尾部按Lévy measure衰减，局部一、二阶increment moments还要排除大跳区域。", "目录归入Active Matter，但本文是通用随机系统辨识，数值例子为double well、Maier–Stein、Lorenz和gene regulation；没有活性粒子实验。"),
      sec("模型与方法", "Theorem 1给出small-time probability limits：落在距起点超过ε的annulus中的概率密度恢复Lévy measure；截断在|x−z|<ε内的一阶、二阶条件矩分别恢复drift与Gaussian diffusion，并带可计算的jump补偿。", "算法先由log-log tail counts拟合α与σ，再把drift/diffusion展开在polynomial basis上，用least squares求系数。数据为许多独立短step pairs，而非一条轨迹上直接数值微分。"),
      sec("核心结果与证据", "Tables 1–3在一维double well中识别α、jump scale、cubic drift和state-dependent diffusion；参数随ε与h变化但接近真值。Figure 1把学习的drift/diffusion曲线与真函数叠加，显示主区间内吻合。", "Tables 5–10扩展到二维Maier–Stein与三维Lorenz；Table 11处理同时含Gaussian和Lévy noise的gene regulatory system。结果证明该采样协议在低维合成数据上可工作，不等于对真实hidden-variable数据已有稳健保证。", "Theorem是small-time极限，实践中h过大有bias，过小又使rare jump计数不足；ε同时控制局部矩与tail统计，必须联合扫描而非只报单一最优值。"),
      sec("有效性与局限", "方法假设加性、对称、各向同性α-stable jump noise；multiplicative/asymmetric Lévy measure、measurement error与irregular sampling不在当前算法内。polynomial library必须覆盖真实drift/diffusion，维数升高会使basis和样本量迅速增长。", "所有实验由已知SDE模拟，缺少现实数据、bootstrap uncertainty和与其他jump-process estimators的统一benchmark。α、σ与diffusion的有限样本耦合可能造成误差传播。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2005.03769；期刊：https://doi.org/10.1016/j.physd.2020.132830；代码与数据：https://github.com/liyangnuaa/Small-Time-Probability-Evolution-Method-of-Machine-Learning/tree/master 。PDF SHA-256：40f1cdcce691dac14f74f20c9ee35632f963ee3fa271272f1a36399fcf1ab3d1。", "复现需固定h、ε grids、sample pairs数量、α-stable sampler convention、polynomial degree、bin widths和random seeds，并分别报告jump、drift、diffusion误差。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–7模型与Theorem 1；pp.8–12看三个辨识算法；pp.13–18读四组examples与Figure 1；pp.19–36查完整表格、证明与实现参数。")],
     "figure-1-drift-diffusion.webp","Figure 1",14,"comparison","一维double-well系统中真实与学习的drift、diffusion函数对比。","在给定small-time sampling与polynomial library下，两类系数函数在训练区间内贴合真值。","Figure 1把表格中的系数估计转化为完整函数形状，是判断恢复质量最直接的原文图证。",
     [{"label":"Jump-diffusion model","latex":r"dX_t=b(X_t)dt+\Lambda(X_t)dB_t+\sigma\,dL_t^{\alpha}","role":"separate drift, Gaussian diffusion and heavy-tailed jump forcing","symbols":{"b":"drift","Lambda":"Brownian diffusion matrix","L_alpha":"symmetric alpha-stable Lévy motion"},"evidence":"paper.pdf pp. 3–5, stochastic model and Theorem 1","interpretation":"Identification relies on small-time local moments and nonlocal transition tails."}],
     ["paper.pdf pp. 1–7: jump-diffusion model and small-time theorem","paper.pdf pp. 8–12: algorithms for Lévy, drift and diffusion terms","paper.pdf pp. 13–18, Figure 1: four synthetic systems","paper.pdf pp. 29–36, Tables 1–11: complete parameter estimates","source PDF SHA-256 40f1cdcce691dac14f74f20c9ee35632f963ee3fa271272f1a36399fcf1ab3d1","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-aa856c468aa42fde", "arXiv manuscript", "https://arxiv.org/pdf/2010.09147",
     "Physics-informed neural networks for solving forward and inverse flow problems via the Boltzmann-BGK formulation", "通过Boltzmann–BGK表述求解正逆流动问题的物理信息神经网络",
     "theory_numerics", "aa856c468aa42fde", "AI for Science",
     {"doi":"10.1016/j.jcp.2021.110676","arxiv_id":"2010.09147","version":"arXiv full text","title":"Physics-informed neural networks for solving forward and inverse flow problems via the Boltzmann-BGK formulation","authors":["Qin Lou","Xuhui Meng","George Em Karniadakis"],"journal":"Journal of Computational Physics","volume":"447","pages":"110676","published":"2021","abstract":"PINN-BGK learns equilibrium and non-equilibrium distributions while enforcing discrete-velocity BGK equations across continuum and rarefied regimes.","comment":"JCP article cross-checked with arXiv manuscript"},
     [sec("作者信息", "作者 Qin Lou、Xuhui Meng、George Em Karniadakis；Journal of Computational Physics 447, 110676 (2021)，DOI:10.1016/j.jcp.2021.110676。核验 arXiv:2010.09147 全文30页。"),
      sec("研究问题", "Navier–Stokes只适用于continuum limit，而micro/nano flows可进入rarefied regime。能否用统一physics-informed network求解跨Knudsen数的Boltzmann–BGK正问题，并在边界条件未知时仅凭少量内部velocity sensors重建全流场？"),
      sec("背景", "BGK kinetic equation让distribution f向local Maxwellian/equilibrium f_eq以relaxation time τ松弛，宏观density、momentum和energy由velocity moments得到。离散velocity后，每个f_i满足transport-relaxation PDE。", "PINN不需要空间mesh，但仍需选collocation points、discrete velocities和network capacity；自动微分替代导数离散不代表没有velocity-space或optimization误差。"),
      sec("模型与方法", "PINN-BGK由三个部分组成：NN_eq近似equilibrium distribution，NN_neq近似non-equilibrium correction，physics part通过automatic differentiation计算BGK residual，并加入initial/boundary/data mismatch。不同subdomains可各用网络并在interface约束连续。", "正问题覆盖Kovasznay、Taylor–Green、lid-driven cavity、micro-Couette；逆问题不给wall boundary condition，只在内部稀疏位置提供u observations。训练采用Adam与L-BFGS-B，并测试跨参数transfer learning。"),
      sec("核心结果与证据", "Figure 1明确三网络架构、discrete velocities及physics residual。Tables 1–3和Figures 2–4显示continuum benchmarks与解析或LBM参考总体一致；accuracy依赖network width和domain decomposition。", "Figures 5–8覆盖Kn=0.01–5的micro-Couette正/逆问题。Figures 9–11显示micro-cavity逆问题：random interior sensors可恢复vortex，但均匀传感线若避开边界/涡核，近壁误差明显；增加靠近关键区域的measurements后改善。", "transfer-learning表格在特定2D Kovasznay设置约有三倍speedup。该数字不是通用PINN复杂度结论，也未与成熟kinetic solvers在相同精度和硬件上全面比较。"),
      sec("有效性与局限", "实验是稳态或规则benchmark，reference多为analytic/LBM/DUGKS；高维velocity space、3D unsteady rarefied flow和turbulence会显著提高collocation与训练成本。inverse accuracy对sensor placement敏感。", "BGK是单松弛近似，不覆盖所有collision physics；论文未系统报告多seed优化方差、wall-clock/energy、公平mesh-solver基线或noisy sensor robustness。所谓同一代码仍需按case设置scaling、boundary loss和subdomains。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2010.09147；期刊：https://doi.org/10.1016/j.jcp.2021.110676。PDF SHA-256：5ef8daa46b84f631cfa82ad75cd5ea27a52b75f022ab589e893684d8ead657d6。正文未给公开代码仓库。", "复现需固定discrete velocity set、Kn/τ、network layers、activation、collocation/boundary/sensor points、loss weights、Adam/L-BFGS-B stopping、subdomain interfaces与reference solver。Evidence status: full-text verified numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–5 BGK与Figure 1；pp.6–14看continuum正问题；pp.15–23看rarefied正逆问题和sensor placement；pp.24–25读总结；pp.26–30为参考文献。")],
     "figure-1-pinn-bgk.webp","Figure 1",5,"schematic","equilibrium、non-equilibrium两个神经网络与Boltzmann–BGK physics residual的组合架构。","分布函数近似与动理学方程约束共同训练，使同一表述覆盖正问题和带内部观测的逆问题。","Figure 1直接给出PINN-BGK的组成、信息流和物理约束，是理解其区别于普通PINN的关键图证。",
     [{"label":"Boltzmann-BGK equation","latex":r"\partial_t f+\boldsymbol{\xi}\!\cdot\!\nabla_x f=-\frac{1}{\tau}(f-f^{eq})","role":"couple kinetic transport to relaxation toward local equilibrium","symbols":{"f":"particle distribution","xi":"microscopic velocity","tau":"relaxation time","f_eq":"equilibrium distribution"},"evidence":"paper.pdf pp. 3–5, Eqs. (1)–(14) and Figure 1","interpretation":"The PINN enforces a discrete-velocity approximation of this equation."}],
     ["paper.pdf pp. 1–5, Figure 1: PINN-BGK architecture","paper.pdf pp. 6–14, Figures 2–4: continuum benchmarks","paper.pdf pp. 15–23, Figures 5–11: rarefied forward and inverse problems","paper.pdf pp. 23–25: transfer learning and scope","source PDF SHA-256 5ef8daa46b84f631cfa82ad75cd5ea27a52b75f022ab589e893684d8ead657d6","Evidence status: full-text verified numerical study; no independent reproduction performed."]),

card("record-abbbdd1f1314d86f", "arXiv v2 manuscript", "https://arxiv.org/pdf/1811.06750",
     "Itô vs Stratonovich in the presence of absorbing states", "存在吸收态时的Itô与Stratonovich解释",
     "theory", "abbbdd1f1314d86f", "Statistical Physics",
     {"doi":"10.1063/1.5081791","arxiv_id":"1811.06750","version":"arXiv v2 full text","title":"Itô vs Stratonovich in the presence of absorbing states","authors":["Álvaro Correales","Carlos Escudero"],"journal":"Journal of Mathematical Physics","volume":"60","pages":"123301","published":"2019","abstract":"The usual Itô-Stratonovich drift conversion can fail for non-Lipschitz square-root noise at absorbing states, changing boundaries and even solution multiplicity.","comment":"JMP article cross-checked with arXiv v2"},
     [sec("作者信息", "作者 Álvaro Correales、Carlos Escudero；Journal of Mathematical Physics 60, 123301 (2019)，DOI:10.1063/1.5081791。核验 arXiv:1811.06750v2 全文14页。"),
      sec("研究问题", "常用公式把Itô SDE转换为Stratonovich形式并加减半个noise-induced drift。这个转换在扩散系数于吸收边界呈square-root、不可C¹时是否仍保持同一随机过程？若不保持，会怎样改变灭绝态、长期行为与解的唯一性？"),
      sec("背景", "经典等价定理要求drift/diffusion足够Lipschitz且σ可微。人口、branching、reaction和金融模型常有σ(x)∝√x，在x=0只有Hölder-1/2连续；0又具有吸收的物理意义。形式代入σ'σ可能产生有限漂移，却跨越了定理假设。", "选择Itô或Stratonovich必须来自建模极限和积分定义，不能把转换公式当作无条件代数恒等式。本文关注退化边界，未声称一种解释在所有物理系统中普遍优越。"),
      sec("模型与方法", "以Feller branching dX=√(2X)dW为主例：Itô在X0=0有吸收解；形式Stratonovich dual多出−1/2 drift，立即失去零解。Theorem 2.1把结论推广到f(x0,t)=g(x0,t)=0但g'(x0,0)≠0的sqrt(2g)噪声。", "作者用边界分类、强解存在唯一性、hitting/absorption time和squared Bessel process分析长期与中期动力学；并构造不同等待时间后离开零点的Stratonovich解族，展示非唯一性。"),
      sec("核心结果与证据", "Eqs. (6)–(9)构成最小反例：形式转换可把吸收零态变成瞬时反射边界，反向转换也会改变解。带两个吸收态的x(1−x)例子显示两个边界可同时丢失。", "对有界区间，Theorem 4.1在假设下证明Itô过程几乎必然在有限平均时间到达边界，因此差异不是只在无限远时间出现。Feller process在无界区间几乎必然灭绝但平均吸收时间发散，说明两种时间陈述需区分。", "Section 5证明相应Stratonovich square-root SDE可有不可数多个solutions，而Itô方程由Yamada–Watanabe型结果保持唯一。证据为解析定理与显式解，不含数值实验。"),
      sec("有效性与局限", "反例依赖扩散在边界非Lipschitz且退化；若经典smoothness条件成立，标准转换仍有效。本文主要是一维time-homogeneous或特定一般化，multidimensional manifolds、colored-noise limits和SPDE需另行分析。", "‘Itô较安全’只针对文中吸收态类和well-posedness结果，不是通用物理处方。实际模型还须说明microscopic noise limit、边界规则与desired conservation law。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/1811.06750；期刊：https://doi.org/10.1063/1.5081791。PDF SHA-256：4da4a40e6cb615d6188938704ed959d5e5ad4fadb9d7d3e9811983706e9caa62。纯解析论文未提供或需要代码仓库。", "复核应先检查σ的可微/Lipschitz条件，再逐项验证Eqs. (6)–(19)、边界分类、hitting probability和solution family；不得在x=0直接套用形式导数而忽略定义域。Evidence status: full-text verified analytical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4标准转换条件与Theorem 2.1；pp.5–9看边界分类和长期动力学；pp.9–10读finite mean absorption；pp.10–12看Feller多解；pp.12–14读结论。")],
     "theorem-absorbing-state.webp","Theorem 2.1 and Eqs. (6)–(9)",3,"schematic","Feller square-root diffusion及其形式Itô–Stratonovich转换，连同吸收态丢失的一般定理。","非光滑扩散边界使形式漂移修正不再保持零解，直接改变随机动力学。","该页并列最小物理反例和一般定理，是没有数据图的解析论文中最能支撑中心结论的页面证据。",
     [{"label":"Feller branching diffusion","latex":r"dX_t=\sqrt{2X_t}\,dW_t,\qquad X_0=0","role":"exhibit an absorbing Itô state destroyed by formal Stratonovich conversion","symbols":{"X":"nonnegative population-like state","W":"Brownian motion","0":"absorbing boundary"},"evidence":"paper.pdf pp. 3–4, Eqs. (6)–(9) and Theorem 2.1","interpretation":"The diffusion coefficient is not differentiable at the boundary, so the classical conversion theorem does not apply."}],
     ["paper.pdf pp. 1–2: classical conversion assumptions","paper.pdf pp. 3–4, Eqs. (6)–(11): absorbing-state counterexamples","paper.pdf pp. 5–10: boundary classification and absorption times","paper.pdf pp. 10–12, Eqs. (15)–(19): Feller solution multiplicity","source PDF SHA-256 4da4a40e6cb615d6188938704ed959d5e5ad4fadb9d7d3e9811983706e9caa62","Evidence status: full-text verified analytical study; no independent reproduction performed."]),

card("record-af3db7e12355e717", "arXiv v2 manuscript", "https://arxiv.org/pdf/2112.14143",
     "Meta-Schrödinger invariance", "Meta-Schrödinger不变性",
     "theory", "af3db7e12355e717", "Mathematical Physics",
     {"doi":"10.1016/j.nuclphysb.2022.116020","arxiv_id":"2112.14143","version":"arXiv v2 full text","title":"Meta-Schrödinger invariance","authors":["Stoimen Stoimenov","Malte Henkel"],"journal":"Nuclear Physics B","volume":"985","pages":"116020","published":"2022","abstract":"An infinite-dimensional dynamical symmetry combines ballistic transport in one direction with Schrödinger diffusion in transverse directions and fixes covariant two-point functions.","comment":"Open-access Nuclear Physics B article cross-checked with arXiv v2"},
     [sec("作者信息", "作者 Stoimen Stoimenov、Malte Henkel；Nuclear Physics B 985, 116020 (2022)，DOI:10.1016/j.nuclphysb.2022.116020。核验 arXiv:2112.14143v2 全文29页。"),
      sec("研究问题", "非平衡体系可能沿一个parallel方向ballistic传播(z∥=1)，而在transverse方向diffusive扩散(z⊥=2)。是否存在同时包含meta-conformal与Schrödinger性质的最大dynamical symmetry？其无限维扩展、ageing表示和准初级场二点函数是什么？"),
      sec("背景", "纯diffusion equation由Schrödinger algebra控制，纯biased ballistic transport与meta-conformal algebra相关。本文研究的线性operator把一阶parallel derivative与二阶transverse Laplacian结合，因此空间各向异性不是单一z可描述。", "这里‘meta’指meta-conformal/ballistic–diffusive对称，不是机器学习元学习。工作是Lie-algebraic分类和covariance推导，没有材料或数值simulation。"),
      sec("模型与方法", "作者从一般一阶time-space generators出发，要求它们把混合transport-diffusion equation的solution space映回自身，并通过commutator closure求系数。分case A/B构造finite meta-Schrödinger algebra及infinite meta-Schrödinger–Virasoro extension。", "对非平稳ageing，将time translation改为X_{−1}=−∂t+ξ/t；随后对二点函数施加translation、dilatation、Galilei和special generators的Ward identities，求stationary与non-stationary scaling forms。"),
      sec("核心结果与证据", "得到msv(1,1)≅vir⊕sv(1)，其最大有限子代数为metasch(1,1)。Table 1把ortho-conformal、meta-conformal、Schrödinger与新meta-Schrödinger transformations并列，显示parallel坐标分式变换与transverse Gaussian/phase结构如何结合。", "Sections 2.1–2.2列出A、B两类generators与commutators；Section 3证明含ξ的ageing representations及与stationary representation的关系。Section 4给出三类covariant two-point functions，non-stationarity主要引入time-ratio scaling variable。", "论文得到允许的对称形式，而未在具体many-body model中数值验证。结论明确把spin ageing等physical realisations留给后续，因此不能把algebra existence当作某实际系统已呈现该universality class。"),
      sec("有效性与局限", "分类依赖所选linear mixed-order PDE、local infinitesimal generators和1个parallel/1个transverse方向；虽说明可推广多个transverse dimensions，但非线性、boundaries、disorder和interactions可能破坏对称。", "二点函数的covariance不是完整动态解，也不自动固定higher-point functions或operator content。central extensions只在附录按代数条件讨论；物理unitarity、positivity与realization未建立。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2112.14143；开放期刊版：https://doi.org/10.1016/j.nuclphysb.2022.116020。PDF SHA-256：840a7c35b4769360b75e814e11ba5026d265f04a2cef6e6239bda7994d308596。纯符号推导未提供或需要代码。", "复核需固定generator sign、light-cone coordinates、mass/rapidity/scaling-dimension conventions；逐一检查Eqs. (2.7)–(2.40) commutators、operator covariance与Section 4 Ward identities。Evidence status: full-text verified analytical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4三类已知对称与Table 1；pp.5–13看algebra构造；pp.14–18看ageing representations；pp.19–23读two-point functions；pp.23–29为结论和central extensions。")],
     "table-1-transformations.webp","Table 1 and Section 2",4,"table","已知conformal、meta-conformal、Schrödinger与meta-Schrödinger时空变换的并列表。","新对称把parallel ballistic变换与transverse diffusive Schrödinger结构组合在同一代数框架。","Table 1提供最紧凑的结构对照，紧接的Section 2方程又给出新代数作用的起点，适合作为中心解析证据。",
     [{"label":"Ballistic-diffusive operator","latex":r"\mathcal{S}=\partial_t-S_{\parallel}\partial_{\parallel}-S_{\perp}\nabla_{\perp}^{2}","role":"encode anisotropic transport with z_parallel=1 and z_perp=2","symbols":{"S_parallel":"ballistic velocity scale","S_perp":"transverse diffusion coefficient","nabla_perp":"transverse gradient"},"evidence":"paper.pdf pp. 2–4, Eqs. (1.2)–(1.4)","interpretation":"The meta-Schrödinger algebra is constructed as a dynamical symmetry of this mixed operator."}],
     ["paper.pdf pp. 1–4, Table 1: symmetry landscape","paper.pdf pp. 5–13: meta-Schrödinger algebra and commutators","paper.pdf pp. 14–18: non-stationary representations","paper.pdf pp. 19–23: covariant two-point functions","source PDF SHA-256 840a7c35b4769360b75e814e11ba5026d265f04a2cef6e6239bda7994d308596","Evidence status: full-text verified analytical study; no independent reproduction performed."]),

card("record-b336bfda0ec9a9fc", "arXiv manuscript", "https://arxiv.org/pdf/1808.04327",
     "Hidden fluid mechanics: Learning velocity and pressure fields from flow visualizations", "隐藏流体力学：从流动可视化学习速度与压力场",
     "theory_numerics", "b336bfda0ec9a9fc", "Fluid Dynamics",
     {"doi":"10.1126/science.aaw4741","arxiv_id":"1808.04327","version":"arXiv full text","title":"Hidden fluid mechanics: Learning velocity and pressure fields from flow visualizations","authors":["Maziar Raissi","Alireza Yazdani","George Em Karniadakis"],"journal":"Science","volume":"367","pages":"1026–1030","published":"2020","abstract":"Navier-Stokes-informed networks infer unobserved velocity and pressure from passive-scalar concentration movies in synthetic two- and three-dimensional flows.","comment":"Science article with extended arXiv manuscript and public code"},
     [sec("作者信息", "作者 Maziar Raissi、Alireza Yazdani、George Em Karniadakis；Science 367, 1026–1030 (2020)，DOI:10.1126/science.aaw4741。核验 arXiv:1808.04327 全文33页，扩展于四页期刊主文。"),
      sec("研究问题", "实验常只拍到被dye/smoke携带的passive scalar concentration c(x,t)，而真正关心的velocity、pressure、wall shear stress难以直接测量。能否在未知几何、初边界条件下，仅由c的时空movie和Navier–Stokes/transport laws恢复隐藏流场？"),
      sec("背景", "对不可压Newtonian flow，c满足advection–diffusion，u,p满足continuity与Navier–Stokes。单看scalar movie的inverse problem高度欠定；PDE residual把不同输出网络耦合，提供物理正则。", "所谓geometry/BC-agnostic指loss不显式输入完整边界条件；训练域、采样窗口、物理方程和synthetic data仍已指定。论文没有直接使用真实染料、MRI或临床影像。"),
      sec("模型与方法", "分别用深网络表示c、velocity components与p，automatic differentiation构造scalar transport、mass和momentum residual。loss由observed c mismatch与PDE residual组成；Reynolds、Péclet数也可作为待学习参数。", "案例包括2D/3D cylinder wake、带障碍channel及realistic intracranial aneurysm geometry。训练只取DNS/Nektar生成数据的一部分，held-out时空点与已知simulation fields比较，并由预测u,p计算lift/drag和wall shear stress。"),
      sec("核心结果与证据", "Figure 1给网络输出与五个PDE residual；Figures 3–7在2D cylinder中显示由scalar恢复u,v,p，relative L2 errors及lift/drag接近reference。数据少于或避开重要区域时误差上升。", "Figures 9–14扩展3D cylinder与obstacle channel；Figure 12把exact与learned c,u,v,p并列，Figure 13给wall shear stress。Figures 15–21在aneurysm geometry展示三维速度、压力和壁面剪切的模型重建。", "这些结果是clean synthetic passive-scalar data上的inverse consistency test。图像呈现强，但缺少真实measurement noise、segmentation、projection geometry和跨设备验证，临床用途属于前景而非已证明结论。"),
      sec("有效性与局限", "identifiability依赖scalar具有足够空间梯度并覆盖流域；混合均匀区或未观测边界附近的信息弱。optimization可出现gradient/pathology，turbulence、多尺度与高Re会显著加难。", "模型假设incompressible Newtonian flow、已知PDE形式与基本transport参数；实际dye有reaction、buoyancy、3D projection和噪声。论文明确承认数据合成且较干净，真实2D影像到3D场需要额外成像模型。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/1808.04327；期刊：https://doi.org/10.1126/science.aaw4741；代码与数据：https://github.com/maziarraissi/HFM ，归档DOI:10.5281/zenodo.3566161。PDF SHA-256：38ea28939e579159111099b777d480a617ecc5fa8f4f7c2f1eb68a1eadf77dad。", "复现需固定Nektar/DNS网格、scalar initialization、training windows、10×50 networks、activation、loss sampling/weights、optimizer schedule、Re/Pe参数化与error normalization。Evidence status: full-text verified numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–6问题、方程与Figure 1；pp.7–14看2D cylinder；pp.15–23读3D/channel和Figures 9–14；pp.24–28看aneurysm与局限；pp.29–33为参考文献。")],
     "figure-3-hidden-fields.webp","Figure 3",12,"comparison","2D cylinder wake中输入scalar concentration与预测/真实velocity、pressure场对比。","PDE residual把可见passive scalar与不可见流场耦合，使模型在合成benchmark上恢复隐藏变量。","Figure 3把唯一观测量和三类隐藏输出放在同一快照中，是HFM逆问题主张最直观、最可核查的证据。",
     [{"label":"Passive-scalar transport","latex":r"\partial_t c+\mathbf{u}\cdot\nabla c=Pe^{-1}\nabla^2c","role":"connect observed concentration movies to the hidden velocity field","symbols":{"c":"passive scalar concentration","u":"fluid velocity","Pe":"Péclet number"},"evidence":"paper.pdf pp. 4–6, governing equations and Figure 1","interpretation":"Velocity is inferred jointly with pressure by also enforcing incompressibility and momentum balance."}],
     ["paper.pdf pp. 1–6, Figure 1: HFM formulation","paper.pdf pp. 7–14, Figures 2–7: 2D cylinder reconstruction","paper.pdf pp. 15–23, Figures 8–14: 3D and channel flows","paper.pdf pp. 23–28, Figures 15–21: aneurysm and limitations","source PDF SHA-256 38ea28939e579159111099b777d480a617ecc5fa8f4f7c2f1eb68a1eadf77dad","Evidence status: full-text verified numerical study; no independent reproduction performed."])
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids=[]
    for item in CARDS:
        pid=str(item["arxiv_id"])
        (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
        ids.append(pid)
    print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__ == "__main__": raise SystemExit(main())
