#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 032."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import figure, provenance, sec

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

def card(pid: str, source_version: str, source_pdf: str, title: str, title_zh: str,
         profile: str, record: str, topic: str, metadata: dict[str, object],
         sections: list[dict[str, object]], figfile: str, figlabel: str, figpage: int,
         figtype: str, alt: str, caption: str, rationale: str,
         equations: list[dict[str, object]], evidence: list[str]) -> dict[str, object]:
    return {"arxiv_id": pid, "source_version": source_version, "source_pdf": source_pdf,
            "title_en": title, "title_zh": title_zh, "curation_status": "full_text_verified",
            "card_standard_version": "2.3", "paper_profile": profile,
            "style_reference": "physicist_daily_arxiv", "provenance": provenance([record], [topic]),
            "verified_metadata": metadata, "sections": sections,
            "cover": {"mode": "source_figure", "asset_path": f"assets/collection-figures/{pid}/{figfile}",
                      "label": figlabel, "visual_type": figtype, "evidence": f"paper.pdf p. {figpage}, {figlabel}",
                      "alt_text": alt, "caption": caption, "selection_rationale": rationale},
            "figure_refs": [figure(pid, figfile, figlabel, figpage, "support the central result", alt, caption,
                                   "The figure supports the stated protocol-specific claim, not an unrestricted generalization.")],
            "equation_refs": equations, "evidence_refs": evidence}

CARDS = [
card("doi-10.1038-s41586-023-06734-w", "version of record",
     "https://www.nature.com/articles/s41586-023-06734-w.pdf",
     "An autonomous laboratory for the accelerated synthesis of inorganic materials", "加速无机材料合成的自主实验室",
     "ai_empirical", "148c46dc8ad025d7", "AI for Science",
     {"doi":"10.1038/s41586-023-06734-w","version":"version of record","title":"An autonomous laboratory for the accelerated synthesis of inorganic materials","authors":["Nathan J. Szymanski","Bernardus Rendy","Yuxing Fei","Rishi E. Kumar","Tanjin He","David Milsted","Matthew J. McDermott","Max Gallant","Ekin Dogus Cubuk","Amil Merchant","Haegyeom Kim","Anubhav Jain","Christopher J. Bartel","Kristin Persson","Yan Zeng","Gerbrand Ceder"],"journal":"Nature","volume":"624","pages":"86–91","published":"2023-11-29","abstract":"A robotic solid-state laboratory combines computed targets, literature-derived recipes, diffraction analysis and active learning to realize 36 of 57 targets in 17 days.","comment":"Open-access version of record; no Crossref update relation found"},
     [sec("作者信息", "作者 Nathan J. Szymanski、Bernardus Rendy、Yuxing Fei 等；Nature 624, 86–91 (2023)，DOI:10.1038/s41586-023-06734-w，发表于2023-11-29。核验12页开放期刊版、Methods、代码/数据声明和Crossref；未发现关联更正或撤稿。"),
      sec("研究问题", "计算筛选可快速提出稳定无机晶体，但固相合成需选择前驱体、温度、时间并解释多相XRD。论文问：能否把计算数据库、文献挖掘、机器人和主动学习闭合为自主循环，在极少人工干预下连续提出、执行、解释并修正粉末合成实验？"),
      sec("背景", "A-Lab从Materials Project与Google DeepMind候选中选择空气稳定目标；文本挖掘模型为目标推荐前驱体和热处理recipe。机器人称量、混合、压片、加热，XRD经ML phase identification判断成功、失败或不确定。", "Figure 1把target selection、recipe optimization、robotic synthesis、XRD interpretation与active-learning feedback串成闭环。所谓自主是流程内决策自动化；设备补料、维护和系统设计仍由人完成。"),
      sec("模型与方法", "每个目标最多进行若干轮实验。若XRD显示中间相，算法结合已知phase diagram与pairwise reaction database调整前驱体、温度或路径；目标形成但含杂相时继续优化。成功要求XRD主相匹配目标，并由Rietveld/人工复核支持。", "57个目标覆盖氧化物与磷酸盐，且是A-Lab首轮尝试，不是随机抽取全部材料空间。计算稳定性使用0 K近似；可合成性还受动力学、挥发、熔化、前驱体可得性和设备温度上限约束。"),
      sec("核心结果与证据", "17天连续运行中，A-Lab对57个目标实现36个，平均每天超过2个。Figure 2逐目标给出稳定性、文献recipe与active-learning轮次；结果证明该特定目标集和仪器协议下的throughput，而不是36种全新功能材料均已完成独立结构/性质表征。", "Figure 3展示失败反应的pairwise analysis如何识别稳定中间体并提出替代路线。17个未实现目标中，11个主要受缓慢动力学影响；另有计算稳定性误差、挥发或熔化等障碍。失败分析说明闭环并非无条件成功。", "36个成功中包含此前无合成报道或记录稀少的化合物，但论文证据核心是粉末XRD相形成。对新结构、纯度、长期稳定性和功能性质仍需材料专门实验；不能把自动识别等同于完整材料认证。"),
      sec("有效性与局限", "目标选择偏向空气稳定、可用固相前驱体和设备温区；recipe模型依赖历史文献偏差。XRD在多相、disorder、相似结构和少量杂相下有歧义，论文保留inconclusive类别并进行人工复核。", "平台尚未自主选择所有前驱体形态、处理挥发性/高压体系或修复硬件。17天与57目标是一次有限campaign；没有与同等资源的人类实验室随机对照，因此‘加速’主要由自动连续运行和产出率支持。"),
      sec("复现与资源", "期刊：https://doi.org/10.1038/s41586-023-06734-w；核验PDF SHA-256：574b5523f857b544ffdf4eff00dd742977636ba90bb09798d413237724542f7e。复现需固定目标列表、稳定性阈值、recipe语料、前驱体库存、机器人误差、炉温程序、XRD采集与phase-matching阈值。", "还需记录每轮决策、人工介入、失败/不确定分类和材料纯度标准。Evidence status: full-text verified version of record and robotic campaign; no independent reproduction performed."),
      sec("阅读指南", "先看 pp.1–2 Figure 1确认闭环边界，再读 pp.2–3 Figure 2的57目标结果；p.4 Figure 3说明主动学习如何改变reaction path，p.5 Figure 4列失败机制。最后读Methods，把自动执行、算法建议和人工复核分开。")],
     "figure-1-a-lab.webp","Figure 1",2,"schematic","A-Lab从计算候选和文献recipe到机器人合成、XRD解释及主动学习反馈的流程图。","A-Lab把目标选择、固相实验和衍射解释闭合为可连续运行的自主循环。","Figure 1直接定义自主实验室的系统边界、实验动作、数据解释与反馈决策链。",
     [{"label":"Reaction free-energy proxy","latex":r"\Delta G_{\rm rxn}=\sum_p\nu_pG_p-\sum_r\nu_rG_r","role":"rank candidate solid-state reaction routes","symbols":{"G":"computed phase free-energy approximation","nu":"stoichiometric coefficient"},"evidence":"paper.pdf pp. 3–4, reaction-path analysis","interpretation":"Thermodynamic ranking narrows routes but does not include all kinetic barriers."}],
     ["paper.pdf pp. 1–2, Figure 1: autonomous workflow","paper.pdf pp. 2–3, Figure 2: 57-target outcomes","paper.pdf pp. 3–5, Figures 3–4: active learning and failure modes","source PDF SHA-256 574b5523f857b544ffdf4eff00dd742977636ba90bb09798d413237724542f7e","Evidence status: full-text verified version of record; no independent reproduction performed."]),

card("doi-10.1038-s41586-023-06735-9", "version of record", "https://www.nature.com/articles/s41586-023-06735-9.pdf",
     "Scaling deep learning for materials discovery", "扩展深度学习以发现材料", "ai_empirical", "155d977401d19b7b", "AI for Science",
     {"doi":"10.1038/s41586-023-06735-9","version":"version of record","title":"Scaling deep learning for materials discovery","authors":["Amil Merchant","Simon Batzner","Samuel S. Schoenholz","Muratahan Aykol","Gowoon Cheon","Ekin Dogus Cubuk"],"journal":"Nature","volume":"624","pages":"80–85","published":"2023-11-29","abstract":"GNoME uses graph networks and large-scale active learning to identify 2.2 million candidate structures below the then-current computational convex hull.","comment":"Open-access version of record; no Crossref update relation found"},
     [sec("作者信息", "作者 Amil Merchant、Simon Batzner、Samuel S. Schoenholz、Muratahan Aykol、Gowoon Cheon、Ekin Dogus Cubuk；Nature 624, 80–85 (2023)，DOI:10.1038/s41586-023-06735-9。核验11页开放期刊版、Methods和Crossref；未发现关联更正或撤稿。"),
      sec("研究问题", "既有材料数据库只有约数万种DFT稳定晶体，而组合/结构空间巨大；早期ML在真正out-of-distribution候选上的稳定性预测不够准确。论文问：扩大graph-network训练、候选生成与DFT主动学习循环，能否提高命中率并发现数量级更多的计算稳定结构？"),
      sec("背景", "GNoME并用composition-only与structure-aware GNN。候选来自prototype substitution和随机结构搜索；模型预测decomposition energy后筛选，DFT松弛提供新标签，再迭代六轮。稳定性按相对于已有竞争相convex hull的PBE能量判断。", "Figure 1展示active-learning pipeline、训练集增长、实验匹配样例和命中率提升。候选是计算结构，‘发现’首先指通过DFT筛选，不等于全部已合成。"),
      sec("模型与方法", "结构模型用图消息传递预测总能量/formation energy；composition模型在没有候选结构时先筛化学式。DFT验证包括结构松弛与相分离能计算，新结果加入训练。最终还训练大规模interatomic potential，测试energy/force prediction与AIMD迁移。", "评估含time-split/novel-composition等OOD划分，但candidate generation与数据库本身存在化学先验。hull会随新竞争相加入而变化；论文明确一些当前稳定候选未来可能被新结构推到hull上方。"),
      sec("核心结果与证据", "六轮主动学习后，作者报告约2.2 million个结构低于当时Materials Project convex hull，其中约381,000个为new compositions；prototype数量从约8,000扩展到45,500。该数字是PBE计算稳定候选，不是实验稳定材料计数。", "Figure 1d显示最终GNoME筛选相对早期模型将DFT hit rate提高约一个数量级。736个预测结构后来与独立实验数据库中的结构匹配，且配套A-Lab工作合成了部分目标；匹配提供外部支持，但不构成对220万候选的普遍验证。", "Figure 3显示interatomic potential随数据和模型规模呈幂律式改善，并在不同温度AIMD上迁移。准确率仍受DFT标签、元素覆盖、磁性/电荷状态和长程相互作用限制，模型速度或低loss不能替代高精度量子化学或实验。"),
      sec("有效性与局限", "PBE formation energy有系统误差，0 K hull忽略熵、缺陷、动力学和合成路线。近hull候选对误差很敏感；结构去重与prototype归类也影响数量。论文的稳定性阈值不是实验可合成性的充分条件。", "大规模active learning消耗大量DFT计算，训练与候选生成由Google内部基础设施完成；完全复现需要数据快照、代码、算力与筛选细节。实验matched structures可能受发表/数据库选择偏差，不能直接估计全体precision。"),
      sec("复现与资源", "期刊：https://doi.org/10.1038/s41586-023-06735-9；项目数据：https://next-gen.materialsproject.org。核验PDF SHA-256：f1af6c92eda54f5bd84eb5012f3010d7bb9167dca337414cffca81623b4a535a。复现需固定database snapshot、DFT functional/settings、hull construction、candidate generators、deduplication、GNN规模、rounds与splits。", "应同时报告候选数、DFT hit rate、hull threshold、元素覆盖和独立实验匹配规则。Evidence status: full-text verified version of record; no independent reproduction performed."),
      sec("阅读指南", "先看 pp.2–3 Figure 1理解GNoME循环和hit-rate指标，再看 pp.3–4 Figure 2的220万结构组成。p.4–5 Figure 3是势函数缩放；最后读Methods和limitations，将模型预测、DFT确认、数据库匹配与实验合成分成四级证据。")],
     "figure-1-gnome.webp","Figure 1",2,"schematic","GNoME候选生成、GNN筛选、DFT验证与主动学习循环及命中率图。","GNoME用六轮主动学习把模型筛选与DFT验证连接起来，提高计算稳定结构的搜索效率。","Figure 1同时给出候选生成流程、训练数据增长、实验匹配样例与搜索效率指标。",
     [{"label":"Convex-hull stability","latex":r"E_{\rm hull}=E_{\rm form}-E_{\rm convex\ hull}","role":"classify a candidate against competing phases","symbols":{"E_form":"DFT formation energy","E_convex_hull":"lowest mixture energy at the same composition"},"evidence":"paper.pdf pp. 2–4, stability definitions","interpretation":"A non-positive value indicates computational stability only within the database and DFT approximation."}],
     ["paper.pdf pp. 2–3, Figure 1: GNoME pipeline and hit rate","paper.pdf pp. 3–4, Figure 2: discovered candidate counts","paper.pdf pp. 4–5, Figure 3: interatomic-potential scaling","source PDF SHA-256 f1af6c92eda54f5bd84eb5012f3010d7bb9167dca337414cffca81623b4a535a","Evidence status: full-text verified version of record; no independent reproduction performed."]),

card("doi-10.1038-s41586-024-07566-y", "version of record", "https://ora.ox.ac.uk/objects/uuid%3Afa1155e9-c2ff-436a-8391-455b622f4e64/files/rt148fj567",
     "AI models collapse when trained on recursively generated data", "AI模型在递归生成数据训练下发生坍塌", "theory_numerics", "474c820b5224b6bf", "Scaling Laws",
     {"doi":"10.1038/s41586-024-07566-y","version":"version of record","title":"AI models collapse when trained on recursively generated data","authors":["Ilia Shumailov","Zakhar Shumaylov","Yiren Zhao","Nicolas Papernot","Ross Anderson","Yarin Gal"],"journal":"Nature","volume":"631","pages":"755–759","published":"2024-07-24","abstract":"Recursive training on model-generated samples loses distribution tails and can converge toward low-variance outputs when original data are not preserved.","comment":"Open-access repository copy of version of record; no Crossref update relation found"},
     [sec("作者信息", "作者 Ilia Shumailov、Zakhar Shumaylov、Yiren Zhao、Nicolas Papernot、Ross Anderson、Yarin Gal；Nature 631, 755–759 (2024)，DOI:10.1038/s41586-024-07566-y。核验Oxford开放仓储中的6页期刊版与Crossref；未发现关联更正或撤稿。"),
      sec("研究问题", "未来模型若从网络抓取数据，训练集会混入前代模型输出。论文问：当每一代生成模型在前一代样本上重新训练时，有限采样、模型表达误差和优化误差如何累积；分布尾部是否先丢失，最终是否出现低方差或单模态坍塌？"),
      sec("背景", "作者把generation i的数据分布记为pi，训练operator F将数据映射为下一代模型，再从该模型有限采样形成Di+1。early collapse指低概率事件/尾部先消失，late collapse指主体分布也收缩并偏离真实分布。", "Figure 1并列递归feedback示意、二维Gaussian toy process与OPT-125m文本例子。关键protocol是后代主要或全部使用前代生成数据；结论不能不加限定地扩展到含持续真实数据、人工过滤或外部校验的synthetic-data训练。"),
      sec("模型与方法", "理论分析包括有限支持离散分布与多维Gaussian近似，分别隔离sampling error以及expressivity/approximation error；补充材料再讨论Hilbert-space density estimation。数值实验用Gaussian mixture、VAE和OPT-125m，逐代生成并重新训练。", "语言实验从固定初始corpus出发，每代采样后训练下一模型，比较perplexity与输出多样性。它是小型开放模型和特定解码/数据替换protocol，不是对所有LLM训练管线的直接预测。"),
      sec("核心结果与证据", "离散模型中有限M使低概率类别有正概率在某代完全未被采到；一旦support消失，纯递归流程不能恢复。Gaussian theorem表明在给定假设下均值误差可漂移且variance趋向零，展示late collapse的解析机制。", "Figure 1的Gaussian mixture和VAE结果先丢掉外围mode，再集中到少数模式；OPT-125m跨generation输出逐渐重复、低多样性且perplexity恶化。三类模型共同支持protocol-specific degenerative trend，但规模有限且没有生产级模型训练。", "保留固定比例原始数据或访问真实分布可显著缓解，说明‘不可逆’是相对于已经丢失且无法重新取得的原始信息。高质量合成数据、teacher更强、去重/importance weighting等情形不由本文实验充分覆盖。"),
      sec("有效性与局限", "作者所谓universal是三类误差在递归生成链中的一般风险，不是任意使用合成数据必然坍塌的数学定理。理论模型简化了优化、data curation、模型更替和web生态；现实训练常混合真实、合成和检索数据。", "尾部消失可能来自有限采样本身，也受解码temperature、过滤与capacity影响。OPT-125m实验规模、代数与corpus有限；不能从图中推断GPT-4等闭源系统的时间尺度或必然结果。"),
      sec("复现与资源", "期刊：https://doi.org/10.1038/s41586-024-07566-y；开放全文来自Oxford Research Archive。核验PDF SHA-256：a461808d21b1715a74306506433662b1ad275f07340db54348138810c341a832。复现需固定初始分布/corpus、每代样本数、真实数据保留比例、model capacity、optimization、decoder和evaluation。", "应分开报告tail coverage、variance、distribution distance、perplexity与文本多样性。Evidence status: full-text verified version of record; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–2 Figure 1和Definitions 2.1–2.3，确认collapse类型与误差来源；再读 pp.2–3离散/Gaussian理论和Theorem 3.1；最后看 pp.3–5 VAE/LLM证据与Discussion，特别检查作者对原始数据保存的限定。")],
     "figure-1-model-collapse.webp","Figure 1",2,"comparison","递归训练反馈、Gaussian分布演化和OPT-125m跨代文本退化。","纯递归生成数据使低概率尾部先消失，并在多种有限模型实验中逐代退化。","Figure 1把定义、toy mechanism和语言模型现象放在同一证据链。",
     [{"label":"Generational learning process","latex":r"p_{i+1}=\mathcal S_M\!\left[F(p_i)\right]","role":"represent training followed by finite resampling","symbols":{"F":"learning operator","S_M":"sampling of M points","p_i":"generation-i distribution"},"evidence":"paper.pdf pp. 1–2, generational-data definition","interpretation":"Approximation and sampling errors are recursively fed into the next generation."}],
     ["paper.pdf pp. 1–2, Figure 1: collapse definition and examples","paper.pdf pp. 2–3: discrete and Gaussian analysis","paper.pdf pp. 3–5: VAE and OPT-125m experiments","source PDF SHA-256 a461808d21b1715a74306506433662b1ad275f07340db54348138810c341a832","Evidence status: full-text verified version of record; no independent reproduction performed."]),

card("doi-10.1038-s41586-025-08744-2", "version of record", "https://www.nature.com/articles/s41586-025-08744-2.pdf",
     "Mastering diverse control tasks through world models", "通过世界模型掌握多样化控制任务", "ai_empirical", "2624e1e69131305b", "World Models",
     {"doi":"10.1038/s41586-025-08744-2","version":"version of record","title":"Mastering diverse control tasks through world models","authors":["Danijar Hafner","Jurgis Pasukonis","Jimmy Ba","Timothy Lillicrap"],"journal":"Nature","volume":"640","pages":"647–653","published":"2025-04-02","abstract":"DreamerV3 uses a recurrent world model and imagined trajectories with one fixed hyperparameter configuration across more than 150 control tasks.","comment":"Version of record; no Crossref update relation found"},
     [sec("作者信息", "作者 Danijar Hafner、Jurgis Pasukonis、Jimmy Ba、Timothy Lillicrap；Nature 640, 647–653 (2025)，DOI:10.1038/s41586-025-08744-2。核验19页期刊版含Extended Data/Methods、代码声明与Crossref；未发现关联更正或撤稿。"),
      sec("研究问题", "强化学习算法常针对Atari、连续控制、3D导航或Minecraft分别调参。论文问：一个学习latent world model、在想象轨迹中训练actor–critic的算法，能否用同一组hyperparameters跨150余种视觉与状态控制任务稳定学习，并在数据效率上达到强基线？"),
      sec("背景", "Dreamer将观察编码为recurrent state-space model，预测reward、continuation与下一latent state；actor在模型生成的imagined trajectories上优化，critic估计回报。DreamerV3引入symlog predictions、two-hot regression、free bits、percentile return normalization和unimix等稳定化技术。", "Figure 1给出world-model、critic和actor三网络的训练流。world model不是生成任意真实世界视频，而是对训练环境中action-conditioned dynamics的任务相关近似。"),
      sec("模型与方法", "评估覆盖Atari、ProcGen、DMLab、Meta-World、Atari100k、Crafter、Minecraft和多类continuous control，总计超过150 tasks。主张强调固定超参数；网络规模随预设配置变化，环境wrapper、action repeat和训练步数仍按benchmark协议。", "模型以latent KL regularization平衡representation与dynamics losses；critic用离散桶预测return，actor通过想象回报反传。Minecraft diamond challenge从pixels与稀疏reward学习，无demonstrations或手工curriculum，但含环境接口和已知action space。"),
      sec("核心结果与证据", "Figure 4汇总各domain normalized scores：固定配置的Dreamer在多数组合上达到或超过专用基线，并通常用更少environment interactions。跨suite平均会掩盖单任务失败，因此正文同时报告各task curves与置信区间。", "Figure 5中Dreamer从头收集经验并在Minecraft获得diamond，成功率随训练增长；这是特定游戏版本、action abstraction和大规模训练下的结果，不等于开放世界一般智能。", "Figure 6的ablations显示return normalization、KL balancing、free bits等对跨domain稳定性重要，模型与数据规模增加时performance总体上升。消融是组合算法内证据，不能唯一证明每项在所有环境的独立因果作用。"),
      sec("有效性与局限", "任务虽多但都为模拟benchmark；没有实体机器人安全、sim-to-real、传感延迟或执行器故障验证。固定hyperparameters不等于零先验：architecture、observation preprocessing、reward和benchmark budget已经确定。", "world model可能在训练分布外产生错误想象，actor会利用model bias；KL与regularizers是经验稳定化而非正确动力学保证。算力、replay和实现质量影响比较，部分baseline结果来自文献而非统一重跑。"),
      sec("复现与资源", "期刊：https://doi.org/10.1038/s41586-025-08744-2；代码：https://github.com/danijar/dreamerv3。核验PDF SHA-256：b34e999951cb5b8b84594f3936b1c395e9d51e563e0932273e9197cee66e37ef。复现需固定commit、JAX/XLA、environment versions、frames/action repeat、replay ratio、model size、seed和evaluation episodes。", "跨算法比较需统一interaction budget和score normalization。Evidence status: full-text verified version of record benchmarks; no independent reproduction performed."),
      sec("阅读指南", "先看 pp.2–3 Figure 1理解latent imagination，再看 p.3 Figure 2的任务范围与p.4 Figure 3的视频预测。核心比较在 p.5 Figure 4，Minecraft和消融看 pp.6–7 Figures 5–6；最后读Methods核对固定与变化的配置。")],
     "figure-4-dreamer-benchmarks.webp","Figure 4",5,"comparison","Dreamer与多种强化学习基线在七个任务域上的标准化分数柱状图。","固定超参数的Dreamer在多个视觉与连续控制suite上取得广泛而非逐任务一致的高性能。","Figure 4是‘多样任务’主张的直接跨域证据，并保留各benchmark与强基线的差异。",
     [{"label":"World-model objective","latex":r"\mathcal L=\mathcal L_{\rm pred}+\beta_{\rm dyn}\mathcal L_{\rm dyn}+\beta_{\rm rep}\mathcal L_{\rm rep}","role":"train predictions while regularizing recurrent latent states","symbols":{"L_pred":"observation/reward/continuation prediction","L_dyn":"dynamics KL","L_rep":"representation KL"},"evidence":"paper.pdf pp. 2–3, learning algorithm","interpretation":"KL balancing controls latent predictability but does not guarantee an exact environment model."}],
     ["paper.pdf pp. 2–3, Figure 1: Dreamer architecture","paper.pdf pp. 3–5, Figures 2–4: domains and benchmark scores","paper.pdf pp. 5–7, Figures 5–6: Minecraft and ablations","source PDF SHA-256 b34e999951cb5b8b84594f3936b1c395e9d51e563e0932273e9197cee66e37ef","Evidence status: full-text verified version of record; no independent reproduction performed."]),

card("doi-10.1038-s41598-022-25638-9", "corrected version of record", "https://www.nature.com/articles/s41598-022-25638-9.pdf",
     "Sparse inference and active learning of stochastic differential equations from data", "从数据稀疏推断并主动学习随机微分方程", "theory_numerics", "d592ab7cb81d857c", "Active Matter",
     {"doi":"10.1038/s41598-022-25638-9","version":"version of record with 2024 author correction","title":"Sparse inference and active learning of stochastic differential equations from data","authors":["Yunfei Huang","Youssef Mabrouk","Gerhard Gompper","Benedikt Sabass"],"journal":"Scientific Reports","volume":"12","article":"21691","published":"2022-12-15","abstract":"Automatic threshold sparse Bayesian learning identifies drift and diffusion libraries, while feedback perturbations improve global SDE inference in multistable simulations.","comment":"Author Correction 10.1038/s41598-024-57801-9 (2024-03-29) supplements the Data Availability statement; scientific results unchanged"},
     [sec("作者信息", "作者 Yunfei Huang、Youssef Mabrouk、Gerhard Gompper、Benedikt Sabass；Scientific Reports 12, 21691 (2022)，DOI:10.1038/s41598-022-25638-9。核验17页开放期刊版及2024 Author Correction 10.1038/s41598-024-57801-9；更正补充Data Availability，不改变结果。"),
      sec("研究问题", "从有限含噪轨迹识别ODE/PDE/SDE时，候选函数库通常高度共线，稀疏阈值又依赖人工调参；多稳态轨迹还可能只覆盖一个basin。论文问：Bayesian Laplace prior能否自动选择稀疏项并给不确定度，以及反馈施加小扰动能否主动探索未采样区域以恢复全局Langevin方程？"),
      sec("背景", "Kramers–Moyal系数由短时间增量估计：一阶对应drift，二阶对应diffusion。把候选函数在数据点上的值组成library Θ，未知系数ξ进入线性逆问题。Automatic threshold sparse Bayesian learning（ATSBL）用Laplacian prior促进稀疏并迭代删除低可信项。", "Figure 1以一维SDE展示从轨迹、binned KM estimates到正确drift/diffusion terms的恢复，并比较Laplacian与Gaussian prior的数据效率。"),
      sec("模型与方法", "作者先用Euler–Maruyama生成已知SDE轨迹，估计conditional moments并按state bins平均；ATSBL同时拟合D(1)与D(2)。随后扩展到time-dependent SDE、Lorenz ODE和PDE，以已知真值评估coefficient error与term selection。", "AISO主动学习循环根据当前模型的不确定性构造外力，使轨迹访问信息不足区域；每轮收集新数据、减去已知控制力并重估方程。控制只在模拟中施加，且假定可测状态与可加控制通道已知。"),
      sec("核心结果与证据", "Figure 1的一维多项式drift/diffusion例中，ATSBL在作者的采样范围内恢复正确非零项和近真值系数；Laplacian prior比Gaussian prior用更少数据达到低误差。该比较依赖候选库含真项和所用阈值/噪声模型。", "Figure 2显示time-dependent force及短trajectory下的adaptive binning能改善KM估计。有限sampling interval会产生系统偏差，作者明确指出需要finite-time corrections；本文重点不是消除这类偏差。", "Figure 3的二维多井势中，被动轨迹长时间困于单井，局部模型对其他区域错误；AISO逐轮降低uncertainty并增加跨saddle rare events，使global drift coefficients接近真值。这是已知模拟系统的闭环验证，不是实验自主发现。"),
      sec("有效性与局限", "稀疏恢复假设真实方程位于候选library；遗漏项、共线性、measurement noise或隐藏变量会造成错误结构。KM估计需要Markov近似、足够小采样间隔和充分bin occupancy；高维时binning与library规模迅速增长。", "AISO需要能够安全、近似加性地操纵系统并知道控制力；真实实验可能有delay、state constraints和control-dependent noise。作者更正只补充代码/数据位置，不增强科学验证。"),
      sec("复现与资源", "期刊：https://doi.org/10.1038/s41598-022-25638-9；更正：https://doi.org/10.1038/s41598-024-57801-9；代码与数据：https://doi.org/10.5281/zenodo.10732552。核验PDF SHA-256：5aaa46b06fb6edc96dbb68f102ca8921959ebb49ae753ff6e98a2118d828e466。", "复现需固定dt、trajectory length、bins、library、prior、threshold iterations、control cost、uncertainty metric与seeds。Evidence status: full-text verified corrected record; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.2–7的KM、library与ATSBL公式，再看 p.9 Figure 1的一维验证；p.10–11 Figure 2检查sampling/binning，p.12 Figure 3是主动学习主结果。最后读Discussion和2024 correction，区分算法结构、模拟性能与数据声明更新。")],
     "figure-1-sde-inference.webp","Figure 1",10,"comparison","一维SDE轨迹、漂移/扩散估计、稀疏恢复方程及prior误差比较。","ATSBL把含噪Kramers–Moyal估计投影到稀疏候选库并恢复已知一维SDE。","Figure 1完整展示从随机轨迹、条件矩估计到稀疏可解释方程及误差比较的基础验证。",
     [{"label":"Kramers–Moyal coefficients","latex":r"D^{(n)}(x)=\frac{1}{n!}\lim_{\tau\to0}\frac{\langle[X(t+\tau)-X(t)]^n\mid X(t)=x\rangle}{\tau}","role":"estimate drift and diffusion from conditional increments","symbols":{"D1":"drift","D2":"diffusion coefficient","tau":"sampling lag"},"evidence":"paper.pdf p. 2, Eq. (2)","interpretation":"Finite lag and sparse occupancy bias these estimates unless their limits are controlled."},{"label":"Sparse library model","latex":r"\mathcal F_\ell(Z)=\Theta(Z)\boldsymbol\xi_\ell","role":"cast equation discovery as sparse linear inference","symbols":{"Theta":"candidate-function library","xi":"sparse coefficients"},"evidence":"paper.pdf p. 3, Eqs. (3)–(4)","interpretation":"Interpretability is conditional on the true terms being represented in the library."}],
     ["paper.pdf pp. 2–7: KM estimation and ATSBL","paper.pdf p. 9, Figure 1: one-dimensional SDE recovery","paper.pdf pp. 10–12, Figures 2–3: adaptive binning and AISO","Author Correction DOI 10.1038/s41598-024-57801-9: Data Availability update","source PDF SHA-256 5aaa46b06fb6edc96dbb68f102ca8921959ebb49ae753ff6e98a2118d828e466","Evidence status: full-text verified corrected record; no independent reproduction performed."])
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids=[]
    for item in CARDS:
        pid=str(item["arxiv_id"]); (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); ids.append(pid)
    print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__ == "__main__": raise SystemExit(main())
