#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 048."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

CARDS = [
card("record-770220f9508b5e10", "arXiv v3 manuscript", "https://arxiv.org/pdf/2106.16078",
     "Identification of Linear Systems with Multiplicative Noise from Multiple Trajectory Data", "由多轨迹数据辨识带乘性噪声的线性系统",
     "theory_numerics", "770220f9508b5e10", "Active Matter",
     {"doi":"10.1016/j.automatica.2022.110486","arxiv_id":"2106.16078","version":"arXiv v3 full text","title":"Identification of Linear Systems with Multiplicative Noise from Multiple Trajectory Data","authors":["Yu Xing","Benjamin Gravell","Xingkang He","Karl Henrik Johansson","Tyler Summers"],"journal":"Automatica","volume":"144","pages":"110486","published":"2022","abstract":"First- and second-moment least squares across independent short rollouts jointly estimate nominal dynamics and an identifiable equivalence class of multiplicative-noise covariances.","comment":"ArXiv v3 accepted manuscript cross-checked with Automatica metadata"},
     [sec("作者信息", "作者 Yu Xing、Benjamin Gravell、Xingkang He、Karl Henrik Johansson、Tyler Summers；Automatica 144, 110486 (2022)，DOI:10.1016/j.automatica.2022.110486。核验 arXiv:2106.16078v3 全文51页，主文19页、其余为证明附录。"),
      sec("研究问题", "离散线性系统的state与input都可能被random matrices乘性扰动。如何仅由多条独立短trajectories同时估计nominal A,B及noise covariance，而且不预先知道noise distribution或系统稳定性？进一步，哪些covariance entries可由state second moments真正辨识？"),
      sec("背景", "模型xt+1=(A+Āt)xt+(B+B̄t)ut。first moments满足由A,B控制的线性递推，second moments经Kronecker lifting后还包含ΣA、ΣB。不同完整covariance matrices可能经reshaping operator产生相同second-moment dynamics，因此数据最多识别equivalence class。", "目录归类为Active Matter，但本文是stochastic control/system identification，并无活性粒子实验；方法可能服务受state-dependent noise影响的系统，本卡保留目录标签同时明确真实学科范围。"),
      sec("模型与方法", "Algorithm 1对nr条独立rollouts在每个短time index平均state及state outer product；第一组least squares估计[A B]，第二组用second-moment residual估计可辨识的reshaped covariance。预设计input first/second moments提供persistent excitation。", "作者证明在controllability与moment-design矩阵满秩时asymptotic consistency；若states/noise bounded，则给failure probability δ下的high-probability error bounds，主要按O(1/√nr)缩小。无需long stable trajectory，但需要能反复reset并独立采样rollouts。"),
      sec("核心结果与证据", "Figure 1在二维example中用Gaussian、uniform和deterministic exploratory inputs各运行50次；A/B及covariance-equivalence estimates随rollout数约按1/√nr下降，支持consistency rate。小nr区有尖峰，反映moment averaging不稳。", "Figure 2显示误差超过固定阈值的经验频率随nr近指数下降，对应finite-sample theorem；Figure 3展示不同但等价ΣA产生相同state second-moment trajectory，说明完整covariance不可唯一恢复不是算法缺陷，而是observational identifiability边界。", "后续与single-trajectory recursive least squares比较，并测试附加additive noise。优势出现在可获得多次独立reset的设定；若只有一条长trajectory，数据协议本身不同，不能直接套用同一保证。"),
      sec("有效性与局限", "non-asymptotic bounds假设bounded states/noise，常见Gaussian noise不严格满足；常数依赖unknown system、condition numbers与input moments。当前averaging可能随rollout length增加反而损失excitation，作者将更高效利用长轨迹列为未来工作。", "covariance只能到equivalence class，除非增加结构假设；state必须完全观测，input独立且可控。数值实验规模小，没有真实系统、partial observation、correlated rollouts或closed-loop adaptive input验证。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2106.16078；期刊：https://doi.org/10.1016/j.automatica.2022.110486。PDF SHA-256：c20d29a8ef086ab776862a6ebbb996c7d9ee64aee21ea6cccd5b85cf00795a4a。正文未给公开代码仓库。", "复现需固定A/B、ΣA/ΣB、rollout length ℓ=4、nr grid、input mean/covariance sequences、50 repeats、reshaping convention与matrix norm。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4 model与moment dynamics；pp.5–10看identifiability和Algorithm 1；pp.11–15读consistency/error bounds；pp.16–19看Figures 1–5和limitations；pp.20–51为证明。")],
     "figure-1-consistency.webp","Figure 1",17,"data_plot","nominal matrices与multiplicative-noise covariance估计误差随独立rollout数的变化。","三种input分布下误差整体遵循O(1/√nr)下降，但小样本存在明显波动。","Figure 1是渐近一致性与有限rollout实践行为的直接数值证据。",
     [{"label":"Multiplicative-noise system","latex":r"x_{t+1}=(A+\bar A_t)x_t+(B+\bar B_t)u_t","role":"separate nominal linear dynamics from state- and input-dependent random matrices","symbols":{"A,B":"nominal system matrices","bar_A,bar_B":"zero-mean multiplicative noise","u_t":"designed exploratory input"},"evidence":"paper.pdf p. 2, Eq. (1)","interpretation":"Covariance identification is generally only possible up to the equivalence class inducing the same second moments."}],
     ["paper.pdf pp. 2–6: system and moment equations","paper.pdf pp. 6–10: identifiability and Algorithm 1","paper.pdf pp. 11–15: consistency and finite-sample theorems","paper.pdf pp. 16–19, Figures 1–5: numerical validation","source PDF SHA-256 c20d29a8ef086ab776862a6ebbb996c7d9ee64aee21ea6cccd5b85cf00795a4a","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-7d4e1f2895b79b9b", "JMLR 2021 full text", "https://www.jmlr.org/papers/volume22/20-1288/20-1288.pdf",
     "Online stochastic gradient descent on non-convex losses from high-dimensional inference", "高维推断非凸损失上的在线随机梯度下降",
     "theory_numerics", "7d4e1f2895b79b9b", "Training Dynamics",
     {"doi":None,"arxiv_id":"2003.10409","version":"JMLR 22 (2021) full text","title":"Online stochastic gradient descent on non-convex losses from high-dimensional inference","authors":["Gerard Ben Arous","Reza Gheissari","Aukosh Jagannath"],"journal":"Journal of Machine Learning Research","volume":"22","pages":"1–51","published":"2021","abstract":"The first nonzero derivative of the population loss at zero overlap defines an information exponent that sets polynomial sample thresholds for online SGD from random initialization.","comment":"Final JMLR article; corresponding preprint arXiv:2003.10409"},
     [sec("作者信息", "作者 Gerard Ben Arous、Reza Gheissari、Aukosh Jagannath；Journal of Machine Learning Research 22(106), 1–51 (2021)，对应 arXiv:2003.10409。核验JMLR最终全文51页；期刊页面未列DOI。"),
      sec("研究问题", "在high-dimensional teacher-student inference中，online SGD从随机起点优化random non-convex sample losses。需要多少独立samples才能与ground truth形成非平凡overlap并最终consistent？是否存在不依赖全局convexity或uniform derivative control的统一complexity参数？"),
      sec("背景", "参数约束在N维sphere，teacher θN固定，population risk只通过overlap m=θ·θN/N变化。作者把m=0附近population drift首个非零阶定义为information exponent k：k越高，随机起点的signal越弱，初始search越困难。", "online设定每步使用一个新sample且不复用；结论描述高维渐近、rotationally invariant data和指定step-size scaling，不等价于finite dataset的multi-epoch minibatch SGD。"),
      sec("模型与方法", "作者将projected SGD的overlap过程分成search、descent和local convergence三个阶段，以martingale concentration控制sample noise，并对time-rescaled dynamics建立law-of-large-numbers limit。上/下界给一致估计所需M随dimension N的多项式阈值，其指数由k决定。", "应用覆盖phase retrieval、generalized linear models、online PCA、spiked tensor inference及单神经元supervised learning。对Hermite activation，information exponent由与teacher signal相关的首个非零Hermite coefficient决定。"),
      sec("核心结果与证据", "主定理表明k=1任务近线性samples即可启动，k=2出现N log N尺度，k≥3需要约N^{k-1}量级（精确上下界含小指数/对数条件）；大多数samples消耗在从随机overlap O(N^{-1/2})逃离无信息区域。", "一旦达到固定正overlap，descent阶段在较少额外samples内遵循确定性population flow，局部阶段再收敛到teacher。这种两时间尺度解释为何warm start显著降低难度。", "Figure 2.1比较activation x²与x³−3x：随机起点前者平滑进入高overlap，后者长期停留后陡升，且sample/time尺度大得多；Figure 2.2 warm start使两者都快速下降，Figure 2.3展示不同initialization和step-size trajectories。"),
      sec("有效性与局限", "结果依赖单index/低秩teacher结构、sphere constraint、fresh independent samples及regularity/moment assumptions。information exponent只描述m≈0局部signal，若population loss有额外bad attractors、anisotropy或model mismatch，单一k不能概括全部动力学。", "渐近阈值并非精确finite-N sample recommendation，图中每条件只有少量runs。现代deep networks、minibatch、momentum/Adam、data reuse与representation learning均不在定理范围。"),
      sec("复现与资源", "全文：https://www.jmlr.org/papers/v22/20-1288.html；预印本：https://arxiv.org/abs/2003.10409。JMLR PDF SHA-256：713b2af1c17706a24a21f7316000a114b8870569983c76e881b40e7cb095eab9。正文未给代码仓库。", "复现Figure 2需固定N=3000、sample counts α、activation/Hermite polynomial、random/warm starts、sphere projection、step-size schedule和four-run seeds。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–6 model与information exponent；pp.7–12看三个学习阶段和sample thresholds；pp.13–16读Figures 2.1–2.3；pp.17–31看applications；pp.32–51为proofs。")],
     "figure-2-random-start.webp","Figure 2.1",14,"comparison","二次与三次Hermite activation下随机初始化online SGD的overlap trajectories。","information exponent更高的任务在无信息区停留更久，需要更大的sample/time尺度才进入快速下降。","Figure 2.1把抽象sample exponent转化为可见的search-phase bottleneck。",
     [{"label":"Information exponent","latex":r"k=\min\{j\ge1:\Phi^{(j)}(0)\ne0\}","role":"measure the first population-loss signal visible near zero overlap","symbols":{"Phi":"population loss as a function of overlap","k":"information exponent","m":"student-teacher overlap"},"evidence":"paper.pdf pp. 5–8, definition and threshold discussion","interpretation":"The exponent controls the random-start search phase under the paper's high-dimensional online assumptions."}],
     ["paper.pdf pp. 1–8: inference model and information exponent","paper.pdf pp. 8–13: search/descent/local thresholds","paper.pdf pp. 13–16, Figures 2.1–2.3: SGD trajectories","paper.pdf pp. 17–31: phase retrieval, PCA, tensors and neural examples","source PDF SHA-256 713b2af1c17706a24a21f7316000a114b8870569983c76e881b40e7cb095eab9","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-7fc155cd48360cde", "arXiv v4 manuscript", "https://arxiv.org/pdf/0910.2097",
     "Information Theory and Renormalization Group Flows", "信息论与重整化群流",
     "theory_numerics", "7fc155cd48360cde", "Renormalization Group",
     {"doi":"10.1016/j.physa.2011.08.014","arxiv_id":"0910.2097","version":"arXiv v4 full text","title":"Information Theory and Renormalization Group Flows","authors":["S. M. Apenko"],"journal":"Physica A: Statistical Mechanics and its Applications","volume":"391","pages":"62–77","published":"2012","abstract":"Conditional entropy quantifies information discarded by a Wilsonian step, while mutual information and entropy per site provide monotonicity statements for selected real-space decimations.","comment":"ArXiv v4 full text cross-checked with Physica A metadata"},
     [sec("作者信息", "作者 S. M. Apenko；Physica A 391, 62–77 (2012)，DOI:10.1016/j.physa.2011.08.014。核验 arXiv:0910.2097v4 全文13页。"),
      sec("研究问题", "Wilsonian RG积分掉fast variables，直觉上丢失information并应不可逆。能否用Shannon entropy、conditional entropy与mutual information构造一般的RG monotone？为什么总entropy下降本身不足以排除limit cycles或复杂RG flows？"),
      sec("背景", "将microscopic variables分为slow η与fast ψ，joint distribution p(η,ψ)在coarse graining后变为p(η)。链式法则H(η,ψ)=H(η)+H(ψ|η)说明丢失量是非负conditional entropy。", "但H是extensive，RG同时减少degrees of freedom；即使总H下降，也可能只是system size缩小而非couplings沿flow不可逆。需要考察entropy per site或size-independent subleading term。连续变量differential entropy还依赖measure/units，作者主要在lattice examples中工作。"),
      sec("模型与方法", "论文定义fast–slow mutual information I(η;ψ)=H(η)+H(ψ)−H(η,ψ)，计算1D Ising decimation、Gaussian model和spin-1 real-space RG。对隔点decimation，在sublattices对称时利用mutual-information positivity推导renormalized entropy density不减。", "还研究triangular-lattice majority-rule/block-spin transformations，指出coarse-grained mapping若确定且多对一，conditional distributions和block correlations决定lost information；并讨论additive constant/free-energy关系。"),
      sec("核心结果与证据", "单步总entropy严格满足H(slow)≤H(all)，但这不是c-theorem。对于1D隔点decimation，两个sublattices有相同entropy，I≥0给h'≥h，即每剩余site的信息entropy沿RG增长；这在该变换下提供irreversibility方向。", "Figure 1画1D/2D decimation partitions；Figure 2显示spin-1 model在(x,y)couplings平面上的RG flow与四个fixed points A–D、critical line AC。沿箭头entropy per site增长，并在fixed points取0、ln2、(1/2)ln2等值。", "Figure 3的triangular block-spin说明更一般变换中mutual information仍可定义，但不能自动给普适monotone。文章以examples和inequalities提出信息论视角，不声称证明任意quantum/continuum RG的c/a/F theorem。"),
      sec("有效性与局限", "关键monotonicity只对某些real-space decimations、translation symmetry和恰当normalized entropy成立。differential entropy可为负且随coordinate scaling变，continuous fields需要relative entropy或regulator；paper没有解决scheme dependence。", "entropy per site增长方向与通常central charge decrease不是同一quantity；size-independent additive term被提出为候选但未一般构造。复杂RG、gauge constraints、quantum entanglement和non-equilibrium coarse graining不在证明范围。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/0910.2097；期刊：https://doi.org/10.1016/j.physa.2011.08.014。PDF SHA-256：4109eebe56299a24f41ac80c87af0508af767b6ac384f4fb891f4ff28a4710d3。无代码需求或仓库。", "复核需固定log base、entropy normalization、block/decimation map和spin-1 coupling coordinates；可按Eqs. (12)–(35)逐步计算conditional/mutual information与fixed-point values。Evidence status: full-text verified analytical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 entropy chain rule与问题；pp.4–6看mutual information和Ising decimation；p.8 Figure 2读spin-1 RG flow；pp.9–11看block-spin examples；pp.11–13读适用边界与结论。")],
     "figure-2-decimation-flow.webp","Figure 2",8,"phase_diagram","spin-1 lattice model在两个couplings上的decimation RG flow、fixed points及各点entropy值。","该例中entropy per lattice site沿RG箭头增加，展示由mutual-information positivity得到的不可逆方向。","Figure 2是文章信息论monotonicity主张的具体可视化，而非普适RG相图。",
     [{"label":"Fast-slow information loss","latex":r"H(\eta,\psi)-H(\eta)=H(\psi\mid\eta)\ge0","role":"quantify information discarded when fast variables are integrated out","symbols":{"eta":"retained slow variables","psi":"discarded fast variables","H":"Shannon entropy"},"evidence":"paper.pdf pp. 2–3, entropy chain rule","interpretation":"Positivity proves loss of total information but not by itself a size-normalized RG Lyapunov function."}],
     ["paper.pdf pp. 1–3: entropy and conditional information","paper.pdf pp. 4–6, Figure 1: mutual information and decimation","paper.pdf pp. 7–9, Figure 2: spin-1 RG flow","paper.pdf pp. 9–11, Figure 3: block-spin transformations","source PDF SHA-256 4109eebe56299a24f41ac80c87af0508af767b6ac384f4fb891f4ff28a4710d3","Evidence status: full-text verified analytical study; no independent reproduction performed."]),

card("record-8364a2a233d4ec9e", "NeurIPS 2021 proceedings PDF", "https://proceedings.neurips.cc/paper_files/paper/2021/file/940392f5f32a7ade1cc201767cf83e31-Paper.pdf",
     "Diffusion Schrödinger Bridge with Applications to Score-Based Generative Modeling", "扩散Schrödinger桥及其在基于得分的生成建模中的应用",
     "theory_numerics", "8364a2a233d4ec9e", "Flow Matching",
     {"doi":None,"arxiv_id":"2106.01357","version":"NeurIPS 2021 proceedings full text","title":"Diffusion Schrödinger Bridge with Applications to Score-Based Generative Modeling","authors":["Valentin De Bortoli","James Thornton","Jeremy Heng","Arnaud Doucet"],"journal":"Advances in Neural Information Processing Systems","volume":"34","pages":None,"published":"2021","abstract":"Diffusion Schrödinger Bridge alternates learned forward and backward Markov kernels as a continuous-state IPF approximation, correcting finite-time endpoint mismatch in score-based diffusion.","comment":"Proceedings PDF verified; corresponding preprint is arXiv:2106.01357"},
     [sec("作者信息", "作者 Valentin De Bortoli、James Thornton、Jeremy Heng、Arnaud Doucet；NeurIPS 2021。核验会议正式PDF全文15页；对应 arXiv:2106.01357。会议PDF未列DOI，本卡不推测。"),
      sec("研究问题", "score-based generative modeling需让forward noising SDE在终点足够接近Gaussian prior；短T或少steps会留下endpoint mismatch。能否把生成建模写成path-space entropy-regularized optimal transport，即Schrödinger bridge，并用多次forward/backward修正使有限时间两端精确匹配？"),
      sec("背景", "Schrödinger bridge在reference diffusion path measure附近寻找满足data和prior marginals的最小KL process。Iterative Proportional Fitting交替投影两个endpoint constraints，类似discrete Sinkhorn；reverse-time drifts可由score/conditional regression估计。", "第一轮DSB等价于传统SGM的reverse fit；后续轮次也更新forward drift，从而补偿pN≠pprior。‘finite time exact’属于理想IPF/continuous model极限，neural approximation、finite particles和Euler discretization仍产生误差。"),
      sec("模型与方法", "作者先离散reference diffusion为N-step Markov chain，交替用regression拟合backward kernels Bkn和forward kernels Fkn，构成Diffusion SB。理论分析IPF KL convergence、time-discretization和early SGM error，并给OU-like reference下的bounds。", "实验用2D toy distributions验证marginals，MNIST/CelebA用reduced U-Net，扫描N=12–50与DSB iterations；另做Swiss-roll到S-curve、EMNIST到MNIST的arbitrary endpoint interpolation。"),
      sec("核心结果与证据", "Figure 1在T=0.2、N=20时显示初始forward diffusion未到Gaussian且第一轮reverse未回data；第五轮DSB后两个endpoint明显匹配，直观展示迭代修正。", "Figures 2–3定量/可视验证toy ground-truth mean、variance、covariance和四种2D shapes随20轮逼近。Figures 5–6显示CelebA在N=12等少steps时图像与FID随DSB iterations改善；作者明确说实现尚不与SOTA竞争。", "Figure 7展示non-Gaussian endpoint间bridge，支持DSB不仅是data-to-Gaussian generator，也可视为continuous-state Sinkhorn工具。T过小时score在prior support附近难学，论文在discussion中承认质量下降。"),
      sec("有效性与局限", "每个DSB iteration需重新训练forward/backward regressors，少sampling steps不等于总训练更便宜；errors会在IPF iterations中传播。理论常数依赖regularity、finite entropy与kernel assumptions，未覆盖任意neural score class。", "image实验低分辨率且缺少强SOTA baselines、多seed error bars和完整compute accounting。FID改善来自该配置，不能推出所有short-schedule diffusion都应增加IPF rounds；T、N、model capacity需联合调节。"),
      sec("复现与资源", "全文：https://proceedings.neurips.cc/paper/2021/hash/940392f5f32a7ade1cc201767cf83e31-Abstract.html；项目：https://vdeborto.github.io/publication/schrodinger_bridge/。PDF SHA-256：a896f34cefb188d72f04ce3490d43a0ed03db4e4ffd2a5bf2dab115855f0fe57。", "复现需固定reference drift/noise、T、N、DSB rounds、kernel regression/U-Net、forward/backward sampling counts、optimizer、FID implementation与dataset preprocessing。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 Figure 1与SB/IPF联系；pp.3–6看DSB算法和theory；pp.7–10读Figures 2–7实验；pp.10–15为discussion、proof sketches和实现细节。")],
     "figures-2-3-dsb-convergence.webp","Figures 2–3",9,"comparison","DSB对ground-truth moments的迭代收敛及四个二维分布从第一轮到第二十轮的改善。","后续IPF rounds修正第一轮SGM留下的短时endpoint mismatch。","Figures 2–3同时给出moment-level与distribution-level convergence证据。",
     [{"label":"Schrödinger bridge objective","latex":r"P^\star=\arg\min_{P:\,P_0=p_{\rm data},\,P_T=p_{\rm prior}}\mathrm{KL}(P\,\|\,P^{\rm ref})","role":"find the closest diffusion path measure satisfying both endpoint marginals","symbols":{"P_ref":"reference diffusion","P_0,P_T":"endpoint marginals","KL":"path-space relative entropy"},"evidence":"paper.pdf pp. 2–4, Schrödinger bridge formulation","interpretation":"Practical DSB approximates alternating path-space projections with learned discrete kernels."}],
     ["paper.pdf pp. 1–3, Figure 1: endpoint mismatch and DSB idea","paper.pdf pp. 3–6: IPF/DSB algorithm and theory","paper.pdf pp. 8–9, Figures 2–4: toy and CelebA results","paper.pdf p. 10, Figures 5–7: FID and endpoint interpolation","source PDF SHA-256 a896f34cefb188d72f04ce3490d43a0ed03db4e4ffd2a5bf2dab115855f0fe57","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-8ae792fdc6e22ec9", "arXiv v3 manuscript", "https://arxiv.org/pdf/2203.11010",
     "Sparse inference and active learning of stochastic differential equations from data", "从数据稀疏推断并主动学习随机微分方程",
     "theory_numerics", "8ae792fdc6e22ec9", "Active Matter",
     {"doi":"10.1038/s41598-022-25638-9","arxiv_id":"2203.11010","version":"arXiv v3 full text","title":"Sparse inference and active learning of stochastic differential equations from data","authors":["Yunfei Huang","Youssef Mabrouk","Gerhard Gompper","Benedikt Sabass"],"journal":"Scientific Reports","volume":"12","pages":"21691","published":"2022","abstract":"Automatic-threshold sparse Bayesian learning recovers differential-equation terms, while feedback control actively drives stochastic trajectories into under-sampled regions to improve global drift inference.","comment":"ArXiv v3 full text cross-checked with Scientific Reports metadata"},
     [sec("作者信息", "作者 Yunfei Huang、Youssef Mabrouk、Gerhard Gompper、Benedikt Sabass；Scientific Reports 12, 21691 (2022)，DOI:10.1038/s41598-022-25638-9。核验 arXiv:2203.11010v3 全文17页。"),
      sec("研究问题", "从trajectory识别SDE drift/diffusion时，稀疏回归既要自动选threshold，又受metastable wells造成的phase-space sampling bias：粒子长期困在一个basin，只能局部知道force。能否用Bayesian sparsity稳定选项，并让当前推断反过来设计control perturbation主动探索未知区域？"),
      sec("背景", "Kramers–Moyal coefficients D(1)、D(2)可由short-time increments估计，再表示为library Θ(z)与稀疏weights。作者采用Laplacian prior的Bayesian compressive sensing，并以train/test error迭代删除小weights，称ATSBL。", "active loop AISO根据当前估计potential minima添加flattening control，生成新trajectory，去除已知control后重新推断uncontrolled drift。它要求能安全、准确施加外力，并假设control作用可从动力学中分离。"),
      sec("模型与方法", "ATSBL把threshold candidates通过cross-validation式test error筛选，Laplacian prior相比Gaussian prior更强稀疏。对短SDE trajectories，binning与probability cutoff排除采样极少区域；同一framework还用于Lorenz ODE和reaction–diffusion PDE。", "AISO在1D three-well和2D Mexican-hat-like force fields中循环：定位估计minimum、加入局部control使well变平、收集controlled samples、subtract control并更新global model。以coefficient deviation DIC评估每轮改善。"),
      sec("核心结果与证据", "Figure 1的double-well SDE显示ATSBL从一条10^6-step noisy trajectory恢复drift与diffusion；Laplacian prior减少所需samples并更快threshold convergence。Figure 2说明short trajectory未访问区域的不确定性和binning cutoff作用。", "Figure 3是主动学习主证据：无control的1D/2D trajectories困在局部区域；逐轮flatten estimated wells后覆盖扩大，DIC下降。2D streamlines从第一轮明显偏离真值，到第十轮pink identified field基本贴合black ground truth。", "Figures 4–5在Lorenz和reaction–diffusion上展示ODE/PDE term discovery。所有ground truth与active-control结果来自simulation，论文没有真实在线实验或control-cost/safety benchmark。"),
      sec("有效性与局限", "library必须含真实函数，finite-difference KM estimates要求足够小Δt且近似Markov/Itô；measurement noise、colored noise、hidden variables和rare transitions会偏置。threshold选于有限test split，不保证结构posterior calibration。", "AISO依据当前错误模型设计control，可能把系统推向危险或model-invalid区域；本文control landscape可解析且模拟可reset。高维系统的potential minima搜索、actuator constraints和control/data tradeoff尚未解决。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2203.11010；期刊：https://doi.org/10.1038/s41598-022-25638-9。PDF SHA-256：b34b22371e314236ef7e23c26e9cb3b15216c51bdd5de2082b3d71d18bd5d7d6。正文说明源码和数据可由通讯作者获取，未列公开仓库URL。", "复现需固定Δt、trajectory length、library、Laplace hyperparameters、threshold grid/train-test split、bin cutoff、control amplitude/width、AISO iterations和DIC definition。Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–5 ATSBL与threshold；pp.6–9看SDE/KM和binning；pp.9–12看AISO feedback；p.16 Figure 3是主证据，pp.14–17汇总所有figures和完整captions。")],
     "figure-3-active-learning.webp","Figure 3",16,"schematic","AISO反馈控制示意及1D/2D受困轨迹、DIC迭代与识别force-field streamlines。","主动flatten当前估计的local wells扩大采样域，使全局drift模型逐轮接近真值。","Figure 3同时呈现控制机制、coverage变化和推断误差收敛。",
     [{"label":"Sparse KM regression","latex":r"F^{(n)}=\Theta(z)W^{(n)}+\epsilon,\qquad n\in\{1,2\}","role":"identify drift and diffusion from Kramers–Moyal estimates over a candidate library","symbols":{"F_n":"estimated KM coefficient samples","Theta":"function library","W_n":"sparse weights"},"evidence":"paper.pdf pp. 2–5, linear inverse formulation","interpretation":"Finite-time increments and incomplete phase-space sampling can bias both targets and selected terms."}],
     ["paper.pdf pp. 1–5: sparse Bayesian learning and ATSBL","paper.pdf pp. 6–9: SDE/KM inference and binning","paper.pdf pp. 9–12: AISO active-learning loop","paper.pdf pp. 14–17, Figures 1–5: complete visual evidence","source PDF SHA-256 b34b22371e314236ef7e23c26e9cb3b15216c51bdd5de2082b3d71d18bd5d7d6","Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."])
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids=[]
    for item in CARDS:
        pid=str(item["arxiv_id"])
        (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
        ids.append(pid)
    print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__ == "__main__": raise SystemExit(main())
