#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 047."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

CARDS = [
card("record-390b8e9b9479daa3", "arXiv v1 manuscript", "https://arxiv.org/pdf/1609.06401",
     "Data-driven discovery of partial differential equations", "偏微分方程的数据驱动发现",
     "theory_numerics", "390b8e9b9479daa3", "Active Matter",
     {"doi":"10.1126/sciadv.1602614","arxiv_id":"1609.06401","version":"arXiv v1 full text","title":"Data-driven discovery of partial differential equations","authors":["Samuel H. Rudy","Steven L. Brunton","Joshua L. Proctor","J. Nathan Kutz"],"journal":"Science Advances","volume":"3","pages":"e1602614","published":"2017","abstract":"PDE-FIND constructs a library of nonlinear fields and spatial derivatives and uses sequential threshold ridge regression to identify parsimonious governing PDEs.","comment":"Four-page arXiv main article; code and supplementary material are linked by the authors"},
     [sec("作者信息", "作者 Samuel H. Rudy、Steven L. Brunton、Joshua L. Proctor、J. Nathan Kutz；Science Advances 3, e1602614 (2017)，DOI:10.1126/sciadv.1602614。核验 arXiv:1609.06401v1 主文4页及作者公开PDE-FIND资源。"),
      sec("研究问题", "给定空间位置与时间上的field measurements，能否自动从大量候选非线性项与偏导数中发现控制PDE，而无需逐个枚举模型？核心难点是数值微分放大measurement noise、library columns高度相关，以及单条特殊解可能同时满足多个不同方程。"),
      sec("背景", "PDE-FIND把所有u(x,t)样本堆成U，把已知potential或|u|等辅助量堆成Q，再生成Θ(U,Q)，其列包含1、u、u²、空间导数及乘积。目标Ut=Θξ中ξ应稀疏；这把symbolic PDE discovery变为support selection。", "目录将该记录归为Active Matter，但论文是通用PDE discovery方法，示例包括Navier–Stokes、KdV、Burgers、Schrödinger harmonic oscillator与diffusion；本卡不把它表述成活性物质专用算法。"),
      sec("模型与方法", "作者用polynomial interpolation估计含噪数据导数，必要时先SVD filtering。Sequential Threshold Ridge Regression反复做ridge fit并删除小系数；外层根据residual、nonzero count和condition number选择Pareto折中。Figure 1还给出subsampling与compressed library路径以降低大数据成本。", "实验从数值解抽样，逐步增加noise和减少data；多initial conditions用于区分单soliton上等价的advection表达与真正KdV非线性。另把Brownian trajectory切成短段、用位移histograms恢复diffusion equation，并从Re=100 cylinder wake识别vorticity Navier–Stokes。"),
      sec("核心结果与证据", "Figure 1以Navier–Stokes为例连接data collection、library/derivatives、sparse regression、identified dynamics以及compressed solve，是PDE-FIND全过程证据。它展示算法结构，不是performance曲线。", "正文报告在多个canonical PDE上可恢复正确term support和接近真值的coefficients；对traveling-wave KdV，单一soliton会被误认为linear advection，而加入另一amplitude solution后恢复6uux+uxxx，清楚暴露identifiability条件。", "cylinder-wake示例从一个边界条件发现vorticity equation，并用该方程预测其他boundary conditions；结果说明发现显式law可能比纯trajectory fit更可迁移，但仍在同一控制方程和数值数据家族内。"),
      sec("有效性与局限", "成功依赖candidate library包含真项、导数估计足够准、ξ确实稀疏且columns可辨识。threshold和penalty是model-selection choices；复杂噪声、irregular grids、weak solutions/shocks、hidden variables或nonlocal/fractional operators可能破坏流程。", "四页主文只给概要，详细parameter sweeps依赖supplement。合成PDE有ground truth，现实系统通常没有；低residual不能排除结构上不同但观测等价的方程。多trajectory策略缓解但不保证全局identifiability。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/1609.06401；期刊：https://doi.org/10.1126/sciadv.1602614；代码/补充：https://github.com/snagcliffs/PDE-FIND。PDF SHA-256：f917731f626566618d7b50530a6d42e433620b88b44125796bae7e278ac3721f。", "复现需固定PDE solver、sample grid/trajectories、noise definition、polynomial derivative stencil、library degree、ridge λ、threshold search与Pareto penalty。Evidence status: full-text verified numerical/methodological study; no independent reproduction performed."),
      sec("阅读指南", "先读 p.1问题和library思想；p.2 Figure 1与Eqs. (1)–(3)看完整算法；p.3看Brownian/KdV identifiability，p.4看Navier–Stokes、Schrödinger结果与资源链接。")],
     "figure-1-pde-find-workflow.webp","Figure 1",2,"schematic","PDE-FIND从field data到library、稀疏回归、identified dynamics及compressed solve的工作流。","把PDE发现归约为候选项矩阵中的稀疏系数选择，并可对子样本压缩求解。","Figure 1是方法的端到端结构证据，并明确显示数据、微分与稀疏选择的接口。",
     [{"label":"Sparse PDE library regression","latex":r"U_t=\Theta(U,Q)\xi,\qquad \hat\xi=\arg\min_\xi\|\Theta\xi-U_t\|_2^2+\epsilon\kappa(\Theta)\|\xi\|_0","role":"select a parsimonious set of nonlinear and derivative terms","symbols":{"Theta":"candidate PDE library","xi":"sparse coefficients","Q":"known auxiliary fields"},"evidence":"paper.pdf p. 2, Eqs. (2)–(3)","interpretation":"Correct recovery requires an expressive and identifiable library plus reliable numerical derivatives."}],
     ["paper.pdf pp. 1–2: problem, library and STRidge","paper.pdf p. 2, Figure 1: workflow and compression","paper.pdf p. 3, Figures 2–3: diffusion and KdV identifiability","paper.pdf p. 4: Navier–Stokes and other case studies","source PDF SHA-256 f917731f626566618d7b50530a6d42e433620b88b44125796bae7e278ac3721f","Evidence status: full-text verified numerical/methodological study; no independent reproduction performed."]),

card("record-52733712d33cf0cd", "arXiv v1 manuscript", "https://arxiv.org/pdf/2102.13231",
     "A Quantitative Kinetic Theory of Flocking with Three-Particle-Closure", "带三粒子闭合的定量集群运动动力学理论",
     "theory_numerics", "52733712d33cf0cd", "Active Matter",
     {"doi":"10.1103/PhysRevE.104.034604","arxiv_id":"2102.13231","version":"arXiv v1 full text","title":"A Quantitative Kinetic Theory of Flocking with Three-Particle-Closure","authors":["Rüdiger Kürsten","Thomas Ihle"],"journal":"Physical Review E","volume":"104","pages":"034604","published":"2021","abstract":"A BBGKY-like kinetic theory resolves the full pair correlation and uses a three-particle closure to predict the flocking threshold beyond mean field.","comment":"ArXiv v1 manuscript cross-checked with Physical Review E metadata"},
     [sec("作者信息", "作者 Rüdiger Kürsten、Thomas Ihle；Physical Review E 104, 034604 (2021)，DOI:10.1103/PhysRevE.104.034604。核验 arXiv:2102.13231v1 全文25页，含数值实现与closure appendix。"),
      sec("研究问题", "Vicsek-like alignment中的pair和higher-order correlations在disordered phase也不可忽略，mean-field显著错估flocking onset。论文问：能否自洽求完整two-particle distribution，并用可控的three-particle closure改善transition noise预测，同时与agent-based simulation定量比较？"),
      sec("背景", "模型由二维constant-speed particles的generalized Langevin equations构成，interaction是interaction disk内所有邻居方向的非加性平均。作者从N-particle Fokker–Planck hierarchy推导one-、two-、three-particle distribution equations；homogeneous/isotropic mean field会丢失角度与空间相关。", "ring-kinetic truncation保留g2并忽略connected g3；进一步closure把g3表示为pair correlations的组合。该体系与Vicsek模型定性相似但采用continuous-time angular noise和特定nonadditive interaction，临界值不可直接移植到所有Vicsek variants。"),
      sec("模型与方法", "作者利用translation/rotation symmetry把pair correlation写为h(r,α,Δφ)，并用Fourier modes离散角度、空间grid数值积分kinetic equations。C2、D2等integrated pair-correlation parameters进入polar mode线性稳定性；three-particle closure为hierarchy补上leading spatial correlations。", "agent simulations使用C1=ρπR²=1、R=v=1、N=509等设定，扫描angular noise σ；在disordered regime逐点比较h，使用polar-order variance定位σc,sim，并以微小polar perturbation测试kinetic theory的disordered-state stability。"),
      sec("核心结果与证据", "Figures 5–14显示ring-kinetic theory对不同r、α、Δφ的完整pair correlation总体跟随agent simulations，尤其interaction disk内aligned增强和anti-aligned抑制；靠近transition时偏差增大，作者没有隐去这一breakdown。", "Figure 15比较C2和D2：mean field预测σc,mf=0.607，直接simulation给σc,sim=0.53(1)，ring theory给0.505(5)，加入g3 closure后为0.525，明显接近simulation。方向相关促进disorder，因此相较mean field把ordering推向更低noise。", "Figure 16用polar-order fluctuations定位simulation onset，Figure 17用finite waiting-time stability估计ring threshold。临界数值依赖有限N、grid和waiting time，‘good agreement’不等于critical exponents或first-order banded regime的完整理论。"),
      sec("有效性与局限", "closure在低noise/ordered regime偏差变大，kinetic equations到stationarity耗时极长；作者主要从disordered侧的linear/numerical stability推断onset，而非稳态ordered distribution。g3 closure不是systematic error-bounded expansion。", "采用homogeneous assumptions，未解析traveling bands、finite-size hysteresis或strong density inhomogeneity；Fourier/spatial truncation与agent sampling都有数值误差。参数集中在代表性density/speed，结论的普适性需额外扫描。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2102.13231；期刊：https://doi.org/10.1103/PhysRevE.104.034604。PDF SHA-256：f472427647cb89e7f033c1c7a07b9b7f65bb3421784f0b259e4cd0063404a1c7。正文未给公开代码仓库。", "复现需固定C1、R、v、N、σ scan、Fourier cutoffs、spatial resolution、initial g2/polar perturbation、waiting time与agent seeds。Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4 model与hierarchy；pp.5–9看cluster/Fourier truncation；pp.10–14读h(r,α,Δφ)与Figure 15；pp.14–18看transition stability和three-particle closure；appendix核对closure algebra。")],
     "figure-15-transition-correlations.webp","Figure 15",14,"comparison","integrated pair correlations C2、D2随noise变化及simulation、ring theory、g3 closure与mean-field临界线。","三粒子closure把预测flocking threshold从ring值0.505修正到0.525，接近simulation的0.53。","Figure 15把局域correlation accuracy与macroscopic ordering threshold置于同一比较中。",
     [{"label":"Connected pair correlation","latex":r"f_2(1,2)=f_1(1)f_1(2)+g_2(1,2)","role":"retain two-particle spatial and orientational dependence beyond mean field","symbols":{"f_1":"one-particle distribution","f_2":"two-particle distribution","g_2":"connected pair correlation"},"evidence":"paper.pdf pp. 4–7, cluster expansion","interpretation":"Closing the hierarchy at g2 or approximating g3 introduces uncontrolled errors near strong ordering."}],
     ["paper.pdf pp. 2–7: microscopic model and hierarchy","paper.pdf pp. 8–10: ring-kinetic equations and numerical method","paper.pdf pp. 10–14, Figures 5–15: pair correlations and threshold","paper.pdf pp. 14–18, Figures 16–22: onset and three-particle closure","source PDF SHA-256 f472427647cb89e7f033c1c7a07b9b7f65bb3421784f0b259e4cd0063404a1c7","Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."]),

card("record-53f0bbe1eb06ac49", "arXiv v3 manuscript", "https://arxiv.org/pdf/1904.09406",
     "DeepMoD: Deep learning for Model Discovery in noisy data", "DeepMoD：从噪声数据中用深度学习发现模型",
     "ai_empirical", "53f0bbe1eb06ac49", "AI for Science",
     {"doi":"10.1016/j.jcp.2020.109985","arxiv_id":"1904.09406","version":"arXiv v3 full text","title":"DeepMoD: Deep learning for Model Discovery in noisy data","authors":["Gert-Jan Both","Subham Choudhury","Pierre Sens","Remy Kusters"],"journal":"Journal of Computational Physics","volume":"428","pages":"109985","published":"2021","abstract":"A coordinate neural network supplies smooth fields and automatic derivatives while sparse regression selects a PDE library, enabling discovery from small noisy data and electrophoresis images.","comment":"ArXiv v3 includes main paper and supplementary information"},
     [sec("作者信息", "作者 Gert-Jan Both、Subham Choudhury、Pierre Sens、Remy Kusters；Journal of Computational Physics 428, 109985 (2021)，DOI:10.1016/j.jcp.2020.109985。核验 arXiv:1904.09406v3 全文20页及GitHub实现。"),
      sec("研究问题", "PDE-FIND类方法依赖numerical derivatives，含噪、稀疏或不规则抽样时容易失效；PINN通常假定方程结构已知。DeepMoD问：能否让neural network同时平滑插值u(x,t)、通过automatic differentiation生成derivatives，并在训练中从candidate library稀疏选出未知PDE？"),
      sec("背景", "coordinate MLP以(x,t)为输入输出û，data loss拟合观测；autodiff得到ût、ûx、ûxx等，library Θ在网络输出上构造。sparse regression系数ξ与network weights联合优化，periodic thresholding删除scaled coefficients较小的项。", "它不是用许多已标注PDE训练的foundation model；每个dataset都要从头优化一个implicit neural representation。平滑网络是强inductive bias，可能抹掉shock或small-scale terms。"),
      sec("模型与方法", "总loss含data fit、PDE residual和L1 sparsity，作者设置动态loss weighting避免某项主导。训练先让网络形成合理field approximation，再启动threshold；归一化library columns后比较coefficients，最终回到unscaled values恢复物理参数。", "合成测试覆盖Burgers（含/不含shock）、KdV、2D advection-diffusion和Keller–Segel，扫描sample count与Gaussian noise。现实实验追踪gel electrophoresis中紫色dye的二维advection/diffusion，以5000个space-time points拟合。"),
      sec("核心结果与证据", "论文报告若干合成方程仅需O(10²) samples，并在特定case中容忍最高75% noise；这一上限不是所有PDE共同保证，shock、library order和noise realization会改变可恢复范围。Figures 2–5展示coefficient paths、threshold与reconstruction。", "Figure 6显示electrophoresis图像、dye density snapshots与scaled coefficients。threshold后得到0.31uy+0.011uxx+0.009uyy=0；第二个dye区域给近似相同drift约0.3与diffusion约0.01，构成有限的重复测量证据。", "实验中某些higher-order nonlinear coefficients虽小却非零，作者明确指出automatic threshold未必给理想sparse solution，固定0.1阈值或coefficient clustering更合适。这是现实噪声与model misspecification的关键失败边界。"),
      sec("有效性与局限", "性能依赖network architecture、spectral bias、training schedule、loss balancing、library scaling与threshold。联合非凸优化可能在不同seed给不同support；文中没有对所有设置给置信区间。shock等非光滑解与高频结构对MLP/autodiff并不天然友好。", "electrophoresis只有一个装置与两个dye regions，颜色强度到density的标定、边界和光照可能带systematic error；identified advection-diffusion是相容模型而非微观因果证明。候选library之外的项不会被发现。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/1904.09406；代码/数据：https://github.com/PhIMaL/DeePyMoD；期刊：https://doi.org/10.1016/j.jcp.2020.109985。PDF SHA-256：627bb95c4b14bf43f8bf1379a7131009048627215c780a9e95d3362bb1d0e569。", "复现需固定sample coordinates/noise、MLP layers、optimizer、loss weights、library、coefficient normalization、threshold start/frequency/value和seed。Evidence status: full-text verified numerical/experimental study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 Figure 1与joint loss；pp.3–6看Burgers/KdV robustness，pp.6–7看Keller–Segel；p.8 Figure 6是实验主证据；pp.13–20核对supplementary training与2D tests。")],
     "figure-6-electrophoresis.webp","Figure 6",8,"comparison","电泳装置时间序列、dye density快照及候选PDE系数的训练演化。","从5000个实验space-time samples筛出二维advection和diffusion项，并在另一dye区域得到近似参数。","Figure 6是DeepMoD从真实图像测量到可解释PDE的完整实验链。",
     [{"label":"Joint data and physics residual","latex":r"\mathcal L=\|u_\theta-U\|_2^2+\|\partial_tu_\theta-\Theta(u_\theta)\xi\|_2^2+\lambda\|\xi\|_1","role":"fit a smooth coordinate field while sparsely selecting its governing PDE","symbols":{"u_theta":"neural field approximation","Theta":"automatic-differentiation library","xi":"PDE coefficients"},"evidence":"paper.pdf pp. 2–3, DeepMoD loss","interpretation":"Thresholding and non-convex training can change the selected support, especially for real noisy data."}],
     ["paper.pdf pp. 1–3, Figure 1: architecture and loss","paper.pdf pp. 3–7, Figures 2–5: synthetic noise/sample tests","paper.pdf p. 8, Figure 6: electrophoresis experiment","paper.pdf pp. 13–20: supplementary optimization and 2D cases","source PDF SHA-256 627bb95c4b14bf43f8bf1379a7131009048627215c780a9e95d3362bb1d0e569","Evidence status: full-text verified numerical/experimental study; no independent reproduction performed."]),

card("record-71b518265b03b2fb", "JMLR 2025 full text", "https://www.jmlr.org/papers/volume26/23-1605/23-1605.pdf",
     "Stochastic Interpolants: A Unifying Framework for Flows and Diffusions", "随机插值：流与扩散的统一框架",
     "theory_numerics", "71b518265b03b2fb", "Flow Matching",
     {"doi":None,"arxiv_id":"2303.08797","version":"JMLR 26 (2025) full text / arXiv v4-equivalent revision","title":"Stochastic Interpolants: A Unifying Framework for Flows and Diffusions","authors":["Michael S. Albergo","Nicholas M. Boffi","Eric Vanden-Eijnden"],"journal":"Journal of Machine Learning Research","volume":"26","pages":"1–80","published":"2025","abstract":"Stochastic interpolants bridge arbitrary endpoint densities and induce shared transport and Fokker–Planck equations, yielding trainable ODE or tunable-noise SDE generative models.","comment":"Evidence uses the final 80-page JMLR article published September 2025"},
     [sec("作者信息", "作者 Michael S. Albergo、Nicholas M. Boffi、Eric Vanden-Eijnden；Journal of Machine Learning Research 26(209), 1–80 (2025)。核验JMLR最终全文80页；对应 arXiv:2303.08797v4。JMLR页面未列期刊DOI，本卡不把arXiv DataCite DOI误作期刊DOI。"),
      sec("研究问题", "flow matching与score-based diffusion都用continuous dynamics把base density ρ0变成target ρ1，却常以不同objectives和samplers表述。论文问：能否从一个可设计的random interpolating process同时导出transport equation和一族Fokker–Planck equations，并用可采样的quadratic losses学习velocity、score和denoiser？"),
      sec("背景", "stochastic interpolant定义xt=I(t,x0,x1)+γ(t)z，其中(x0,x1)来自任意coupling、z为Gaussian且γ在端点为0。由conditional expectations得到density velocity b、score s与denoiser ηz；同一ρ(t)既可由probability-flow ODE采样，也可由含可调diffusion ε的forward/backward SDE采样。", "框架在population且function class充分时精确连接端点densities；实际neural regression、finite samples与numerical ODE/SDE integration都会引入误差。选择interpolant/coupling并非无关紧要，它改变学习难度和path geometry。"),
      sec("模型与方法", "Theorems 6–8给出ρ(t)的transport/Fokker–Planck equations，b和s分别是quadratic objectives的唯一L2 minimizers。作者推导SDE likelihood/cross-entropy estimators，并说明SDE drift regression可控制likelihood，而deterministic ODE还需控制Fisher divergence。", "后续覆盖one-sided、two-sided、mirror和Gaussian encoding-decoding designs，联系denoising、rectified flow、stochastic localization与Schrödinger bridge；Algorithms 1–4给训练和Heun/dopri5 sampling。实验包括2D checkerboard、128D Gaussian mixtures及128×128 Oxford flowers。"),
      sec("核心结果与证据", "理论表明在相同learned velocity/score下，ε=0给probability-flow ODE，ε>0给保持相同marginal path的SDE family；diffusion可作为sampling-time控制量，而不需要重新定义target path。exactness仍取决于真实b、s，而非近似网络。", "Figure 8对2D checkerboard扫描四种γ与ε=0,0.5,1,2.5，报告|logρ1−logρ̂(1)|的mean/variance。特定γ在ODE下最好；在较大ε时SDE用同一b̂、ŝ获得更低误差，支持stochastic sampling可缓解估计误差，但只是一组toy density结果。", "128D Gaussian-mixture实验进一步测projected KL；Oxford flowers显示ODE/SDE生成和mirror resampling。论文没有以现代大规模image benchmark做SOTA FID竞争，重点是统一理论和design-space demonstration。"),
      sec("有效性与局限", "正则性、绝对连续性、端点和有限能量条件支撑PDE/SDE推导；singular data manifold、nonsmooth interpolant或score在端点爆炸需特别处理。likelihood bounds含不可直接观测的approximation errors，有限网络不一定满足。", "实验规模有限，γ、coupling、ε、solver steps和network共同影响结果；大ε需要更多SDE steps，质量提升不等于wall-clock更优。Schrödinger bridge recovery还需优化整个interpolant，而非任意固定path自动最优。"),
      sec("复现与资源", "全文：https://jmlr.org/papers/v26/23-1605.html；arXiv：https://arxiv.org/abs/2303.08797；代码：https://github.com/malbergo/stochastic-interpolants。JMLR PDF SHA-256：5b9e56d46b89ed4880d94a778b7334508015a0fe6ce020e738768f5907e3478b。", "复现需固定JMLR revision、endpoint coupling、I与γ、b/s/denoiser parameterization、ε、ODE/SDE solver和steps、density estimator及random seeds。Evidence status: full-text verified theory/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–6 Figure 1和定义；pp.7–21看velocity/score objectives与ODE/SDE；pp.21–32看likelihood；pp.33–45看interpolant designs和Schrödinger bridge；pp.47–53读Figures 7–15实验，pp.56–80为证明和配置。")],
     "figure-8-sde-sample-quality.webp","Figure 8",48,"comparison","不同noise schedule γ与sampling diffusion ε下checkerboard终点log-density误差的mean和variance。","同一learned drift/score下，非零ε的SDE sampling在该实验中通常优于确定性ODE，并受γ设计影响。","Figure 8定量展示框架两个独立旋钮——interpolant noise schedule与sampler diffusion——的相互作用。",
     [{"label":"Stochastic interpolant","latex":r"x_t=I(t,x_0,x_1)+\gamma(t)z,\qquad z\sim\mathcal N(0,I)","role":"construct a finite-time density bridge whose marginals admit ODE and SDE samplers","symbols":{"I":"endpoint interpolation map","gamma":"latent-noise schedule","x_0,x_1":"coupled endpoint samples"},"evidence":"paper.pdf pp. 6–10, Definition 1 and Figure 2","interpretation":"Endpoint exactness is a population statement; learned fields and numerical integration determine practical error."}],
     ["paper.pdf pp. 5–12: stochastic interpolant and density equations","paper.pdf pp. 12–31: quadratic objectives, samplers and likelihood","paper.pdf pp. 32–45: design choices and Schrödinger bridges","paper.pdf pp. 47–53, Figures 7–15: numerical and image examples","source PDF SHA-256 5b9e56d46b89ed4880d94a778b7334508015a0fe6ce020e738768f5907e3478b","Evidence status: full-text verified theory/numerical study; no independent reproduction performed."]),

card("record-736b3f9c1f275b31", "arXiv v1 manuscript", "https://arxiv.org/pdf/2411.04990",
     "Clustering in Causal Attention Masking", "因果注意力掩码中的聚类",
     "theory_numerics", "736b3f9c1f275b31", "Transformer Theory",
     {"doi":"10.52202/079017-3673","arxiv_id":"2411.04990","version":"arXiv v1 full text / NeurIPS 2024","title":"Clustering in Causal Attention Masking","authors":["Nikita Karagodin","Yury Polyanskiy","Philippe Rigollet"],"journal":"Advances in Neural Information Processing Systems","volume":"37","pages":"115652–115681","published":"2024","abstract":"A continuous-depth causal self-attention particle system converges asymptotically to one cluster for arbitrary key-query matrices and identity values, while displaying long-lived metastable clusters related to Rényi parking.","comment":"ArXiv v1 full text cross-checked with NeurIPS proceedings metadata"},
     [sec("作者信息", "作者 Nikita Karagodin、Yury Polyanskiy、Philippe Rigollet；NeurIPS 2024 / Advances in Neural Information Processing Systems 37, 115652–115681，DOI:10.52202/079017-3673。核验 arXiv:2411.04990v1 全文22页。"),
      sec("研究问题", "以continuous-depth self-attention把tokens视为球面上的interacting particles时，full attention可利用mean-field gradient-flow结构分析；causal mask令第k个token只看1…k，interaction非对称并失去该结构。论文问：tokens是否仍最终聚成一个cluster，数值中长期多cluster又如何解释？"),
      sec("背景", "模型在sphere上演化，每个token按softmax of key-query similarities朝先前tokens的value-weighted average移动，再投影到tangent space。causal ordering使早期tokens成为单向anchors，不能用exchangeable mean-field limit。", "这是tied weights、continuous layer time、无MLP且常设V=Id的抽象动力系统；token clustering是representation geometry现象，不直接等价于language-model rank collapse、semantic grouping或训练性能。"),
      sec("模型与方法", "Theorem 4.1证明V=Id且Q、K任意时，除零测initial conditions外所有tokens渐近收敛到单一cluster。证明依靠causal triangular structure逐token归纳和sphere几何，而不是能量下降。作者也讨论V的principal eigenspace扩展。", "为解释metastability，二维K=Q=V=I、large β情形映射到Rényi parking：初始序列中相距约β^{-1/2}的早期tokens成为centers。Lemma 5.1给strong centers的quasi-stationary时间，Theorem 5.2在centers固定假设下证明其余tokens被吸引。"),
      sec("核心结果与证据", "Theorem 4.1比早先只处理scaled-identity Q/K/V的结果更广：arbitrary key-query matrices仍在V=Id下eventual consensus。它是t→∞结论，不提供实际layer depth内的收敛速率。", "Figure 2用n=200、d=2、β=64从uniform circle出发：t=5–10快速形成多个clusters，到t=150仍约七个，t=500才有一个center合并；这解释为何有限数值观察与single-cluster theorem表面矛盾。", "Rényi-center density预测β^{(d−1)/2}尺度，二维图中red/black centers捕捉部分clusters；作者明确说strong centers不能解释全部clusters。跨attention加入冻结anchors时，Theorem 5.1类结果描述向anchors收敛。"),
      sec("有效性与局限", "作者的limitations指出两段理论尚未闭合：strong centers可长时近静止，固定centers可吸引其余particles，但未证明在真实共同演化中每个center于O(1)时间捕获Ω(n) tokens；甚至ω(1)捕获仍未证。", "实用模型限制包括跨层tied weights和缺失Transformer核心MLP；LayerNorm、residual、finite depth、trained Q/K/V及data-dependent token distribution会改变动力学。Figure 2是单一低维参数示例，不能作为LLM内部cluster数量预测。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2411.04990；会议：https://doi.org/10.52202/079017-3673。PDF SHA-256：9c5f7ea6c418cfdb991af9b499e0c0995a18cfd0943c62f4155ee64ef5fe188e。正文未给公开代码仓库。", "复现Figure 2需固定n=200、d=2、β=64、K=Q=V=I2、uniform initial angles、ODE solver/time grid和Rényi-center definitions δ=4β^{-1/2}。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 causal particle system与贡献；pp.4–5看Theorem 4.1，p.6 Figure 2理解metastability；pp.6–9读Rényi parking results和limitations；pp.13–22核对proofs与auxiliary figures。")],
     "figure-2-metastable-clusters.webp","Figure 2",6,"trajectory","200个球面tokens从均匀分布到多个长寿命cluster并缓慢合并的时间序列。","有限时间呈现七个左右metastable clusters，而定理只保证无限时间最终单cluster。","Figure 2最清楚地区分asymptotic theorem与实际可观察的长寿命多cluster状态。",
     [{"label":"Causal self-attention dynamics","latex":r"\dot x_k=P_{x_k}^{\perp}\frac{\sum_{j\le k}e^{\beta\langle Qx_k,Kx_j\rangle}Vx_j}{\sum_{j\le k}e^{\beta\langle Qx_k,Kx_j\rangle}}","role":"model continuous-depth masked attention as a triangular interacting-particle system","symbols":{"x_k":"token on the sphere","P_perp":"tangent projection","beta":"attention inverse temperature"},"evidence":"paper.pdf pp. 2–4, causal self-attention system","interpretation":"The main clustering theorem sets V=Id and does not model MLP or learned finite-depth layers."}],
     ["paper.pdf pp. 1–4: causal attention particle model","paper.pdf pp. 4–5: asymptotic clustering Theorem 4.1","paper.pdf p. 6, Figure 2: metastable cluster trajectory","paper.pdf pp. 6–9: Rényi parking results and limitations","source PDF SHA-256 9c5f7ea6c418cfdb991af9b499e0c0995a18cfd0943c62f4155ee64ef5fe188e","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."])
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids = []
    for item in CARDS:
        pid = str(item["arxiv_id"])
        (OUT / f"{pid}.json").write_text(json.dumps(item, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        ids.append(pid)
    print(json.dumps({"installed": ids}, ensure_ascii=False))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
