#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 051."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"data"/"collection_cards"

CARDS=[
card("record-b378b5e0070cf951","arXiv v2 manuscript","https://arxiv.org/pdf/2510.22026",
"Normalization in Attention Dynamics","注意力动力学中的归一化","theory_numerics","b378b5e0070cf951","Transformer Theory",
{"doi":None,"arxiv_id":"2510.22026","version":"arXiv v2 full text","title":"Normalization in Attention Dynamics","authors":["Nikita Karagodin","Shu Ge","Yury Polyanskiy","Philippe Rigollet"],"journal":"Advances in Neural Information Processing Systems","volume":"38","pages":None,"published":"2025","abstract":"Transformer normalization schemes become speed regulators for interacting token directions on a sphere, yielding distinct clustering and representation-collapse dynamics.","comment":"NeurIPS 2025 manuscript; DOI not asserted"},
[sec("作者信息","作者 Nikita Karagodin、Shu Ge、Yury Polyanskiy、Philippe Rigollet；NeurIPS 2025，对应 arXiv:2510.22026v2。核验全文23页；当前正文未列稳定DOI或页码，本卡不推测。"),
sec("研究问题","Post-LN、Pre-LN、Mix-LN、Peri-LN和nGPT都改变residual与normalization的位置。它们如何影响深层token directions的移动速度、聚类和representation collapse？能否在同一动力系统中比较，而不只追踪gradient variance？"),
sec("背景","将embedding写成x_k=r_k θ_k，其中θ_k位于单位sphere。pure attention使token directions成为相互作用粒子；归一化不只控制norm，还通过r_k和residual placement调节每层角速度。","模型省略FFN并重点分析forward representations。它是架构机制的理论proxy，不等价于完整LLM训练或下游能力评测。"),
sec("模型与方法","作者为各normalization写出discrete update，再取continuous-depth limit，得到共享球面interaction direction乘以scheme-specific speed factor。Tables 1–2列Post/Pre/Mix/Peri-LN与nGPT的调速项。","对两token可解模型推导cosine similarity γ(t)与速度γ̇，随后用256 tokens及随机attention weights模拟平均cosine similarity，并分析early/terminal velocity。"),
sec("核心结果与证据","Figure 1明确归一化位置；Figure 2显示Post-LN最快冲向cosine 1并collapse，Pre-LN因norm增长逐渐减速，Mix-LN折中，而Peri-LN在早层保持速度、深层避免过快collapse。","Figure 3显示nGPT步长α_t决定收敛：constant、root、linear与组合schedule产生不同terminal behavior。Figure 4的random-weight实验总体复现理想two-token ordering，支持speed-regulation解释。","结论偏向Peri-LN的有效速度profile，但证据主要来自简化动力学；没有大规模预训练loss、benchmark accuracy或compute-controlled消融。"),
sec("有效性与局限","理论假设pure attention、特定continuous-depth scaling和简化weight dynamics；LayerNorm的centering、FFN、multi-head、causal mask、position encoding及训练后权重相关性可能改变轨迹。","cosine clustering是representation collapse诊断之一，不等价于信息、rank或task performance。scheme优劣依赖深度、residual scaling与optimizer，不能由单一two-token模型普遍排序。"),
sec("复现与资源","全文：https://arxiv.org/abs/2510.22026。PDF SHA-256：aaaf02755d23a0324eaa99261831b37a23f5197315c87d95e8a5a960b8cf8c10。正文未给公开代码仓库。","复现需固定n,d、β、initial token geometry、Q/K/V distribution、depth discretization及各scheme的α_t/r_t schedule，并报告cosine、angular speed与norm。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–4 Figure 1与统一球面动力学；pp.5–8看Tables 1–2和Figures 2–4；pp.9–12读scheme比较；pp.13–23为证明与补充实验。")],
"figure-2-speed-regulation.webp","Figure 2",7,"comparison","不同normalization下两token cosine similarity、角速度及phase portrait。","归一化通过scheme-specific speed factor改变接近聚类态的速度，而非改变共同interaction direction。","Figure 2同时展示状态、速度和phase portrait，是全文speed-regulation主张最直接的比较证据。",
[{"label":"Directional decomposition","latex":r"x_k(t)=r_k(t)\,\theta_k(t),\qquad \theta_k(t)\in\mathbb{S}^{d-1}","role":"separate token magnitude from spherical representation direction","symbols":{"r_k":"token norm","theta_k":"token direction","k":"token index"},"evidence":"paper.pdf pp. 2–4, normalized attention dynamics","interpretation":"Normalization schemes act primarily by changing the speed assigned to directional motion."}],
["paper.pdf pp. 1–4, Figure 1: normalization placements","paper.pdf pp. 4–7, Tables 1–2: continuous-time speed factors","paper.pdf pp. 7–9, Figures 2–4: clustering dynamics","paper.pdf pp. 13–23: proofs and supplementary experiments","source PDF SHA-256 aaaf02755d23a0324eaa99261831b37a23f5197315c87d95e8a5a960b8cf8c10","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-c65ba3d17ce216b5","arXiv manuscript","https://arxiv.org/pdf/2006.13203",
"Machine learning active-nematic hydrodynamics","机器学习活性向列液晶流体动力学","theory_experiment","c65ba3d17ce216b5","Active Matter",
{"doi":"10.1073/pnas.2016708118","arxiv_id":"2006.13203","version":"arXiv full text","title":"Machine learning active-nematic hydrodynamics","authors":["Jonathan Colen","Ming Han","Rui Zhang","Steven A. Redford","Linnea M. Lemma","Link Morgan","Paul V. Ruijgrok","Raymond Adkins","Zev Bryant","Zvonimir Dogic","Margaret L. Gardel","Juan J. De Pablo","Vincenzo Vitelli"],"journal":"Proceedings of the National Academy of Sciences","volume":"118","pages":"e2016708118","published":"2021","abstract":"Neural networks trained on active-nematic simulations infer activity and elasticity from director movies and forecast experimental dynamics in latent space.","comment":"PNAS article with arXiv manuscript and public Zenodo code"},
[sec("作者信息","作者 Jonathan Colen、Ming Han、Rui Zhang 等；PNAS 118, e2016708118 (2021)，DOI:10.1073/pnas.2016708118。核验 arXiv:2006.13203 全文16页及代码/数据声明。"),
sec("研究问题","active nematic的activity α、elastic constant K等宏观参数难从microscopic motor chemistry推导，velocity也常不可直接测。能否仅由director-field movies估计这些参数的时空变化，并在不显式求解方程时预测chaotic field的短期未来？"),
sec("背景","active stress σ^a_ij=α n_i n_j与Frank elasticity竞争，决定defect density和correlation length。实验为microtubule–kinesin及actin–myosin systems，ATP或light控制motor activity。","参数估计网络先用lattice-Boltzmann synthetic data监督训练，再迁移到实验；forecast网络则可直接用实验序列训练。两任务的数据依赖和物理先验不同。"),
sec("模型与方法","参数网络含convolution、LSTM和dense layers，以nematic-symmetry representation输入多个frames，输出α、K等；大图按patch预测并ensemble。训练library扫描2D/3D simulation parameters。","forecast使用autoencoder压缩director image，recurrent residual model在latent space逐步预测，再decode；为抑制chaos误差累积，周期性把真实frame重新初始化，并与machine-learning-informed LB比较。"),
sec("核心结果与证据","Figure 1显示2D/3D director输入、network和activity recovery；simulation test中预测α/K接近truth。Figure 3把microtubule–kinesin实验的ATP变化映射为α上升、K下降，并让ML-calibrated LB的correlation length与defect density匹配实验。","Figure 3还展示light-activated spatially heterogeneous activity：网络重建illumination region内外α/K fields。forecast部分在短期比未校准simulation更接近实验，但长期仍受chaotic divergence限制。","实验参数并无独立ground-truth meter；其可信度来自simulation-trained inverse mapping、趋势一致性和ML+LB统计回放，而非直接测量α、K。"),
sec("有效性与局限","simulation-to-experiment存在domain gap；training continuum model、one-constant approximation、imaging noise和director extraction都会影响参数。α与K可存在组合identifiability，单个movie未必唯一分离。","forecast以短期图像误差为主，周期性truth reset不等于长期free-running prediction。样本来自少数active-nematic platforms，control仅被提出，未执行闭环实验。"),
sec("复现与资源","全文：https://arxiv.org/abs/2006.13203；期刊：https://doi.org/10.1073/pnas.2016708118；代码与LB资料归档：https://doi.org/10.5281/zenodo.4541607。PDF SHA-256：408a37b1cba94293f967617ed4493d3d8639ba7caf1e46c5e376fe3852288e35。","复现需固定director extraction、pixel scale、simulation α/K ranges、patching、CNN/LSTM architecture、dropout、ATP/light protocols与forecast reset interval。Evidence status: full-text verified theory/simulation/experiment study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–3 Figure 1参数网络；pp.4–6看ATP/light experiments和Figure 3；pp.6–9读forecast；pp.10–16为methods、额外实验与参考文献。")],
"figure-3-activity-fields.webp","Figure 3",5,"comparison","ATP/light control下实验director fields与网络预测activity、elasticity的时间和空间变化。","网络从director movies恢复非均匀hydrodynamic parameters，并用它们校准continuum simulation。","Figure 3同时包含真实实验、受控perturbation和参数场，是论文实验有效性的中心图证。",
[{"label":"Active stress","latex":r"\sigma^{a}_{ij}=\alpha n_i n_j","role":"couple local nematic orientation to active forcing","symbols":{"alpha":"activity coefficient","n":"nematic director","sigma_a":"active stress"},"evidence":"paper.pdf p. 1, Eqs. (1)–(2)","interpretation":"The network estimates activity from director dynamics, not from direct stress measurements."}],
["paper.pdf pp. 1–3, Figure 1: parameter-estimation network","paper.pdf pp. 4–6, Figure 3: ATP and light-controlled experiments","paper.pdf pp. 6–9: latent forecasting","paper.pdf pp. 10–15: active-nematic and ML methods","source PDF SHA-256 408a37b1cba94293f967617ed4493d3d8639ba7caf1e46c5e376fe3852288e35","Evidence status: full-text verified theory/simulation/experiment study; no independent reproduction performed."]),

card("record-c8d3e59a68e46938","arXiv manuscript","https://arxiv.org/pdf/2306.15873",
"Discovering stochastic partial differential equations from limited data using variational Bayes inference","用变分贝叶斯从有限数据发现随机偏微分方程","theory_numerics","c8d3e59a68e46938","AI for Science",
{"doi":"10.1016/j.cma.2023.116512","arxiv_id":"2306.15873","version":"arXiv full text","title":"Discovering stochastic partial differential equations from limited data using variational Bayes inference","authors":["Yogesh Chandrakant Mathpati","Tapas Tripura","Rajdip Nayek","Souvik Chakraborty"],"journal":"Computer Methods in Applied Mechanics and Engineering","volume":"418","pages":"116512","published":"2024","abstract":"Extended Kramers-Moyal targets and spike-and-slab variational Bayes select sparse drift and diffusion operators for canonical SPDEs from limited ensembles.","comment":"CMAME article cross-checked with arXiv full text"},
[sec("作者信息","作者 Yogesh Chandrakant Mathpati、Tapas Tripura、Rajdip Nayek、Souvik Chakraborty；CMAME 418, 116512 (2024)，DOI:10.1016/j.cma.2023.116512。核验 arXiv:2306.15873 全文16页。"),
sec("研究问题","SPDE同时包含空间微分operator、nonlinear drift和state-dependent stochastic diffusion。数据只有少量independent realizations时，怎样构造可回归targets、选择真正的operator terms并量化model/parameter uncertainty？"),
sec("背景","作者扩展Kramers–Moyal：短时间state increment的一阶ensemble moment给drift，二阶moment给diffusion quadratic form。候选library包含u、powers及空间derivatives。","与单轨迹数值微分不同，方法需要同初态或可比较状态下的ensemble responses。发现的diffusion是平方/协方差层面，sign通常不可由二阶矩辨识。"),
sec("模型与方法","先由有限trajectories计算drift/diffusion response vectors与library matrix，再用Spike-and-Slab prior为每个候选项引入Bernoulli inclusion variable。mean-field variational Bayes迭代posterior coefficients、inclusion probabilities和noise variance。","阈值化posterior inclusion probability选择structure，posterior mean/std给coefficient uncertainty。案例为stochastic heat、Allen–Cahn和Nagumo，使用不同data fractions与noise settings。"),
sec("核心结果与证据","Figure 1的Allen–Cahn例在42个basis中选择drift的u、u³、u_xx与constant diffusion，系数接近truth；Figure 2显示discovered SPDE的space-time solution及predictive uncertainty。","后续Figures 3–6对heat/Nagumo和multiplicative noise重复结构恢复，并扫描训练量。有限synthetic examples中posterior inclusion清晰，但误差图依赖同一生成模型与numerical protocol。","作者声称limited data优势来自Bayesian sparsity，但没有覆盖高维2D/3D fields、unknown boundary、measurement noise与hidden variables的统一benchmark。"),
sec("有效性与局限","KM近似要求small Δt、足够ensemble和Itô/Markov假设；finite difference空间导数会放大噪声。library若遗漏真实term或候选高度共线，posterior inclusion不保证物理正确。","Spike-and-Slab VB低估posterior correlation/多峰性风险高于exact Bayes；reported uncertainty主要是所设likelihood内的epistemic estimate，不含model discrepancy和solver bias。"),
sec("复现与资源","全文：https://arxiv.org/abs/2306.15873；期刊：https://doi.org/10.1016/j.cma.2023.116512。PDF SHA-256：828b9b698fddeffa9e4ca7e36d6e4e1837c1bfe2e67d051040f469ffaed27620。正文未给公开代码仓库。","复现需固定Δt、realizations、spatial grid/derivative stencil、library、PIP threshold、prior hyperparameters、VB convergence与SPDE solver seeds。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–4 extended KM；pp.5–7 Spike-and-Slab VB；pp.8–12 Figures 1–6三个SPDE；pp.13–16读局限、附录和参考文献。")],
"figure-1-allen-cahn.webp","Figure 1",9,"data_plot","Allen–Cahn SPDE候选项的posterior inclusion probabilities及发现方程。","变分Spike-and-Slab从42项中保留真实drift operator与constant diffusion，并给出系数。","Figure 1把稀疏selection和最终方程放在同一图中，是算法结构恢复能力最直接的证据。",
[{"label":"SPDE discovery targets","latex":r"\mathbb{E}[\Delta u]/\Delta t\to f(u),\qquad \mathbb{E}[(\Delta u)^2]/\Delta t\to g^2(u)","role":"construct drift and diffusion regression targets from short-time ensembles","symbols":{"f":"SPDE drift operator","g":"noise amplitude","Delta_u":"short-time field increment"},"evidence":"paper.pdf pp. 3–5, extended Kramers-Moyal expansion","interpretation":"The diffusion target identifies a quadratic noise amplitude under the stated sampling assumptions."}],
["paper.pdf pp. 1–5: extended Kramers-Moyal formulation","paper.pdf pp. 5–8: variational spike-and-slab inference","paper.pdf pp. 8–12, Figures 1–6: heat, Allen-Cahn and Nagumo","paper.pdf pp. 12–15: data efficiency and uncertainty discussion","source PDF SHA-256 828b9b698fddeffa9e4ca7e36d6e4e1837c1bfe2e67d051040f469ffaed27620","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-cd01d3578fe73e63","arXiv manuscript","https://arxiv.org/pdf/1710.04906",
"Stochastic continuity equations with conservative noise","具有守恒噪声的随机连续性方程","theory","cd01d3578fe73e63","Statistical Physics",
{"doi":"10.1016/j.matpur.2019.02.002","arxiv_id":"1710.04906","version":"arXiv full text","title":"Stochastic continuity equations with conservative noise","authors":["Benjamin Gess","Scott Smith"],"journal":"Journal de Mathématiques Pures et Appliquées","volume":"128","pages":"225–263","published":"2019","abstract":"Nonlinear conservative Stratonovich noise yields existence and uniqueness of kinetic entropy solutions for continuity equations with rough velocity fields beyond deterministic thresholds.","comment":"Journal article cross-checked with arXiv full text"},
[sec("作者信息","作者 Benjamin Gess、Scott Smith；Journal de Mathématiques Pures et Appliquées 128, 225–263 (2019)，DOI:10.1016/j.matpur.2019.02.002。核验 arXiv:1710.04906 全文42页。"),
sec("研究问题","deterministic continuity equation ∂tρ+div(ρu)=0在velocity u粗糙且div u控制不足时可出现mass concentration与nonuniqueness。加入保持divergence form的非线性、部分退化white noise，是否能恢复entropy solution的existence与uniqueness？"),
sec("背景","线性transport noise可通过随机flow带来regularization by noise。本文研究更一般的conservative perturbation div(B(ρ)∘dW)，它保持空间积分意义上的mass structure，但Itô correction是非线性、可能退化的parabolic operator。","‘噪声改善适定性’是特定假设下的PDE定理，不表示随机扰动总能平滑任何transport equation；噪声结构、B的非退化区间及u的integrability都关键。"),
sec("模型与方法","作者用kinetic formulation把ρ的非线性entropy family提升为(x,ξ)空间indicator，并引入kinetic measure记录dissipation。先对regularized equation建立L1/Lp和gradient-type a priori estimates。","existence通过viscous/regularized approximations、compactness和hydrodynamic limit；uniqueness利用doubling/duality与commutator estimate。关键dual equation的控制借助fully nonlinear parabolic PDE regularity。"),
sec("核心结果与证据","主定理在u∈L1_t W^{1,1}_x且div u只需较弱Lp-type条件、B满足规定growth/nondegeneracy时，给kinetic entropy solution存在唯一，并保持L1 contraction/相关bounds。","相比deterministic DiPerna–Lions常需div u∈L1_tL∞_x，噪声允许更弱divergence regularity；论文把此前linear multiplicative noise推广到nonlinear conservative noise。","全文为定理证明，没有numerical data或物理实验。效果来自noise-induced second-order dual regularity；不应把well-posedness theorem解读为解路径逐点更光滑。"),
sec("有效性与局限","假设针对Euclidean whole space、指定velocity integrability和scalar density；boundary domains、systems、compressible momentum coupling及arbitrary degenerate B不自动覆盖。Stratonovich/Itô形式与mass conservation必须一致处理。","证明提供适定性而非高阶regularity、长时混合或数值scheme convergence。实际流体中噪声是否符合space-homogeneous Brownian conservative form属于另一个建模问题。"),
sec("复现与资源","全文：https://arxiv.org/abs/1710.04906；期刊：https://doi.org/10.1016/j.matpur.2019.02.002。PDF SHA-256：31681141a9f01579a4a674e796c80be5a91adc060ccef3ff17892a31d66732d7。纯解析论文未提供或需要代码。","复核需固定Stratonovich convention、B与Itô correction、kinetic test functions、velocity exponent条件和mollification order；逐一检查a priori estimates、compactness和L1 contraction。Evidence status: full-text verified analytical study; no independent reproduction performed."),
sec("阅读指南","先读 pp.2–7 deterministic背景与主定理；pp.7–10 kinetic definition/estimate；pp.10–21看existence；pp.22–34看uniqueness与commutator；pp.35–42为appendix。")],
"equations-conservative-noise.webp","Eqs. (1.4)–(1.8)",3,"schematic","从线性随机transport到非线性conservative continuity equation的模型链及确定性对照。","divergence-form Stratonovich noise保持守恒结构，并通过Itô correction产生regularizing parabolic effect。","该页集中定义研究对象、已知线性情形与非线性推广，是无图解析论文最可寻址的中心证据。",
[{"label":"Conservative stochastic continuity equation","latex":r"d\rho+\operatorname{div}(\rho u)dt+\nabla B(\rho)\circ dW_t=0","role":"perturb mass transport with nonlinear noise in divergence form","symbols":{"rho":"density","u":"rough velocity field","B":"nonlinear noise flux","W":"Brownian motion"},"evidence":"paper.pdf pp. 2–4, Eqs. (1.4)–(1.8)","interpretation":"The theorem exploits the induced second-order structure under precise assumptions on B and u."}],
["paper.pdf pp. 2–7: models and main theorem","paper.pdf pp. 7–10: kinetic entropy formulation","paper.pdf pp. 10–21: generalized-solution existence","paper.pdf pp. 22–34: uniqueness and commutator estimate","source PDF SHA-256 31681141a9f01579a4a674e796c80be5a91adc060ccef3ff17892a31d66732d7","Evidence status: full-text verified analytical study; no independent reproduction performed."]),

card("record-d370dbf7389a2607","ICML 2024 full text","https://arxiv.org/pdf/2403.11262",
"Understanding Diffusion Models by Feynman’s Path Integral","通过费曼路径积分理解扩散模型","theory_numerics","d370dbf7389a2607","Flow Matching",
{"doi":None,"arxiv_id":"2403.11262","version":"ICML 2024 / arXiv full text","title":"Understanding Diffusion Models by Feynman’s Path Integral","authors":["Yuji Hirono","Akinori Tanaka","Kenji Fukushima"],"journal":"Proceedings of the 41st International Conference on Machine Learning","volume":"PMLR 235","pages":"18324–18351","published":"2024","abstract":"A path-integral representation interpolates stochastic reverse SDEs and probability-flow ODEs through a Planck-like noise parameter and enables WKB likelihood corrections.","comment":"ICML 2024 PMLR metadata cross-checked with arXiv"},
[sec("作者信息","作者 Yuji Hirono、Akinori Tanaka、Kenji Fukushima；ICML 2024, PMLR 235, 18324–18351；对应 arXiv:2403.11262。核验全文27页；PMLR未列传统DOI。"),
sec("研究问题","score diffusion既可用stochastic reverse SDE，也可用deterministic probability-flow ODE采样；二者共享marginals但finite model error下质量不同。能否用Feynman path integral统一描述，并计算stochasticity对negative log-likelihood的修正？"),
sec("背景","Onsager–Machlup/Feynman formalism把trajectory probability写成对所有paths的指数权重。作者引入h∈[0,1]插值：h=1对应reverse SDE，h=0对应probability-flow ODE；h在semiclassical expansion中类似Planck constant。","这是数学类比与计算工具，不意味着diffusion model是量子系统。path integral discretization、Jacobian convention和boundary terms必须明确。"),
sec("模型与方法","从forward diffusion transition kernel构造离散path measure，time reversal推导backward SDE，并用Girsanov形式联系score-matching loss。把h作为noise amplitude后，对path integral作WKB/saddle expansion。","h→0的classical path由coupled probability-flow ODE给出，O(h) fluctuation determinant/Jacobian修正给stochastic model NLL近似。实验用1D Gaussian解析模型及2D Swiss-roll、25-Gaussian learned scores。"),
sec("核心结果与证据","Figure 1区分单条classical path与围绕它的quantum/stochastic paths；Figure 2展示h从ODE到SDE的trajectory spread。Figure 3在1D Gaussian中将exact NLL/W2与WKB近似对比，small h附近趋势吻合。","Table 1和Figure 4比较2D synthetic数据的NLL correction与Wasserstein metrics；适量h可改善model-error下distribution match，但最优h依赖score误差和schedule。","附录Figures 6–14给不同SDE schedules与local-error scaling。实验仅低维synthetic，不支持直接断言image diffusion中某固定stochasticity普遍更好。"),
sec("有效性与局限","WKB是small-h渐近，h=1处截断误差可能大；路径integral的functional determinant与高维Hessian计算昂贵。结论依赖score smoothness、boundary/decay及离散化。","论文未在CIFAR/ImageNet或文本模型验证，NLL approximation与perceptual quality/FID也非同一指标。若score接近perfect，不同h共享marginals，差异主要来自model/numerical error。"),
sec("复现与资源","全文：https://arxiv.org/abs/2403.11262；PMLR：https://proceedings.mlr.press/v235/hirono24a.html。PDF SHA-256：319e47168831877e46e21443719cc7dddcc5876126b6150631882b6b52d2c2ab。论文项目代码：https://github.com/AkinoriTanaka-phys/diffusion_path_integral 。","复现需固定forward SDE、score network/schedule、h grid、ODE/SDE integrator、NFE、NLL/W2 estimator、synthetic seeds和WKB truncation order。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–3 Figure 1与h类比；pp.3–6看path-integral推导；pp.6–9读WKB与Figure 3；pp.9–11看2D experiments；pp.12–27为证明和补充图。")],
"figure-3-wkb-nll.webp","Figure 3",6,"comparison","一维Gaussian模型中不同h下exact/近似NLL与2-Wasserstein距离。","small-h WKB correction追踪stochasticity改变likelihood和distribution error的方向。","Figure 3同时有解析reference与WKB近似，是检验Planck-like插值是否可计算的中心数值证据。",
[{"label":"Stochasticity interpolation","latex":r"dX_t=b_h(X_t,t)dt+\sqrt{h}\,g(t)d\bar W_t,\qquad 0\le h\le1","role":"interpolate probability-flow ODE and stochastic reverse SDE","symbols":{"h":"Planck-like stochasticity parameter","b_h":"marginal-preserving drift","g":"noise schedule"},"evidence":"paper.pdf pp. 2–5, interpolating generative process","interpretation":"The WKB expansion treats h as a small fluctuation parameter around deterministic paths."}],
["paper.pdf pp. 1–3, Figure 1: path-integral overview","paper.pdf pp. 3–6: reverse SDE and loss derivations","paper.pdf pp. 6–9, Figures 2–4: h interpolation and WKB tests","paper.pdf pp. 15–27, Figures 5–14: synthetic setup and local errors","source PDF SHA-256 319e47168831877e46e21443719cc7dddcc5876126b6150631882b6b52d2c2ab","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."])
]
def main()->int:
 OUT.mkdir(parents=True,exist_ok=True); ids=[]
 for item in CARDS:
  pid=str(item["arxiv_id"]); (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); ids.append(pid)
 print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__=="__main__": raise SystemExit(main())
