#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 038."""
from __future__ import annotations

import json
from pathlib import Path

from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

CARDS = [
    card(
        "doi-10.1103-physrevlett.123.058001", "arXiv v1 manuscript", "https://arxiv.org/pdf/1807.08858",
        "Correlated Rigidity Percolation and Colloidal Gels", "关联刚性渗流与胶体凝胶",
        "theory_numerics", "c3028ace11fb7a70", "Soft Matter",
        {"doi":"10.1103/PhysRevLett.123.058001","arxiv_id":"1807.08858","version":"arXiv v1 full text","title":"Correlated Rigidity Percolation and Colloidal Gels","authors":["Shang Zhang","Leyou Zhang","Mehdi Bouzid","D. Zeb Rocklin","Emanuela Del Gado","Xiaoming Mao"],"journal":"Physical Review Letters","volume":"123","issue":"5","article":"058001","published":"2019-07-30","abstract":"Correlated lattice occupation and attractive-particle molecular dynamics show that short-range structural correlations lower the rigidity-percolation volume fraction without changing the classical critical exponents.","comment":"ArXiv v1 full text cross-checked with version-of-record metadata; Crossref lists no correction or retraction relation"},
        [
            sec("作者信息","作者 Shang Zhang、Leyou Zhang、Mehdi Bouzid、D. Zeb Rocklin、Emanuela Del Gado、Xiaoming Mao；PRL 123, 058001 (2019)。全文 arXiv:1807.08858v1 共10页含补充材料；Crossref 未列更正或撤稿。"),
            sec("研究问题","经典 rigidity percolation 随机移除格点或键，预测二维三角格点约63%才刚化，但胶体凝胶在几个百分点即可承载应力。论文问：吸引诱导的空间关联能否把粒子组织成稀疏而贯通的承力骨架，从而系统性降低刚性阈值？"),
            sec("背景","几何连通不等于机械刚性；刚性需要能传递应力的 spanning rigid cluster，通常接近 isostatic coordination。经典 RP 忽略聚集过程产生的相关结构，而极端 Warren truss 说明一维稀疏结构在二维热力学极限仍可刚性。","本文把‘凝胶化是 RP’限定为给定二维模型中的刚性簇贯通；它没有测量真实凝胶的模量或时间依赖屈服。"),
            sec("模型与方法","correlated lattice model 在三角格点逐点占据，接受概率 p=(1−c)^(6−Nnn)，c 控制邻近关联；最近邻连接成弹簧网。attractive gel model 含10^4个二维单分散粒子，以短程 Lennard-Jones-like 势做周期边界 MD，并在距离≤1.03σ时连键。","两类网络均用 pebble-game algorithm 分解 rigid clusters；横纵双向贯通定义 RP。格点模型对不同 L 做 finite-size scaling；凝胶模型以 Pg=0.5 拟合每个 kBT/ε 下的转变体积分数。"),
            sec("核心结果与证据","关联增强使 P 和最大刚性簇质量 M 的曲线左移。小 c 时阈值移动满足 φl,c(0)−φl,c(c)=a c^(1/ζ)，ζ≈0.76、a≈0.19，而 ν=1.21、β=0.18 与经典 RP 一致，支持短程关联改变临界点但不改变 universality class。","强 c 若允许致密液滴会出现 reentrance；加入‘Nnn≥4不可占据’的动力学冻结修正后，阈值随 c 单调下降。Figure 4 的胶体模型相图同样显示吸引增强使低 φg 的贯通刚性更易出现，并在很强吸引处转入 diffusion-limited aggregation。","Figure 4 的两幅 φg=0.6 构型分别位于非刚与刚区，pebble-game cluster 与拟合边界一致。相图是二维模拟结果；与实验的一致性来自趋势和既有文献，不是本文直接实验拟合。"),
            sec("有效性与局限","格点占据规则和强关联修正是现象学构造；凝胶是二维、单分散、给定短程势与人为1.03σ连键。冷却率、键寿命、角约束、应变和三维结构都可能移动边界。","同一 critical exponent 的判断来自有限 L collapse；关联若变成长程可能不再是 irrelevant perturbation。Pg=0.5与三阶平滑曲线是操作性相界，不能替代机械模量或实验 gel point。"),
            sec("复现与资源","全文：https://arxiv.org/abs/1807.08858；期刊：https://doi.org/10.1103/PhysRevLett.123.058001。PDF SHA-256：74c0bd23509ea252df7836376a6785fdc48e66e0156a14ac37970e297d2b267b。全文未提供代码仓库。","复现需固定 L、c、占据顺序、强关联修正、样本数、pebble-game边界规则，以及 N=10^4、势参数、温控/冷却、1.03σ连键与Pg拟合。Evidence status: full-text verified lattice/MD study; no independent reproduction performed."),
            sec("阅读指南","先读 pp.1–2 的物理问题、Eq. (1) 与 Figure 1；p.3 看临界指数和阈值移位，p.4 Figures 3–4 对照两套相图。最后查 pp.5–10 的 MD、pebble game 与 finite-size details，保留二维与操作性相界限制。"),
        ],"figure-4-gel-phase-diagram.webp","Figure 4",4,"phase_diagram","吸引胶体模型的刚性概率相图和相界两侧的刚性簇分解。","降低 kBT/ε 即增强吸引，会在更低体积分数形成贯通刚性网络；过强吸引进入非平衡聚集区。","Figure 4把相界拟合与具体网络构型直接对应，是关联降低胶体刚性阈值的最完整数值证据。",
        [{"label":"Correlated occupation rule","latex":r"p=(1-c)^{6-N_{nn}}","role":"generate short-range structural correlations on a triangular lattice","symbols":{"c":"correlation strength","N_nn":"occupied nearest neighbors"},"evidence":"paper.pdf p. 2, Eq. (1)","interpretation":"The rule is phenomenological and is modified at strong correlation to mimic dynamical arrest."}],
        ["paper.pdf pp. 1–2, Figure 1 and Eq. (1): correlated lattice and attractive gel models","paper.pdf pp. 3–4, Eqs. (2)–(6) and Figures 2–4: scaling and phase boundaries","paper.pdf pp. 5–10: pebble game, MD protocol and finite-size scaling","source PDF SHA-256 74c0bd23509ea252df7836376a6785fdc48e66e0156a14ac37970e297d2b267b","Evidence status: full-text verified lattice/MD study; no independent reproduction performed."],
    ),
    card(
        "doi-10.1103-physrevlett.126.118003","arXiv v2 manuscript","https://arxiv.org/pdf/2009.07187","Hidden Order Beyond Hyperuniformity in Critical Absorbing States","临界吸收态中超越超均匀性的隐藏序","numerical","02f9ded942dc60bf","Statistical Physics",
        {"doi":"10.1103/PhysRevLett.126.118003","arxiv_id":"2009.07187","version":"arXiv v2 full text","title":"Hidden Order Beyond Hyperuniformity in Critical Absorbing States","authors":["Yuanjian Zheng","Anshul D. S. Parmar","Massimo Pica Ciamarra"],"journal":"Physical Review Letters","volume":"126","issue":"11","article":"118003","published":"2021-03-19","abstract":"Large conserved-lattice-gas and random-organization simulations reveal non-Gaussian many-body correlations extending beyond the shorter hyperuniform length near absorbing transitions.","comment":"ArXiv v2 full text cross-checked with version-of-record metadata; Crossref lists no correction or retraction relation"},
        [
            sec("作者信息","作者 Yuanjian Zheng、Anshul D. S. Parmar、Massimo Pica Ciamarra；PRL 126, 118003 (2021)。全文 arXiv:2009.07187v2 共10页；Crossref 未列更正或撤稿。"),
            sec("研究问题","hyperuniformity 通常只看局域密度方差或结构因子，等价于二点信息。论文问：临近 active–absorbing transition 时，局域密度分布 P(ρR) 的偏度、峰度及 coarse-grained density correlations 是否揭示更长的多体关联尺度？"),
            sec("背景","Poisson 点过程在大 R 下 σ²(R)∼R^−d并趋于 Gaussian；hyperuniform state 的方差以更快指数衰减。仅凭二阶矩无法判断中间尺度的非 Gaussian 结构，也可能把所有临界关联错误归给一个 ξh。","作者比较 conserved lattice gas (CLG) 和 random organization (RO)，两者都有守恒 active–absorbing transition，但微观更新分别是格点排斥迁移与重叠圆盘随机位移。"),
            sec("模型与方法","CLG 主要用 L=8192、约1.5×10^7粒子；RO 常用约8.192×10^6粒子，至少50个独立 runs。对方形窗口尺度 R 计算 P(ρR)、variance、skewness、excess kurtosis，并提取方差极小处 ξh。","在 R=ξh 上计算 coarse-grained density correlation CρR(r) 的指数衰减长度；另记录粒子最后从 active 变 passive 的 freezing time tf，分析 Ctf(r)，并用共享初态的100次 isoconfigurational averages 分离动力噪声。"),
            sec("核心结果与证据","两模型在吸收相有 σ²∼R^−2.45 的方差抑制，但 ξh∼Δρ^−νh 的 νh≈0.6，而非先前假定的约0.8。P(ρR=ξh) 明显 non-Gaussian，偏度/峰度在更大尺度才回到中央极限定理。","Figure 3 显示 coarse-grained density correlation length ξρR 与 freezing-time length ξtf 均以约Δρ^−0.8发散，快于 ξh；各密度的 Ctf 用 r/ξtf 而非 r/ξh collapse。这建立‘方差超均匀尺度’与‘多体动力关联尺度’的分离。","isoconfigurational averages 中最终低密度区域与早冻结区域相关，但 tf 与初态局域密度涨落不相关；作者据此把隐藏结构连接到达吸收态的协同动力学，而非简单初始密度不均。"),
            sec("有效性与局限","核心指数来自两个二维模型和有限密度窗；补充材料只称三维定性相似，不能宣称普适。ξρR 是对 coarse-grained observable 的二点函数，但其信息已编码窗口内多粒子，因此‘many-body’是操作性解释。","巨型系统仍受 finite-size effects；exponent collapse 与极值拟合有系统误差。与超冷液体、jammed solids 的分类是类比和研究建议，没有实测玻璃临界指数验证。"),
            sec("复现与资源","全文：https://arxiv.org/abs/2009.07187；期刊：https://doi.org/10.1103/PhysRevLett.126.118003。PDF SHA-256：192fdf273cabc968fa3cb112da5c87387e056e99e0d773d63a7bb6122db5f94f。全文未给代码仓库。","复现需固定 CLG/RO 更新顺序、δ=0.5、临界密度、L/N、窗口几何、binning、至少50 runs、ξh极值规则、指数拟合区间和100-run isoconfigurational ensemble。Evidence status: full-text verified large-scale simulation study; no independent reproduction performed."),
            sec("阅读指南","先读 pp.1–2 定义 P(ρR) 与两模型；pp.2–3 Figures 1–3 是双尺度结论。p.4 Figure 4 看 freezing-time 来源，再用 pp.6–10补充材料检查 exponent extraction、size effects 与三维限定。"),
        ],"figure-3-hidden-length-scales.webp","Figure 3",3,"comparison","超均匀长度、粗粒密度关联长度与冻结时间关联长度的临界发散和相关函数 collapse。","ξh 以约0.6指数发散，而隐藏密度/冻结动力关联以约0.8指数延伸到更长尺度。","Figure 3直接展示论文标题所称的 beyond-hyperuniformity：同一临界点存在两个不同发散尺度。",
        [{"label":"Two diverging lengths","latex":r"\xi_h\sim\Delta\rho^{-0.6},\qquad \xi_{\rho_R}\sim\xi_{t_f}\sim\Delta\rho^{-0.8}","role":"separate variance suppression from longer many-body dynamical correlations","symbols":{"xi_h":"hyperuniform length","xi_rhoR":"coarse-grained density correlation length","xi_tf":"freezing-time correlation length"},"evidence":"paper.pdf p. 3, Figure 3","interpretation":"The exponents are numerical estimates for the studied absorbing-state models."}],
        ["paper.pdf pp. 1–2, Figure 1: models, moments and hyperuniform scaling","paper.pdf p. 3, Figures 2–3: non-Gaussian distribution and two length scales","paper.pdf p. 4, Figure 4: isoconfigurational freezing-time evidence","source PDF SHA-256 192fdf273cabc968fa3cb112da5c87387e056e99e0d773d63a7bb6122db5f94f","Evidence status: full-text verified large-scale simulation study; no independent reproduction performed."],
    ),
    card(
        "doi-10.1103-physrevlett.127.238001","arXiv v1 manuscript","https://arxiv.org/pdf/2107.14106","Susceptibility of Orientationally Ordered Active Matter to Chirality Disorder","取向有序主动物质对手性无序的敏感性","theory_numerics","08747a6f761ee233","Active Matter",
        {"doi":"10.1103/PhysRevLett.127.238001","arxiv_id":"2107.14106","version":"arXiv v1 full text","title":"Susceptibility of Orientationally Ordered Active Matter to Chirality Disorder","authors":["Bruno Ventejou","Hugues Chaté","Raul Montagne","Xia-qing Shi"],"journal":"Physical Review Letters","volume":"127","issue":"23","article":"238001","published":"2021-11-30","abstract":"Particle simulations and Boltzmann-Ginzburg-Landau hydrodynamics show that homogeneous 2D polar and nematic order is destroyed by arbitrarily weak distributed chirality at infinite size, while traveling bands can remain robust.","comment":"ArXiv v1 full text cross-checked with version-of-record metadata; Crossref lists no correction or retraction relation"},
        [
            sec("作者信息","作者 Bruno Ventejou、Hugues Chaté、Raul Montagne、Xia-qing Shi；PRL 127, 238001 (2021)。全文 arXiv:2107.14106v1 共5页；Crossref 未列更正或撤稿。"),
            sec("研究问题","真实 active populations 的个体 intrinsic turning frequencies 不完全相同。论文问：零均值 Gaussian 或±ω0 bimodal chirality disorder 是否允许二维 polar flock/active nematic 保持长程序，以及 coexistence bands 是否与均匀液体同样脆弱？"),
            sec("背景","粒子以恒速运动并作 ferromagnetic α=1 或 nematic α=2 局域对齐，角动力学含个体ωi和旋转噪声 Dr。纯系统随噪声下降经历无序气体、band coexistence、均匀有序液体。","已有工作因系统较小而认为 finite disorder 可同步；本文把 finite-size threshold 与热力学极限严格区分。"),
            sec("模型与方法","连续时间粒子模型在周期 L×L 区域用 Euler Δt=0.1，ρ0=κ=v0=1；扫描 Dr、ω0、两种 alignment 和两种 frequency distributions，在 L=256 建相图并随 L 测有序液体消失阈值ω0*。","对 ferro+bimodal 情形从两套 Boltzmann equations 推导 coupled hydrodynamics，保留ρ±和一阶 Fourier modes p,m。对均匀有序解的6×6 Fourier-space linearization 搜索任意 q 的最大增长率及最大稳定系统尺度 L†。"),
            sec("核心结果与证据","有限 L 相图包含 polar/nematic liquids、Vicsek/nematic bands，并在强无序出现 vortices、rotating packets 与 active foam。Figure 3(a) 中均匀有序态可容忍的ω0*随 L 约按 L^−0.6衰减，四种组合都趋零。","hydrodynamic ordered solution 在整个存在域都有正增长模；最大稳定尺度 L†∼1/ω0，提供任意非零无序最终破坏均匀 polar order 的连续场机制。微观约0.6指数与1不同，作者归因于 fluctuations/nonlinear effects，未作定量重整化。","band phase 不同：其ω0*随 L 不消失，且 Figure 3(b) 展示 Vicsek bands 与 polar vortices 共存。因此结论不是‘所有取向序都立即消失’，而是均匀长程序脆弱、非均匀 coexistence structures 可承受有限无序。"),
            sec("有效性与局限","完整 hydrodynamic stability 只为 ferromagnetic+bimodal 推导；nematic 与 Gaussian 的热力学结论主要靠粒子 finite-size evidence。相图 L=256 且边界粗略，新 vortex/foam phases 的动力学被明确留待后续。","二维、dry、point-particle、单位作用半径和固定密度限制对实验外推；高维可能恢复同步。L†和ω0*指数差异表明线性理论只解释不稳定性存在，不精确预测微观 finite-size scaling。"),
            sec("复现与资源","全文：https://arxiv.org/abs/2107.14106；期刊：https://doi.org/10.1103/PhysRevLett.127.238001。PDF SHA-256：e5aea4ebd373f4a4fc2adcfc914358c96446bcbca96c1958b7cf06651d68fbda。全文未提供代码仓库。","复现需固定ω分布、Dr convention、L、Δt=0.1、初态/运行时间、order-threshold定义、相图分类，以及 Boltzmann collision kernel、closure 与全q稳定性搜索。Evidence status: full-text verified particle/hydrodynamic study; no independent reproduction performed."),
            sec("阅读指南","先读 pp.1–2 Eq. (1) 与 Figure 1；p.3 Figures 2–3 区分新相与有限尺寸阈值。pp.3–4 Eqs. (2)–(3) 和 Figure 4 给 hydrodynamic mechanism；最后保留 bands、高维和未研究新相的边界。"),
        ],"figure-3-finite-size-disorder.webp","Figure 3",3,"comparison","均匀 polar/nematic order 的可容忍手性无序随系统尺寸衰减，以及 band–vortex coexistence snapshot。","四种模型的ω0*都随 L 下降，而 traveling bands 可与 chiral vortices 共存。","Figure 3同时支撑热力学脆弱性与 band 例外，避免把结论误写成所有有序结构都被任意无序摧毁。",
        [{"label":"Chiral aligning particles","latex":r"\dot\theta_i=\omega_i+\kappa\langle\sin[\alpha(\theta_j-\theta_i)]\rangle+\sqrt{2D_r}\,\eta_i","role":"introduce population disorder through intrinsic turning frequencies","symbols":{"omega_i":"individual chirality","alpha":"1 polar or 2 nematic alignment","D_r":"rotational noise"},"evidence":"paper.pdf p. 1, Eq. (1b)","interpretation":"The distribution has zero mean but nonzero width omega0."}],
        ["paper.pdf pp. 1–2, Eq. (1) and Figures 1–2: particle model and phase inventory","paper.pdf p. 3, Figure 3: finite-size disorder threshold and band-vortex coexistence","paper.pdf pp. 3–4, Eqs. (2)–(3) and Figure 4: hydrodynamic instability","source PDF SHA-256 e5aea4ebd373f4a4fc2adcfc914358c96446bcbca96c1958b7cf06651d68fbda","Evidence status: full-text verified particle/hydrodynamic study; no independent reproduction performed."],
    ),
    card(
        "doi-10.1103-physrevlett.127.240603","arXiv v3 manuscript","https://arxiv.org/pdf/2101.11633","Statistical Physics through the Lens of Real-Space Mutual Information","实空间互信息视角下的统计物理","ai_empirical","a57e23586f7b3bdb","Information Theory",
        {"doi":"10.1103/PhysRevLett.127.240603","arxiv_id":"2101.11633","version":"arXiv v3 full text","title":"Statistical Physics through the Lens of Real-Space Mutual Information","authors":["Doruk Efe Gökmen","Zohar Ringel","Sebastian D. Huber","Maciej Koch-Janusz"],"journal":"Physical Review Letters","volume":"127","issue":"24","article":"240603","published":"2021-12-06","abstract":"A neural mutual-information estimator learns one-step coarse-graining filters that identify interpretable relevant lattice operators, order parameters, and emergent electric fields in an interacting dimer model.","comment":"ArXiv v3 full text cross-checked with version-of-record metadata; Crossref lists no correction or retraction relation"},
        [
            sec("作者信息","作者 Doruk Efe Gökmen、Zohar Ringel、Sebastian D. Huber、Maciej Koch-Janusz；PRL 127, 240603 (2021)。全文 arXiv:2101.11633v3 共16页；Crossref 未列更正或撤稿。"),
            sec("研究问题","实空间 RG 的粗粒化规则常凭经验，迭代会放大错误；通用机器学习又缺少场论可解释性。论文问：能否直接最大化局域 block 与远端 environment 的 mutual information，一步学习最相关 lattice operators、order parameters 与 scaling dimensions？"),
            sec("背景","RSMI principle 认为最优 coarse-graining H 保留 I(H:E)，buffer B 排除短程相关；在临界系统中最优压缩由 relevant operators 决定。难点是高维 mutual information 的估计和离散 coarse variable 的可微优化。","RSMI-NE 用神经网络互信息下界与卷积 filter Λ共同训练；其物理可解释性来自优化目标，而不是网络结构本身。"),
            sec("模型与方法","可见区V经 h=τ(Λ·v)压缩为二分量 binary H，critic fΘ估计 IΛ(H:E)，Λ与Θ用 stochastic gradient descent 联训。buffer thickness LB 充当直接选择长程尺度的旋钮，无需迭代 RG map。","benchmark 是 square-lattice interacting dimer model，低温有四重 columnar order，TBKT=0.65(1)以上为 algebraic critical phase；continuum 对应 sine-Gordon height field，V cos4φ 与 stiffness g(T) 控制相关。"),
            sec("核心结果与证据","Figure 2 中低温最优 RSMI 为 log4，准确编码四种 columnar states；IΛ(T) 的非解析性定位 BKT transition，临界相中它随 buffer algebraic decay。独立训练得到 columnar、plaquette、staggered 三类 pristine filters。","columnar filter 在低温成为已知 dimer-symmetry-breaking order parameter，过 TBKT 后消失；高温 staggered filters 对应 emergent electric field ∇φ。滤波器 ensemble overlap 还显示 plaquette correlations 与 symmetry restoration。","以 learned plaquette network 的 correlator 拟合 T→∞ scaling dimension 得1.00037，对应场论预测1.0。代码公开，但论文只在已知 dimer field theory 上验证；‘automated theory building’仍是前景而非完整自动生成新理论。"),
            sec("有效性与局限","互信息神经下界、有限样本和随机优化可能漏掉等价/近简并 filters；作者通过多次训练分析 ensemble，但没有全局最优证明。binary H维度预先指定，虽称可系统选择，主结果未做广泛容量扫描。","非平衡 formal understanding 尚缺；文中非平衡例证来自 companion work。BKT 有限尺寸、buffer/block大小、Monte Carlo采样质量和已知 height mapping 都影响定量解释。"),
            sec("复现与资源","全文：https://arxiv.org/abs/2101.11633；代码：https://github.com/RSMI-NE/RSMI-NE；期刊：https://doi.org/10.1103/PhysRevLett.127.240603。PDF SHA-256：fe9bc37973d5722289e9d749dae7921fe812eb452ca0e94a297df49930462891。","复现需固定 dimer Monte Carlo、T/L、V/B/E geometry、LB、two-bit embedding、critic/coarse networks、batch/optimizer/seeds、独立run数、filter alignment与correlator fit range。Evidence status: full-text verified ML/statistical-physics study; no independent reproduction performed."),
            sec("阅读指南","先读 pp.1–2 Figure 1 与 Eqs. (1)–(2)；pp.3–5 Figure 2 是完整物理案例。随后按需查 pp.6–16 的 estimator architecture、buffer/size sensitivity 与 scaling-dimension extraction，区分已验证 dimer 结果和自动理论前景。"),
        ],"figure-2-rsmi-dimer.webp","Figure 2",3,"comparison","interacting dimer model 的 RG 结构、RSMI、学习到的 filters、filter overlaps 与 order parameters。","RSMI-NE 随温度自动切换 columnar/plaquette/staggered operators，并恢复低温序参量和高温 emergent electric field。","Figure 2把神经优化输出与已知场论算子逐项对齐，是可解释性主证据。",
        [{"label":"RSMI objective","latex":r"I_\Lambda(H:E)=\sum_{h,e}p_\Lambda(h,e)\log\frac{p_\Lambda(h,e)}{p_\Lambda(h)p(e)}","role":"select coarse variables retaining maximal long-range information","symbols":{"H":"coarse-grained block","E":"distant environment","Lambda":"learned coarse-graining filter"},"evidence":"paper.pdf p. 2, Eq. (1)","interpretation":"The buffer removes short-range information, while neural lower bounds make the objective tractable."}],
        ["paper.pdf pp. 1–2, Figure 1 and Eqs. (1)–(2): RSMI-NE principle and architecture","paper.pdf pp. 3–5, Figure 2 and Eqs. (3)–(5): dimer operators and phase structure","paper.pdf pp. 6–13: estimator, buffer, finite-size and operator extraction details","source PDF SHA-256 fe9bc37973d5722289e9d749dae7921fe812eb452ca0e94a297df49930462891","Evidence status: full-text verified ML/statistical-physics study; no independent reproduction performed."],
    ),
    card(
        "doi-10.1103-physrevlett.129.258001","arXiv v1 manuscript","https://arxiv.org/pdf/2202.12854","Data-Driven Discovery of Active Nematic Hydrodynamics","主动向列流体力学的数据驱动发现","ai_empirical","743c890458f9494f","Active Matter",
        {"doi":"10.1103/PhysRevLett.129.258001","arxiv_id":"2202.12854","version":"arXiv v1 full text","title":"Data-Driven Discovery of Active Nematic Hydrodynamics","authors":["Chaitanya Joshi","Sattvic Ray","Linnea M. Lemma","Minu Varghese","Graham Sharp","Zvonimir Dogic","Aparna Baskaran","Michael F. Hagan"],"journal":"Physical Review Letters","volume":"129","issue":"25","article":"258001","published":"2022-12-16","abstract":"Noise-robust sparse PDE regression on simulations and microtubule-kinesin experiments identifies a minimal flow-coupled Q-tensor equation and Stokes active-stress equation, and maps scaled activity to ATP concentration.","comment":"ArXiv v1 full text cross-checked with version-of-record metadata; Crossref lists no correction or retraction relation"},
        [
            sec("作者信息","作者 Chaitanya Joshi 等8人；PRL 129, 258001 (2022)。全文 arXiv:2202.12854v1 共11页；Crossref 未列更正或撤稿。"),
            sec("研究问题","active-nematic continuum models 含许多 symmetry-allowed PDE terms，实验系数通常间接拟合且模型不唯一。论文问：能否从显微图像导出的 Q tensor 与 PIV velocity 直接稀疏识别最简方程，并把 activity α/η 定量映射到 ATP？"),
            sec("背景","系统是二维 microtubule–kinesin active nematic，假设 constant density、incompressible flow。目标字段为 traceless Qxx,Qxy 与 ux,uy；pressure 不可观测，需通过 stream-function/weak formulation 消去。","候选 Q-equation library 含低阶场与导数组合，最多246项；flow equation 把∂tu放右侧，让数据决定 pure Stokes、unsteady Stokes或更完整 inertia。"),
            sec("模型与方法","对 Q equation 用局域5×5×5左右 integral averaging，对高阶 flow derivatives 用 weak formulation 把导数移到精确 test function。Ridge regression 后逐项删去最不重要项，以 log(1−R²) optimality curve 的最大曲率选稀疏度。","先在 Stokes-with-friction 与 unsteady-Stokes simulations 上加5% synthetic noise，恢复已知10项/2项方程与参数；再分析25、50、100、500 μM等 ATP 的 fluorescence/PolScope orientation 和 PIV velocity data。"),
            sec("核心结果与证据","实验最优 Q 模型主要是 convection、co-rotation 与 flow alignment，系数约1并恢复 Galilean structure；bulk Landau与elastic ∇²Q terms 不进入最优模型，表明该数据范围内 orientation dynamics 由 flow coupling 主导。","Figure 2 的 flow optimality curves 几乎由α/η ∇·Q一项解释；inertial 与 substrate-friction terms 较晚才出现，支持 unscreened Stokes limit。拟合 α/η 随 ATP 增大，并与 velocity autocorrelation inverse time 1/τ 紧密一致。","用最优 Eq. (5) 模拟后，+1/2 defect inverse lifetime 无prefactor地对齐实验；defect density 需一个未知常数长度缩放后吻合。后者不是无参数空间尺度验证，作者也承认 Q equation 无法给 dimensional length/time coefficients。"),
            sec("有效性与局限","term absence 只表示在给定噪声、分辨率、library 与实验状态下未被选择，不证明 free-energy gradients 普遍为零。constant density、2D、incompressibility、coarse-graining 和PIV误差限制外推。","稀疏度取 optimality curve 曲率，弱形式 window 对结果有影响；flow library 是人工 symmetry-informed 候选集。defect density 比较依赖常数缩放，且没有独立 held-out laboratory replicate 的报告。"),
            sec("复现与资源","全文：https://arxiv.org/abs/2202.12854；代码示例：https://github.com/joshichaitanya3/actnempy；期刊：https://doi.org/10.1103/PhysRevLett.129.258001。PDF SHA-256：7d116aed6abcab8e3cf11531b92094f7c52e23312801a4e84b2d684b257b8cac。","复现需固定 raw microscopy/PIV preprocessing、Q extraction、candidate library、sampling m、integral/weak windows、Ridge penalty、elimination normalization、optimality curvature和defect tracking。Evidence status: full-text verified simulation/experimental ML study; no independent reproduction performed."),
            sec("阅读指南","先读 pp.1–2 Eqs. (1)–(3) 锁定字段与候选模型；p.3 Figure 2 看稀疏发现与ATP映射，p.4 Figure 3看缺陷验证。再查 pp.5–11 的 library、window/noise benchmarks 和实验采集，避免把未选择项写成普适缺失。"),
        ],"figure-2-model-discovery.webp","Figure 2",3,"data_plot","不同 ATP 条件下的稀疏最优曲线、flow-coupling coefficients 与 activity-timescale 映射。","最简 Q 动力学由流耦合组成，flow 主要由最低阶 active stress 驱动；α/η与1/τ同步变化。","Figure 2是从实验数据到具体 PDE terms 和可解释 activity parameter 的核心证据。",
        [{"label":"Discovered minimal model","latex":r"\partial_tQ\sim-u\cdot\nabla Q-(\Omega Q-Q\Omega)+E-2(Q:\nabla u)Q,\quad \eta\nabla^2u\sim\alpha\nabla\cdot Q+\nabla P","role":"summarize the sparse experimental Q and flow equations","symbols":{"Q":"nematic tensor","u":"flow velocity","alpha/eta":"scaled activity"},"evidence":"paper.pdf p. 3, Eq. (5)","interpretation":"The model is optimal within the chosen library and experimental resolution, not a universal exact equation."}],
        ["paper.pdf pp. 1–2, Eqs. (1)–(4) and Figure 1: libraries and noise-robust regression","paper.pdf pp. 3–4, Figures 2–3 and Eq. (5): experimental model and defect validation","paper.pdf pp. 5–10: continuum terms, preprocessing, window/noise benchmarks and microscopy","source PDF SHA-256 7d116aed6abcab8e3cf11531b92094f7c52e23312801a4e84b2d684b257b8cac","Evidence status: full-text verified simulation/experimental ML study; no independent reproduction performed."],
    ),
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    installed=[]
    for item in CARDS:
        pid=str(item["arxiv_id"])
        (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
        installed.append(pid)
    print(json.dumps({"installed":installed},ensure_ascii=False))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
