#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 046."""
from __future__ import annotations

import json
from pathlib import Path

from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"


CARDS = [
card("record-18f39c24e7e7af25", "NeurIPS 2025 proceedings PDF", "https://papers.neurips.cc/paper_files/paper/2025/file/2cf63608d264a3c65e68e3cff860c152-Paper-Conference.pdf",
     "Understanding Softmax Attention Layers: Exact Mean-Field Analysis on a Toy Problem",
     "理解Softmax注意力层：玩具问题上的精确平均场分析", "theory_numerics", "18f39c24e7e7af25", "Transformer Theory",
     {"doi":None,"arxiv_id":None,"version":"NeurIPS 2025 proceedings full text","title":"Understanding Softmax Attention Layers: Exact Mean-Field Analysis on a Toy Problem","authors":["Elvis Dohmatob"],"journal":"Advances in Neural Information Processing Systems","volume":"38","pages":None,"published":"2025","abstract":"Random-energy-model calculations reduce softmax attention on single-location regression to overlap variables and characterize its population risk and gradient-flow attractors.","comment":"No arXiv identifier or DOI was found in the verified proceedings PDF"},
     [sec("作者信息", "作者 Elvis Dohmatob（Concordia University、Mila、Meta）；NeurIPS 2025。核验会议正式PDF全文32页。PDF未列arXiv编号或DOI，因此本卡保留内部record标识，并把NeurIPS proceedings PDF作为可逐页定位的权威全文。"),
      sec("研究问题", "single-location regression给出L个token，其中只有隐藏位置ℓ*的embedding带有沿u*的信号，标签又由该token在v*方向的投影经link函数σ产生。论文问：使用真实softmax而非可分离pointwise attention时，能否精确写出population risk，并说明Riemannian gradient flow是否会学到定位方向u*和读出方向v*？"),
      sec("背景", "学生模型用softmax权重pℓ∝exp(λxℓ·u)聚合xℓ·v。难点在于分母把所有token耦合；当dimension d、sequence length L以指数尺度共同增大时，softmax归一化与random energy model的free energy具有相同结构。作者因此把优化压缩为u、v与oracle方向之间的overlaps。", "这是刻意简化的单层、单头、无QKV矩阵、无residual/MLP/layer norm的population模型；它解释一个可控机制，不是对完整LLM训练动力学的定理。"),
      sec("模型与方法", "作者在球面约束u,v∈S^{d−1}上推导高维极限risk R(u,v)，并按inverse temperature与sequence complexity划分softmax选择正确token的相。对identity、square与ReLU等link，risk只依赖四个overlap，随后推导其Riemannian gradient-flow ODE、固定点和稳定性。", "Proposition 2给出oracle在指定条件下达到Bayes risk；后续分类定理说明在奇/偶或一般link条件下，哪些初始化可收敛到唯一稳定oracle attractor。Figure 2以d=100、L=20、1000样本的有限维gradient descent作sanity check。"),
      sec("核心结果与证据", "解析risk显示attention的token-selection与label prediction分别由u和v的oracle alignment控制；当inverse temperature越过random-energy阈值且link满足非退化条件时，oracle模型在该函数族中Bayes-optimal。这里的‘exact’指所定义高维population limit，不含finite-sample generalization error。", "Figure 2中identity与square link的两个overlap趋近1、population risk趋近不可约噪声；ReLU曲线也朝oracle方向移动，但有限步长下有明显振荡。黑色理论曲线与彩色有限样本实验整体吻合，支持overlap ODE而非证明所有finite-d runs必然无失败。", "论文强化了此前pointwise attention结果：若link为odd或even，可在更广初始化下得到全局收敛；一般link仍需落在特定invariant manifold。结果依赖population gradient flow和球面参数化，不能直接外推到Adam、empirical risk或多头深层网络。"),
      sec("有效性与局限", "主要结论采用d→∞、L随d指数增长、Gaussian token/noise、单个隐藏位置以及已知数据生成结构。有限样本只作一幅数值示意，没有系统扫描seeds、dimension、learning rate或model misspecification。", "作者明确把finite-sample empirical-risk analysis和multi-locator regression列为未来工作；后者才更接近sparse parity与组合检索。理论也未处理learned queries/keys、causal masking、multi-head coupling、normalization或训练数据中的语义结构。"),
      sec("复现与资源", "全文：https://papers.neurips.cc/paper_files/paper/2025/file/2cf63608d264a3c65e68e3cff860c152-Paper-Conference.pdf。PDF SHA-256：4bb988a6d2f4d857efdce6b891bcc83acaa9ca45ef92f94a083cb56704514d42。正文未提供独立代码仓库链接。", "复现Figure 2需固定d=100、L=20、β=1、γ=1/√2、label-noise ε=0.1、1000训练样本、10000风险评估样本、步长与球面更新规则。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 的single-location任务和softmax模型；pp.4–6看random-energy risk及Bayes phase transition；pp.7–9读gradient-flow分类与Figure 2；pp.19–31核对分类定理证明和technical lemmas。")],
     "figure-2-mean-field-dynamics.webp","Figure 2",4,"comparison","三种link函数下oracle alignment与population risk随gradient iterations的变化。","理论overlap动力学与有限维实验总体一致，并在相应条件下朝oracle attractor收敛。","Figure 2把解析risk、优化动力学和finite-dimensional sanity check连接在同一证据中。",
     [{"label":"Softmax attention toy model","latex":r"g(X;u,v)=\sum_{\ell=1}^{L}p_\ell x_\ell^\top v,\qquad p_\ell=\frac{e^{\lambda x_\ell^\top u}}{\sum_j e^{\lambda x_j^\top u}}","role":"select the signal-bearing token and read out its label direction","symbols":{"u":"learned locator direction","v":"learned readout direction","lambda":"inverse temperature"},"evidence":"paper.pdf pp. 2–3, model definition","interpretation":"The exact reduction applies to the paper's high-dimensional single-location population model."}],
     ["paper.pdf pp. 1–3: task and softmax attention definition","paper.pdf pp. 4–6: exact population risk and Bayes-optimal phase","paper.pdf pp. 7–9, Figure 2: overlap dynamics and numerical check","paper.pdf pp. 19–31: classification proofs and auxiliary lemmas","source PDF SHA-256 4bb988a6d2f4d857efdce6b891bcc83acaa9ca45ef92f94a083cb56704514d42","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-1ae2eb274403f4be", "Engineering open-access article", "https://doi.org/10.1016/j.eng.2022.02.007",
     "Data-Driven Discovery of Stochastic Differential Equations", "随机微分方程的数据驱动发现",
     "ai_empirical", "1ae2eb274403f4be", "Active Matter",
     {"doi":"10.1016/j.eng.2022.02.007","arxiv_id":None,"version":"Engineering 17 (2022) publisher full text","title":"Data-Driven Discovery of Stochastic Differential Equations","authors":["Yasen Wang","Huazhen Fang","Junyang Jin","Guijun Ma","Xin He","Xing Dai","Zuogong Yue","Cheng Cheng","Hai-Tao Zhang","Donglin Pu","Dongrui Wu","Ye Yuan","Jorge Gonçalves","Jürgen Kurths","Han Ding"],"journal":"Engineering","volume":"17","pages":"244–252","published":"2022","abstract":"BISDE uses sparse Bayesian learning to identify drift and diffusion functions from limited stochastic time-series data.","comment":"Publisher PDF is open access under CC BY-NC-ND"},
     [sec("作者信息", "作者 Yasen Wang、Huazhen Fang、Junyang Jin、Guijun Ma、Xin He、Xing Dai、Zuogong Yue、Cheng Cheng、Hai-Tao Zhang、Donglin Pu、Dongrui Wu、Ye Yuan、Jorge Gonçalves、Jürgen Kurths、Han Ding；Engineering 17, 244–252 (2022)，DOI:10.1016/j.eng.2022.02.007。核验publisher PDF全文9页。"),
      sec("研究问题", "给定受随机扰动系统的一条或少量time series，如何同时恢复SDE的drift f(x)和state-dependent diffusion G(x)，并输出可解释的稀疏公式？直接条件矩估计需要大量重复样本，数值微分又会放大噪声；论文目标是在数据有限时仍从候选函数库中筛出物理上必要的项。"),
      sec("背景", "Itô SDE离散后，conditional increment mean近似drift·Δt，increment covariance近似GGᵀ·Δt。作者先把状态空间binning，用每个bin内样本的经验矩构造两个回归问题，再以sparse Bayesian learning自动收缩无关basis weights。", "目录把本条归在Active Matter，但论文本身是通用SDE system identification，案例覆盖Brownian/Langevin、机械轴承、油价、股票和风速；本卡不把它误述为专门的活性物质模型。"),
      sec("模型与方法", "BISDE首先从短时间increment估计drift输出向量，对candidate library做SBL回归；识别drift后，从残差平方/交叉乘积构造diffusion回归。ARD型weight precisions通过evidence maximization更新，使posterior mean给系数、posterior covariance表征参数不确定性。", "验证包括generalized Wiener与Langevin等synthetic SDE，可用真值和Fokker–Planck stationary density检查；现实数据包括三类bearing condition、Facebook stock、crude oil与Wellington wind speed，并与SDE_SINDy在减少样本量时比较。"),
      sec("核心结果与证据", "Figure 1的Langevin示例展示两阶段pipeline：先识别dv中的−3v drift，再利用drift残差识别常数diffusion约3。该图是算法流程和一个合成真值例，不是对所有未知SDE的一般成功率。", "bearing实验在不同horsepower和normal/inner-race/ball fault条件下得到可区分的随机模型；Figure 3汇总三类simulation与三类real-world应用。论文报告BISDE在有限数据下比所比较SDE_SINDy更稳定，但比较范围、library与预处理均由本文设定。", "stock/oil/wind案例给出parsimonious equations及distribution/prediction解释；这些是exploratory identification，不能据此作金融收益、因果机制或安全工程诊断保证。"),
      sec("有效性与局限", "方法假设高频离散下Euler–Maruyama近似有效、同一bin内drift/diffusion近似常量、候选library含真实项且模型足够稀疏。bin宽、Δt、measurement noise和rarely visited states会共同产生偏差。", "现实案例没有可观测的ground-truth SDE，拟合优度只能说明所选统计量相容；非平稳regime、jump processes、hidden variables、colored noise或高维state会破坏基本设定。SBL posterior uncertainty也不自动包含library misspecification。"),
      sec("复现与资源", "全文：https://doi.org/10.1016/j.eng.2022.02.007；代码与数据：https://github.com/HAIRLAB/BISDE。PDF SHA-256：2243851a963b36993b0efafc2fbe057b844d420960986b1a1527e755f4b08628。", "复现需固定sampling interval、bin number、basis library、SBL convergence threshold、drift-first residual construction、train/test window和各real dataset的单位/normalization。Evidence status: full-text verified analytical/empirical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–2问题与SDE离散化；pp.2–4看Theorem 1和BISDE两阶段回归；p.5 Figure 1理解流程，pp.5–8看bearing、synthetic与经济/风速案例；p.9核对结论、数据和代码链接。")],
     "figure-1-bisde-pipeline.webp","Figure 1",5,"schematic","Langevin数据生成、drift sparse regression和diffusion sparse regression的两阶段流程。","BISDE把条件increment moments转换为两个依次求解的稀疏Bayesian回归问题。","Figure 1最直接解释算法为什么必须先识别drift再利用残差识别diffusion。",
     [{"label":"Short-time conditional moments","latex":r"\mathbb E[\Delta x\mid x]\simeq f(x)\Delta t,\qquad \mathbb E[(\Delta x-f\Delta t)(\Delta x-f\Delta t)^\top\mid x]\simeq G(x)G(x)^\top\Delta t","role":"turn an SDE identification problem into drift and diffusion regressions","symbols":{"f":"drift","G":"diffusion amplitude","Delta_t":"sampling interval"},"evidence":"paper.pdf pp. 2–4, BISDE derivation","interpretation":"The approximation requires sufficiently short sampling intervals and adequate samples per state bin."}],
     ["paper.pdf pp. 1–2: problem statement and SDE setup","paper.pdf pp. 2–4: sparse Bayesian derivation and Theorem 1","paper.pdf p. 5, Figure 1: Langevin pipeline","paper.pdf pp. 5–8, Figures 2–5: simulated and real-data studies","source PDF SHA-256 2243851a963b36993b0efafc2fbe057b844d420960986b1a1527e755f4b08628","Evidence status: full-text verified analytical/empirical study; no independent reproduction performed."]),

card("record-1c62d958272af773", "arXiv v3 manuscript", "https://arxiv.org/pdf/2007.02848",
     "Weak SINDy for Partial Differential Equations", "用于偏微分方程的弱形式SINDy",
     "theory_numerics", "1c62d958272af773", "Active Matter",
     {"doi":"10.1016/j.jcp.2021.110525","arxiv_id":"2007.02848","version":"arXiv v3 full text","title":"Weak SINDy for Partial Differential Equations","authors":["Daniel A. Messenger","David M. Bortz"],"journal":"Journal of Computational Physics","volume":"443","pages":"110525","published":"2021","abstract":"A convolutional weak-form sparse regression discovers PDE terms without pointwise numerical derivatives and remains robust at high measurement noise.","comment":"ArXiv v3 accepted manuscript cross-checked with journal metadata"},
     [sec("作者信息", "作者 Daniel A. Messenger、David M. Bortz；Journal of Computational Physics 443, 110525 (2021)，DOI:10.1016/j.jcp.2021.110525。核验 arXiv:2007.02848v3 全文33页及公开Matlab实现。"),
      sec("研究问题", "从离散且含噪的spatiotemporal field恢复控制PDE时，经典SINDy需要pointwise时间/空间导数，噪声经微分严重放大。论文问：能否把PDE乘compactly supported test functions并分部积分，把导数移到光滑test function上，同时保持稀疏library选择、高精度和近线性计算成本？"),
      sec("背景", "对候选项D^αf_j(u)，弱形式在局部space-time boxes上积分并通过integration by parts变成数据u与已知test-function derivatives的convolution。这样不需先denoise或逐点估计u_t、u_xx；多个box产生矩阵G与右端b，再用STLS寻找稀疏系数。", "目录分类为Active Matter，但基准是Burgers、KdV、Kuramoto–Sivashinsky、nonlinear Schrödinger、sine-Gordon、reaction–diffusion和Navier–Stokes；算法本身不依赖活性物质专用结构。"),
      sec("模型与方法", "WSINDy-PDE利用可分离polynomial test functions与FFT计算convolutions，最坏复杂度为O(N^{D+1}logN)，即每data point约O(logN)。作者用Fourier spectra选support和smoothness，使test function在目标frequency范围内抑制noise。", "scale normalization缓解library columns量纲差异；modified STLS在一列候选threshold上最小化data-fit加sparsity penalty，学习λ而非手设。200次独立Gaussian-noise realizations用于每个noise level的average TPR和coefficient error。"),
      sec("核心结果与证据", "noise-free synthetic data中，识别系数误差可低于数值simulation tolerance，说明weak convolution没有引入主导误差；但这是已知library、规则grid和合成求解器下的结果，不等于实验PDE的机器精度恢复。", "Figure 4汇总七个PDE的200次noise trials：Burgers、KdV、KS和sine-Gordon在σ_NR=1附近仍保持约0.95以上平均TPR；NLS在约0.5之前较稳，reaction–diffusion和Navier–Stokes更早下降。右图显示learned threshold随noise总体上升且不同方程差异明显。", "正文还报告FFT实现随数据规模接近理论复杂度，并通过test-function spectrum解释robustness。成功依赖candidate library包含真项；TPR只衡量support recovery，不能替代coefficient accuracy、forecast stability或模型外推。"),
      sec("有效性与局限", "所有主测试来自数值生成、已知PDE和加性独立Gaussian measurement noise；现实采样常有correlated noise、missing data、irregular grids和boundary artifacts。弱积分会牺牲局部resolution，并依赖support scale与test-function family。", "高维library的collinearity、unmodeled forcing和近似closure可能产生不可辨识项；scale invariance改善condition但不解决结构等价。Navier–Stokes和reaction–diffusion的高噪TPR下降表明robustness并非跨系统统一。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2007.02848；代码：https://github.com/MathBioCU/WSINDy_PDE；期刊：https://doi.org/10.1016/j.jcp.2021.110525。PDF SHA-256：2b86d8de718f797a8951cecb38f569f3bf9970dd8c075538d512680fdfc1c416。", "复现需固定PDE solver/grid、noise normalization σ_NR、candidate library、test-function order/support、query points、FFT padding、STLS threshold grid和200 seeds。Evidence status: full-text verified numerical/methodological study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4为何使用weak form；pp.5–10看convolution、FFT与test-function selection；pp.11–14看threshold learning和scale normalization；pp.16–21读七PDE结果，尤其p.19 Figure 4；附录核对数据生成与parameters。")],
     "figure-4-noise-robustness.webp","Figure 4",19,"comparison","七类PDE在不同相对噪声下的平均term-recovery TPR与学习到的STLS threshold。","weak formulation对若干PDE可承受接近signal幅度的噪声，但RD与Navier–Stokes更早退化。","Figure 4用200次noise realizations呈现方法的鲁棒范围和清晰失败边界。",
     [{"label":"Convolutional weak form","latex":r"\int_\Omega \phi\,D^{\alpha^0}u\,dxdt=\sum_j w_j(-1)^{|\alpha^j|}\int_\Omega D^{\alpha^j}\phi\,f_j(u)\,dxdt","role":"move derivatives from noisy data onto smooth test functions","symbols":{"phi":"compactly supported test function","f_j":"candidate nonlinear term","w_j":"sparse PDE coefficient"},"evidence":"paper.pdf pp. 5–8, weak discretization","interpretation":"Recovery still depends on library identifiability, support choice and boundary handling."}],
     ["paper.pdf pp. 1–4: derivative-noise problem and weak formulation","paper.pdf pp. 5–10: convolutional discretization and FFT","paper.pdf pp. 11–14: learned threshold and scale invariance","paper.pdf pp. 16–21, especially Figure 4: seven-PDE noise tests","source PDF SHA-256 2b86d8de718f797a8951cecb38f569f3bf9970dd8c075538d512680fdfc1c416","Evidence status: full-text verified numerical/methodological study; no independent reproduction performed."]),

card("record-2d6699167b3ea0b5", "arXiv v3 manuscript", "https://arxiv.org/pdf/2403.13117",
     "Optimal Flow Matching: Learning Straight Trajectories in Just One Step", "最优流匹配：一步学习直线轨迹",
     "theory_numerics", "2d6699167b3ea0b5", "Flow Matching",
     {"doi":None,"arxiv_id":"2403.13117","version":"arXiv v3 full text / NeurIPS 2024","title":"Optimal Flow Matching: Learning Straight Trajectories in Just One Step","authors":["Nikita Kornilov","Petr Mokrov","Alexander Gasnikov","Alexander Korotin"],"journal":"Advances in Neural Information Processing Systems","volume":"37","pages":None,"published":"2024","abstract":"Convex-potential vector fields make one flow-matching optimization recover the quadratic optimal-transport displacement independently of the initial coupling.","comment":"ArXiv v3 is the verified NeurIPS 2024 manuscript"},
     [sec("作者信息", "作者 Nikita Kornilov、Petr Mokrov、Alexander Gasnikov、Alexander Korotin；NeurIPS 2024。核验 arXiv:2403.13117v3 全文26页与公开代码。PDF正文未给DOI，本卡不推测会议DOI。"),
      sec("研究问题", "普通Flow Matching沿任意coupling的linear interpolants训练，所得marginal velocity可能弯曲，需要许多ODE function evaluations；Rectified Flow要反复reflow，minibatch OT又有bias。论文问：能否只做一次FM objective，就得到quadratic optimal transport的直线displacement interpolation，且结果不依赖初始transport plan？"),
      sec("背景", "Brenier定理说明绝对连续source到target的quadratic OT map是convex potential梯度。OFM不直接拟合任意time-dependent vector field，而令flow map由strongly convex Ψ_t的梯度参数化；其Eulerian velocity通过inverse map和Hessian关系计算。", "‘one step’指一次flow-matching训练阶段，而不是一个gradient update，也不表示训练零成本。sampling时直线OT map可避免多步ODE integration，但训练内部仍需为每个sample解convex inverse subproblem。"),
      sec("模型与方法", "时间势Ψ_t由端点convex potential Ψ与quadratic term插值得到，使ϕ_t=∇Ψ_t产生直线轨迹。Theorem 1证明，对任意初始coupling π，OFM loss与dynamic OT kinetic energy之差为常数，因此global minimizer恢复唯一quadratic OT flow。", "实现用Input Convex Neural Network表示Ψ；LBFGS近似求ϕ_t^{-1}，Envelope Theorem给parameter gradient。实验覆盖2D toy distributions、维度2–128的Wasserstein-2 benchmark、unpaired image translation和FFHQ latent translation，并与FM、RF、c-RF、OT-CFM及neural OT baselines比较。"),
      sec("核心结果与证据", "Figure 6从Gaussian到eight Gaussians，用independent、minibatch和antiminibatch三种初始plans训练；三者都得到视觉上相近的直线transport，而输入couplings明显不同，直接示范Theorem 1的plan independence。它是2D可视证据，不给finite-sample optimization的一致性保证。", "高维benchmark的Table 1报告OFM在所测维度与baselines间取得有竞争力的L2-UVP，同时可直接用终点map采样。image experiments表明单次训练可得到合理翻译和FID，但论文checklist明确说明昂贵实验没有多次运行统计，因此小差值不应当作显著性结论。", "Appendix runtime显示OFM iteration因inverse convex optimization更昂贵；amortized inverse可缩短训练，但又引入额外MLP误差。推理轨迹直不等于训练总wall-clock更快。"),
      sec("有效性与局限", "定理要求quadratic cost、绝对连续分布、global minimization和足够表达的convex potential。实际ICNN可能欠表达，optimizer只到局部/近似解；高维inverse solve与Hessian operations会成为瓶颈。", "作者列出三项限制：flow-map inversion昂贵、ICNN可能弱于普通网络、gradient需要Hessian inverse。实验缺少多seed variance，图像translation还继承pretrained ALAE latent space与数据偏差；结论不覆盖conditional generation或非quadratic transport costs。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2403.13117；代码：https://github.com/Jhomanik/Optimal-Flow-Matching。PDF SHA-256：6603e34cf45e490259addb32b297ab4315b53e9fe1f36705d481e45e4856ab7e。", "复现需固定source/target samples、initial plan、ICNN depth/convexity constraints、LBFGS tolerance、Hessian solve、training iterations、benchmark reference OT与NFE/FID protocol。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4的FM、dynamic OT与问题动机；pp.5–8看convex flow parameterization、loss和Theorem 1；pp.9–12读Figure 6及benchmarks；pp.23–24看三项限制与amortization，附录检查runtime和hyperparameters。")],
     "figure-6-ofm-trajectories.webp","Figure 6",10,"comparison","Gaussian到eight-Gaussians任务及三种不同初始coupling训练出的OFM轨迹。","尽管初始plan不同，拟合出的OFM均接近同一quadratic-OT直线位移。","Figure 6直接可视化OFM核心的coupling independence与straightness主张。",
     [{"label":"Convex-potential flow map","latex":r"\phi_t(x)=\nabla\Psi_t(x),\qquad \Psi_t(x)=(1-t)\frac{\|x\|^2}{2}+t\Psi(x)","role":"parameterize straight displacement interpolations by a convex endpoint potential","symbols":{"Psi":"learned convex Brenier potential","phi_t":"time-t flow map","t":"interpolation time"},"evidence":"paper.pdf pp. 5–7, OFM parameterization","interpretation":"Exact OT recovery is a population/global-minimum result; practical ICNN and inversion errors remain."}],
     ["paper.pdf pp. 1–4: FM and dynamic-OT preliminaries","paper.pdf pp. 5–8: OFM objective and Theorem 1","paper.pdf p. 10, Figure 6: initial-plan invariance demonstration","paper.pdf pp. 10–12 and 21–23: high-dimensional, image and runtime tests","source PDF SHA-256 6603e34cf45e490259addb32b297ab4315b53e9fe1f36705d481e45e4856ab7e","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-36071a0581a1017d", "arXiv v1 manuscript", "https://arxiv.org/pdf/2308.06675",
     "Learning fast, accurate, and stable closures of a kinetic theory of an active fluid", "学习活性流体动力学理论的快速、准确且稳定的闭合",
     "theory_numerics", "36071a0581a1017d", "Fluid Dynamics",
     {"doi":"10.1016/j.jcp.2024.112869","arxiv_id":"2308.06675","version":"arXiv v1 full text / JCP accepted article","title":"Learning fast, accurate, and stable closures of a kinetic theory of an active fluid","authors":["Suryanarayana Maddu","Scott Weady","Michael J. Shelley"],"journal":"Journal of Computational Physics","volume":"504","pages":"112869","published":"2024","abstract":"Rotationally invariant neural closures and short-horizon differentiable-solver training yield stable reduced simulations of a two-dimensional active suspension.","comment":"ArXiv v1 full text cross-checked with Journal of Computational Physics metadata"},
     [sec("作者信息", "作者 Suryanarayana Maddu、Scott Weady、Michael J. Shelley；Journal of Computational Physics 504, 112869 (2024)，DOI:10.1016/j.jcp.2024.112869。核验 arXiv:2308.06675v1 全文22页。"),
      sec("研究问题", "active suspension的Smoluchowski kinetic theory同时解析位置与orientation，计算昂贵；只演化低阶moments D、u时又需要未知fourth moment S closure。论文问：能否从kinetic simulations学习既尊重rotation invariance、跨activity parameters泛化，又在长时coarse-grained rollout中稳定的快速closure？"),
      sec("背景", "作者研究二维apolar active rods，将S:D等closure contraction写成由D、strain E等tensor invariants决定的isotropic tensor function。representation theorem/Cayley–Hamilton basis把旋转协变性硬编码进features和output，而不是让网络从component-wise data自行学习。", "a-priori小RMSE不保证a-posteriori PDE稳定：微小closure error经time stepping反馈后可能迅速放大。因此论文把监督拟合与嵌入differentiable pseudo-spectral solver的短窗口优化分开评估。"),
      sec("模型与方法", "作者比较pointwise MLP、local CNN和global Fourier Neural Operator；每种都预测closure系数或tensor，并与quadratic和Bingham closures对照。kinetic truth用SBDF2、Δt=0.0004生成；active learning在dipole α与alignment ζ参数平面迭代选择高error区域的数据。", "MPC式训练把closure网络放进粗粒化solver，在q=4的短时间窗口内最小化moment trajectory discrepancy，并用多个injection points控制memory。该训练不是在线控制器，而是以time-stepping constraints把稳定性信息反馈到parameters。"),
      sec("核心结果与证据", "a-priori tests中invariant features较component-wise learning约提升两个数量级accuracy；在相近parameter count下，pointwise MLP优于CNN/FNO，支持该数据范围内closure主要局域。‘nonlocal effects can be ignored’只针对所测二维模型与observables。", "active learning从参数区域边界/高误差处补点，用单一网络覆盖α、ζ范围；Figure 8显示其优于随机或简单grid sampling的测试RMSE。选择策略依赖已有kinetic simulations，并不消除生成ground truth的成本。", "Figure 10在ζ=7与15比较mean velocity statistic和scalar order parameter：普通supervised MLP与quadratic closure在箭头处失稳，而MPC-MLP在所示时间内紧跟kinetic/Bingham曲线。后续power spectra与timing表明MLP每步成本接近传统closures且远低于kinetic solver。"),
      sec("有效性与局限", "研究限于二维、apolar suspension、指定periodic domain和parameter regime；作者指出3D需要新增tensor bases，并且高分辨3D kinetic truth可能贵到只能以Bingham coarse model代替，这会改变ground-truth层级。", "q=4短窗口带来经验稳定性而非全局numerical-stability theorem；更长时间、不同grid/Δt、超出训练参数域或新initial conditions仍可能失稳。Bingham表现强且保有物理结构，ML closure优势应按accuracy、cost与可靠性共同判断。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2308.06675；期刊：https://doi.org/10.1016/j.jcp.2024.112869。PDF SHA-256：14355d0e8fa36c7a6f4ee967615885dca05228e0eec13d26a745bb37745618c8。正文未给公开代码仓库。", "复现需固定kinetic angular/spatial grids、SBDF2 Δt=0.0004、α/ζ ranges、tensor invariants、architectures、active-learning acquisition、MPC horizon q=4、injection points和rollout stability criteria。Evidence status: full-text verified numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4 kinetic model与closure任务；pp.5–8看invariant representation和architectures；pp.9–11读a-priori/active-learning结果；pp.12–15看MPC、Figure 10、spectra、cost和parameter inference；pp.15–16核对二维/apolar限制。")],
     "figure-10-stable-closures.webp","Figure 10",13,"comparison","ζ=7和15下kinetic、Bingham、quadratic、MLP与MPC-MLP的velocity statistic和scalar order parameter。","短窗口solver-in-the-loop训练使MPC-MLP保持稳定并跟随kinetic统计，而普通MLP和quadratic closure发生失稳。","Figure 10直接区分低a-priori误差与真正可用的a-posteriori稳定rollout。",
     [{"label":"Short-horizon solver-in-the-loop loss","latex":r"\mathcal L_q(\theta)=\sum_{l=1}^{q}\nu_l\|\widehat D_{n+l}(\theta)-D_{n+l}^{\rm kinetic}\|_2^2","role":"train a closure through its effect on several numerical time steps","symbols":{"q":"training horizon, set to four","nu_l":"decaying horizon weights","D":"second orientational moment"},"evidence":"paper.pdf pp. 11–13, MPC formulation and Figure 9","interpretation":"Observed long-rollout stability is empirical and specific to the tested solver and parameter regimes."}],
     ["paper.pdf pp. 1–4: kinetic theory and moment closure problem","paper.pdf pp. 5–9: invariant tensor learning and architecture comparison","paper.pdf pp. 9–11, Figures 7–8: active parameter sampling","paper.pdf pp. 11–14, Figures 9–12: MPC stability, spectra and cost","source PDF SHA-256 14355d0e8fa36c7a6f4ee967615885dca05228e0eec13d26a745bb37745618c8","Evidence status: full-text verified numerical study; no independent reproduction performed."])
]


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids = []
    for item in CARDS:
        paper_id = str(item["arxiv_id"])
        (OUT / f"{paper_id}.json").write_text(
            json.dumps(item, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        ids.append(paper_id)
    print(json.dumps({"installed": ids}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
