#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 052."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"data"/"collection_cards"

CARDS=[
card("record-d748aca86800c37b","Nature Physics article / arXiv manuscript","https://arxiv.org/pdf/2403.08466",
"Evidence of universal conformal invariance in living biological matter","活体生物物质中普适共形不变性的证据","theory_experiment","d748aca86800c37b","Statistical Physics",
{"doi":"10.1038/s41567-025-02791-2","arxiv_id":"2403.08466","version":"arXiv manuscript cross-checked with version of record","title":"Evidence of universal conformal invariance in living biological matter","authors":["Benjamin H. Andersen","Francisco M. R. Safara","Valeriia Grudtsyna","Oliver J. Meacock","Simon G. Andersen","William M. Durham","Nuno A. M. Araujo","Amin Doostmohammadi"],"journal":"Nature Physics","volume":"21","pages":"618–623","published":"2025","abstract":"Vorticity contours from four cellular systems obey common fractal, winding-angle and SLE statistics consistent with the percolation universality class.","comment":"Open-access Nature Physics metadata cross-checked with arXiv full text"},
[sec("作者信息","作者 Benjamin H. Andersen、Francisco M. R. Safara、Valeriia Grudtsyna 等；Nature Physics 21, 618–623 (2025)，DOI:10.1038/s41567-025-02791-2。核验 arXiv:2403.08466 全文12页与开放期刊元数据。"),
sec("研究问题","犬肾上皮细胞、人乳腺癌细胞及两种致病细菌的驱动与相互作用完全不同，它们产生的collective vortical flows是否仍共享与尺度、旋转和平移无关的几何统计？这些等涡量轮廓能否由Schramm–Loewner evolution统一描述？"),
sec("背景","二维临界系统的conformal invariance可由随机曲线统计检验。SLE以单一参数κ分类universality class；percolation hull对应κ=6、fractal dimension D=1+κ/8=7/4，winding-angle variance具有指定log slope。","从velocity fields抽取vorticity contours后再检验多个独立标度律，比只拟合一个power law更强；但‘属于universality class’仍是有限尺度实验统计结论。"),
sec("模型与方法","作者用高分辨成像与PIV/optical-flow类处理得到四种cell collective的velocity/vorticity fields，选取closed contours，测量perimeter与radius of gyration、winding angle及left-passage probability。","随后将曲线映射到upper half-plane，反演Loewner driving function，检查其Gaussian increments和variance∝κt；并用active-matter continuum simulation测试同样统计。"),
sec("核心结果与证据","Figure 1展示四系统的coherent flows及尺度跨度。Figure 2a中perimeter对radius of gyration在所有系统上给D≈7/4；Figure 2b的winding-angle variance斜率≈6/7，两项均符合SLE6。","Figure 3的driving-function variance和left-passage probability给κ≈6；Table 1汇总不同测量方法与systems的一致性。continuum active model也复现实验曲线统计。","一致的κ与D支持percolation-class conformal geometry，但不证明这些活体系统处在同一热力学critical point，也不消除finite field-of-view、segmentation和curve-selection bias。"),
sec("有效性与局限","系统仅四类、二维观测且时间/空间尺度有限；轮廓不是独立样本，PIV smoothing和vorticity threshold会改变小尺度结构。作者做多指标交叉检验，但universality范围仍需更多organisms和实验条件。","SLE严格定义于理想连续平面曲线，实验中的closed finite contours需映射与端点选择。active model复现统计不唯一确定microscopic mechanism。"),
sec("复现与资源","全文：https://arxiv.org/abs/2403.08466；期刊：https://doi.org/10.1038/s41567-025-02791-2。PDF SHA-256：ed0fa82771633858cb2e953057f4fe6f05fd49d0a877a1f48d32e2753059ca92。数据/代码可用性应以期刊Supplementary Information和作者声明为准，预印本文本未给单一仓库URL。","复现需固定image calibration、velocity estimator、vorticity threshold、contour filtering、conformal map、driving-function discretization和bootstrap unit。Evidence status: full-text verified theory/experiment study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–3 Figure 1与四实验系统；p.4 Figure 2看两种scale test；pp.5–7 Figure 3/Table 1看SLE6判别；pp.8–12为方法与补充分析。")],
"figure-2-conformal-scaling.webp","Figure 2",4,"data_plot","四类cellular systems的vorticity contours共同满足fractal-dimension与winding-angle标度。","独立几何统计分别接近D=7/4和6/7斜率，均与percolation SLE6预测一致。","Figure 2把四种生物系统叠加在同一两项标度检验上，是普适性主张最直接且可比较的实验图证。",
[{"label":"SLE fractal dimension","latex":r"D=1+\frac{\kappa}{8},\qquad \kappa=6\Rightarrow D=\frac{7}{4}","role":"link contour geometry to the SLE universality parameter","symbols":{"D":"fractal dimension","kappa":"SLE diffusivity parameter"},"evidence":"paper.pdf pp. 3–5, Figure 2 and SLE discussion","interpretation":"Agreement across several finite-size diagnostics supports, but does not mathematically prove, continuum SLE6."}],
["paper.pdf pp. 1–3, Figure 1: four biological flow systems","paper.pdf p. 4, Figure 2: fractal and winding-angle scaling","paper.pdf pp. 5–7, Figure 3 and Table 1: SLE parameter tests","paper.pdf pp. 8–12: methods and controls","source PDF SHA-256 ed0fa82771633858cb2e953057f4fe6f05fd49d0a877a1f48d32e2753059ca92","Evidence status: full-text verified theory/experiment study; no independent reproduction performed."]),

card("record-dfc81cbdbbcf1b33","ICML 2024 full text","https://arxiv.org/pdf/2310.16834",
"Discrete Diffusion Modeling by Estimating the Ratios of the Data Distribution","通过估计数据分布比率进行离散扩散建模","theory_numerics","dfc81cbdbbcf1b33","Transformer Theory",
{"doi":None,"arxiv_id":"2310.16834","version":"arXiv v3 / ICML 2024 full text","title":"Discrete Diffusion Modeling by Estimating the Ratios of the Data Distribution","authors":["Aaron Lou","Chenlin Meng","Stefano Ermon"],"journal":"Proceedings of the 41st International Conference on Machine Learning","volume":"PMLR 235","pages":"32819–32848","published":"2024","abstract":"Score entropy learns discrete probability ratios for reverse continuous-time Markov chains, producing competitive non-autoregressive language models.","comment":"ICML 2024 Best Paper; PMLR metadata cross-checked with arXiv v3"},
[sec("作者信息","作者 Aaron Lou、Chenlin Meng、Stefano Ermon；ICML 2024, PMLR 235, 32819–32848；对应 arXiv:2310.16834v3。核验全文30页；PMLR未列传统DOI。"),
sec("研究问题","continuous diffusion依赖score ∇log p，但text/token state space没有普通梯度。如何定义可训练的discrete score，让reverse continuous-time Markov chain无需显式归一化整个vocabulary，并在likelihood、sampling与infilling上接近autoregressive language models？"),
sec("背景","离散reverse rates取决于相邻states的marginal probability ratio p_t(y)/p_t(x)。直接ratio matching或dimension-wise prediction可能不稳定/不一致。作者定义score entropy，使最优sθ(x)_y恰为这些ratios。","SEDD仍使用Transformer backbone和forward noise process；它是非autoregressive生成机制，不意味着一次network pass生成完整高质量序列。"),
sec("模型与方法","论文从finite-state CTMC推导implicit与denoising score entropy。denoising form只需从clean x0采样noisy xt和transition kernel，避免未知p_t；network输出与allowed transitions对应的ratios。","实现uniform与absorbing noise graphs，推导reverse sampler与Tweedie-style改进，并将conditioning/infilling作为clamping or reverse dynamics约束。训练在text8、OpenWebText和LM1B等语料上。"),
sec("核心结果与证据","Table 1显示同规模SEDD在多个zero-shot datasets上优于D3PM等离散diffusion，并与GPT-2量级autoregressive baselines竞争；Table 2在text8报告bits-per-character。","Figure 1按生成样本文本的external perplexity比较SEDD与GPT-2，SEDD无需temperature/nucleus annealing也能保持较好质量；sampling steps可与quality交换。Tables 4–5展示prefix/suffix infilling。","‘32× fewer evaluations’是相对论文自身特定diffusion sampler/quality点，不等于比所有autoregressive systems快32×；wall-clock还受每步全序列attention成本影响。"),
sec("有效性与局限","评估模型规模和数据远小于当前frontier LLM；perplexity由模型likelihood或外部evaluator测量，不能完整代表语义事实性。diffusion采样仍多步，长序列memory/latency未充分解决。","score ratios依赖noise graph；uniform graph在大vocabulary需结构化输出，absorbing schedule引入mask inductive bias。结果不保证任意discrete domains或conditional generation都同样有效。"),
sec("复现与资源","全文：https://arxiv.org/abs/2310.16834；代码：https://github.com/louaaron/Score-Entropy-Discrete-Diffusion。PDF SHA-256：1f3a135a52346270ef4b0872d52f17954af7ea0fa53d0a0b31a9183599ec976e。","复现需固定dataset/tokenizer、noise graph/schedule、small/medium Transformer configs、training tokens、likelihood estimator、sampling steps与temperature-free decoding，并记录hardware latency。Evidence status: full-text verified theoretical/empirical study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–4 discrete score与score entropy；pp.4–6 denoising objective/sampler；pp.6–9 Tables 1–5；pp.10–13看局限；pp.14–30为证明与样例。")],
"tables-1-3-language-results.webp","Tables 1–3",6,"table","SEDD与GPT-2、D3PM等模型在zero-shot perplexity、text8 BPC和LM1B上的比较。","在给定模型规模和训练设置下，SEDD显著改善既有离散diffusion并达到autoregressive基线量级。","Tables 1–3集中呈现likelihood核心结论，并保留数据集、规模与指标限定，是最可核查的性能证据。",
[{"label":"Discrete score ratio","latex":r"s_t(x)_y=\frac{p_t(y)}{p_t(x)}","role":"parameterize reverse transition rates between discrete states","symbols":{"p_t":"noisy marginal distribution","x,y":"connected discrete states","s_t":"learned ratio score"},"evidence":"paper.pdf pp. 2–5, score entropy definitions","interpretation":"The denoising objective learns these ratios without evaluating the unknown marginal normalizer."}],
["paper.pdf pp. 1–4: discrete ratios and score entropy","paper.pdf pp. 4–6: denoising loss and reverse sampler","paper.pdf pp. 6–9, Tables 1–5 and Figure 1: language results","paper.pdf pp. 14–30: proofs, samples and ablations","source PDF SHA-256 1f3a135a52346270ef4b0872d52f17954af7ea0fa53d0a0b31a9183599ec976e","Evidence status: full-text verified theoretical/empirical study; no independent reproduction performed."]),

card("record-e18c172140e13493","Entropy review / arXiv manuscript","https://arxiv.org/pdf/2207.06415",
"The Free Energy Principle for Perception and Action: A Deep Learning Perspective","用于感知与行动的自由能原理：深度学习视角","theory","e18c172140e13493","Machine Learning",
{"doi":"10.3390/e24020301","arxiv_id":"2207.06415","version":"arXiv full text cross-checked with Entropy review","title":"The Free Energy Principle for Perception and Action: A Deep Learning Perspective","authors":["Pietro Mazzaglia","Tim Verbelen","Ozan Çatal","Bart Dhoedt"],"journal":"Entropy","volume":"24","pages":"301","published":"2022","abstract":"A review maps variational and expected free energy to deep generative world-model learning and several amortized active-inference action-selection designs.","comment":"Review article; not a new experimental benchmark"},
[sec("作者信息","作者 Pietro Mazzaglia、Tim Verbelen、Ozan Çatal、Bart Dhoedt；Entropy 24, 301 (2022)，DOI:10.3390/e24020301。核验 arXiv:2207.06415 全文21页；文章性质为综述/实践指南。"),
sec("研究问题","free-energy principle与active inference的数学表述如何转译为深度学习工程组件？在world-model学习、uncertainty、representation、amortization、preferences、epistemic value和planning之间有哪些可选设计，而它们与RL/VAE术语如何对应？"),
sec("背景","variational free energy是sensory surprisal的可计算upper bound，优化approximate posterior同时学习generative model。expected free energy用于未来policy评估，结合preferred outcomes与information gain。","FEP作为生物理论有强假设和争议；本文目标是组织已有计算实现，不是通过新实验证明大脑必然最小化某个特定自由能。"),
sec("模型与方法","Figure 1把过去经验的variational inference与未来行为的expected-free-energy selection分成两条链。作者以POMDP/generative model写出observations、latent states、actions、transition、likelihood和preferences。","综述比较VAE-style posterior/decoder、deterministic或stochastic dynamics、hierarchical/memory representations，以及explicit planning、amortized policy、habit learning和tree search。Tables 1–2汇总实现choices。"),
sec("核心结果与证据","核心产出不是benchmark，而是设计空间：Figure 3给active-inference graphical model；Figure 4连接world models/representation learning；Figure 5比较plan selection、amortized action和habit/search。","文章澄清active-inference preferences不是RL中外加的瞬时reward，而是generative model期望频繁访问的outcomes；但二者可在特定control-as-inference形式下建立数学对应。","所列算法跨不同任务、评价和假设，不能由综述直接排出普遍优劣。Figure 1适合作为阅读地图，而非性能证据。"),
sec("有效性与局限","综述截至2022，后续world models、diffusion policies和large-scale agents不在范围。不同论文使用的free-energy符号、precision与epistemic terms可能不等价。","FEP的宽泛版本可能难falsify；实际实现仍需指定state model、preferences、horizon和approximation。文章未提供统一代码、同任务reimplementation或controlled empirical comparison。"),
sec("复现与资源","全文：https://arxiv.org/abs/2207.06415；期刊：https://doi.org/10.3390/e24020301。PDF SHA-256：1e8a749aa370ed0189cbb610d9904643e048daac0beda407d1065b75475bbc3d。综述没有单一伴随代码仓库。","复核应分别追踪VFE与EFE定义、KL方向、preference distribution和policy posterior；实现时记录latent dynamics、uncertainty estimator、planning horizon与baselines。Evidence status: full-text verified review; no independent reproduction performed."),
sec("阅读指南","先读 p.1 Figure 1总览；pp.2–5 VFE/EFE；pp.5–12看world-model设计；pp.12–17看action selection与Figure 5；pp.17–21为讨论与参考文献。")],
"figure-1-free-energy-map.webp","Figure 1",1,"schematic","variational free energy与expected free energy两条优化链及其深度学习设计因素。","该图把model learning、state inference、preferences、epistemics和planning放在同一active-inference地图中。","作为综述文章，Figure 1最完整地定义范围和章节路线，适合代表框架而不冒充实验性能证据。",
[{"label":"Variational free energy","latex":r"F[q]=\mathbb{E}_{q(s\mid o)}[\log q(s\mid o)-\log p(o,s)]\ge-\log p(o)","role":"bound sensory surprisal while fitting an approximate posterior","symbols":{"q":"recognition or posterior model","p":"generative model","o":"observation","s":"latent state"},"evidence":"paper.pdf pp. 2–4, variational free-energy derivation","interpretation":"The bound becomes tight only when q matches the exact posterior under the chosen model."}],
["paper.pdf p. 1, Figure 1: review map","paper.pdf pp. 2–5: variational and expected free energy","paper.pdf pp. 5–12, Figures 3–4 and Table 1: model learning","paper.pdf pp. 12–17, Figure 5 and Table 2: action selection","source PDF SHA-256 1e8a749aa370ed0189cbb610d9904643e048daac0beda407d1065b75475bbc3d","Evidence status: full-text verified review; no independent reproduction performed."]),

card("record-e59dd3f1b8f69ef0","Science Advances article / arXiv manuscript","https://arxiv.org/pdf/2202.12853",
"Physically informed data-driven modeling of active nematics","活性向列液晶的物理信息数据驱动建模","theory_experiment","e59dd3f1b8f69ef0","Active Matter",
{"doi":"10.1126/sciadv.abq6120","arxiv_id":"2202.12853","version":"arXiv full text cross-checked with Science Advances","title":"Physically informed data-driven modeling of active nematics","authors":["Matthew Golden","Roman O. Grigoriev","Jyothishraj Nambisan","Alberto Fernández-Nieves"],"journal":"Science Advances","volume":"9","pages":"eabq6120","published":"2023","abstract":"SPIDER uses weak-form sparse regression and symmetry-constrained libraries to discover interpretable active-nematic field equations directly from microtubule experiments.","comment":"Open-access Science Advances article with public MATLAB code"},
[sec("作者信息","作者 Matthew Golden、Roman O. Grigoriev、Jyothishraj Nambisan、Alberto Fernández-Nieves；Science Advances 9, eabq6120 (2023)，DOI:10.1126/sciadv.abq6120。核验 arXiv:2202.12853 全文22页。"),
sec("研究问题","现有Leslie–Ericksen/Beris–Edwards active-nematic models有许多难测参数，且可能不适合油水界面上的microtubule bundles。能否直接由实验director、velocity和order fields发现闭合、稀疏、可解释的PDE relations及系数？"),
sec("背景","topological defects使director n不能全局连续，因此使用Q_ij=S n_i n_j及density/order proxy φ。SPIDER先用symmetry、tensor rank和derivative order生成候选terms，再以weak integral form降低实验微分噪声。","发现的是给定observables和library下的effective continuum relations；遗漏变量可能被吸收到系数或低阶terms中。"),
sec("模型与方法","对每种目标tensor/scalar relation，随机选择space-time integration domains，以smooth test functions把derivatives转移出noisy fields，构造feature matrix。iterative sparse regression沿residual–complexity Pareto curve删除terms。","候选模型用独立domains和symmetry tests验证，并从weak coefficients恢复strong form。原始荧光MT images、PIV velocity、Q/φ fields及confidence weights共同限定可靠区域。"),
sec("核心结果与证据","Figures 2–3展示SPIDER feature construction与稀疏selection。Figure 4比较identified strong-form terms的spatial fields：incompressibility近似成立，orientation transport与active/viscous/friction stresses在可靠区域相互平衡。","发现的结构类似经典active nematics，但该实验中elastic terms未被选中；动力学主要由active stress与friction/viscous response控制。Figure 5量化不同relations residual并显示defects附近误差更大。","‘elasticity不起作用’限定于此dataset、分辨率、library与operating regime；未选择不等于微观elasticity严格为零。"),
sec("有效性与局限","velocity/director reconstruction和mask会系统影响terms；weak form减少noise却牺牲local resolution。候选库、maximum derivative/nonlinearity order和sparsity threshold构成强inductive bias。","只有一个主要experimental platform/regime，缺少外部预测experiment和perturbation validation。识别relations可能因feature collinearity不唯一，作者用多个domains和residual hierarchy缓解但未完全消除。"),
sec("复现与资源","全文：https://arxiv.org/abs/2202.12853；期刊：https://doi.org/10.1126/sciadv.abq6120；MATLAB代码：https://github.com/mgolden30/SPIDER_active_nematics。PDF SHA-256：9d7fcd44ff136b0c0d717740164b7ccde7c1beecdb654bd32b86b2fa3b162f8c。","复现需固定field extraction、confidence masks、library table、weak-domain sizes/test functions、normalization、deletion path和model-selection elbow；应保留raw-to-field provenance。Evidence status: full-text verified theory/experiment study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–3 Figure 1与observables；pp.3–6 Figures 2–3看SPIDER；pp.6–9 Figures 4–5看发现方程；pp.10–16读methods；pp.17–22为supplementary推导。")],
"figure-4-identified-fields.webp","Figure 4",7,"field_map","实验snapshot上identified strong-form relation各项的空间场对比。","观测到的active、viscous与friction terms在可靠区域形成局部平衡，而经典elastic项未进入稀疏模型。","Figure 4把抽象稀疏方程映回真实实验空间，是判断各物理项是否解释数据的中心图证。",
[{"label":"Nematic tensor","latex":r"Q_{ij}=S n_i n_j","role":"represent apolar orientation continuously away from scalar-order defects","symbols":{"S":"local order parameter","n":"director with n equivalent to -n","Q":"nematic tensor field"},"evidence":"paper.pdf pp. 2–3, experimental observables","interpretation":"The discovery library is built from Q, velocity, order and their symmetry-allowed derivatives."}],
["paper.pdf pp. 1–3, Figure 1: experiment and reconstructed fields","paper.pdf pp. 3–6, Figures 2–3: SPIDER algorithm","paper.pdf pp. 6–9, Figures 4–5: identified relations","paper.pdf pp. 10–16: weak-form and regression methods","source PDF SHA-256 9d7fcd44ff136b0c0d717740164b7ccde7c1beecdb654bd32b86b2fa3b162f8c","Evidence status: full-text verified theory/experiment study; no independent reproduction performed."]),

card("record-f556c7709f95836f","NeurIPS 2022 full text","https://arxiv.org/pdf/2208.05003",
"Wavelet Score-Based Generative Modeling","小波得分生成建模","theory_numerics","f556c7709f95836f","Generative Models",
{"doi":None,"arxiv_id":"2208.05003","version":"arXiv full text / NeurIPS 2022","title":"Wavelet Score-Based Generative Modeling","authors":["Florentin Guth","Simon Coste","Valentin De Bortoli","Stéphane Mallat"],"journal":"Advances in Neural Information Processing Systems","volume":"35","pages":None,"published":"2022","abstract":"Wavelet factorization conditions fine coefficients on coarser scales, controls score ill-conditioning and gives linear-in-image-size sampling complexity under stated assumptions.","comment":"NeurIPS 2022 proceedings paper; DOI not asserted"},
[sec("作者信息","作者 Florentin Guth、Simon Coste、Valentin De Bortoli、Stéphane Mallat；NeurIPS 2022，卷35；对应 arXiv:2208.05003。核验全文42页，含理论与补充实验；正文未列传统DOI。"),
sec("研究问题","pixel-space score models在大图和临界随机场中为何需要很多reverse-SDE steps？能否用orthogonal wavelet multiscale factorization降低conditional score的Hessian condition number，使各尺度使用固定步数且总复杂度随pixels线性增长？"),
sec("背景","forward diffusion把data逐渐高斯化，reverse integration稳定性受score Jacobian/Hessian最大与最小eigenvalues控制。scale-invariant distributions在pixel coordinates中低频/高频variance跨度随image size增长，造成stiffness。","wavelet transform本身不生成数据；WSGM把joint distribution分解为coarse marginal与逐尺度detail conditional，每一级各训练conditional score。"),
sec("模型与方法","使用orthogonal wavelet把x_j−1分为coarse x_j和detail coefficients，写p(x)=p(x_J)∏p(detail_j|x_j)。从最粗尺度开始，reverse SDE依次生成各scale details并inverse transform。","理论对Gaussian stationary processes证明renormalized wavelet conditional covariance在适当wavelet moments下condition number不随image size发散。实验覆盖φ4 critical fields、turbulence类physical processes与CelebA等natural images。"),
sec("核心结果与证据","Figure 2比较pixel SGM与WSGM估计covariance随steps的误差；普通SGM达到固定误差所需N随L增长，而WSGM近乎size-independent，对应总linear complexity。","Figure 3在不同L的φ4 fields比较distribution statistics；Figure 4在固定16 steps下显示pixel SGM artifacts明显，WSGM生成更接近reference，且报告FID/物理统计改善。","线性complexity是每scale固定steps与network cost assumptions下的渐近结论；多尺度模型数量、训练成本、channel widths和硬件并行会影响实际wall-clock。"),
sec("有效性与局限","Gaussian theorem不直接覆盖strongly non-Gaussian natural images；wavelet choice、boundary handling和conditional architecture会影响conditioning。逐尺度生成仍串行，超高分辨率的memory与training data成本未消失。","自然图像实验不是当代大型diffusion的统一SOTA比较；图像quality与physical-statistics benchmarks规模有限。wavelet factorization可能引入方向/translation artifacts。"),
sec("复现与资源","全文：https://arxiv.org/abs/2208.05003；会议PDF：https://proceedings.neurips.cc/paper_files/paper/2022/hash/03474669b759f6d38cdca6fb4eb905f4-Abstract-Conference.html。PDF SHA-256：4f3f173b8075a91c844d687ea87679400f1aaae2d7a96efb402366120e1ef77a。正文提供Algorithm 1与补充参数，未在主文列单一官方代码URL。","复现需固定wavelet family/levels、normalization、score architectures、SDE schedule、steps per scale、φ4 sampler、image preprocessing及FID/statistics实现。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
sec("阅读指南","先读 pp.1–4 Figure 1与factorization；pp.4–7 conditioning theory；pp.7–10 Figures 2–4；pp.11–13局限；pp.14–42为proofs、Algorithm 1与额外实验。")],
"figure-2-conditioning.webp","Figure 2",7,"comparison","普通SGM与WSGM的covariance error随reverse steps和image size变化。","pixel-space所需steps随L增加，而wavelet conditional models达到同一误差的steps近乎与L无关。","Figure 2直接检验论文的conditioning与线性复杂度机制，比单纯展示生成样本更能支撑中心主张。",
[{"label":"Wavelet probability factorization","latex":r"p(x)=p(x_J)\prod_{j=1}^{J}p(\bar x_j\mid x_j)","role":"generate coarse content first and conditionally synthesize wavelet details at each scale","symbols":{"x_J":"coarsest coefficients","bar_x_j":"detail coefficients","j":"wavelet scale"},"evidence":"paper.pdf pp. 3–5, multiscale factorization","interpretation":"Separate conditional scores reduce cross-scale stiffness under the paper's assumptions."}],
["paper.pdf pp. 1–4, Figure 1: wavelet SGM construction","paper.pdf pp. 4–7: conditioning and complexity theory","paper.pdf pp. 7–10, Figures 2–4: Gaussian, critical-field and image tests","paper.pdf pp. 14–42: proofs, algorithms and supplementary experiments","source PDF SHA-256 4f3f173b8075a91c844d687ea87679400f1aaae2d7a96efb402366120e1ef77a","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."])
]
def main()->int:
 OUT.mkdir(parents=True,exist_ok=True); ids=[]
 for item in CARDS:
  pid=str(item["arxiv_id"]); (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); ids.append(pid)
 print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__=="__main__": raise SystemExit(main())
