#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 045."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

CARDS = [
card("doi-10.52202-079017-2315", "arXiv v2 manuscript", "https://arxiv.org/pdf/2405.15926",
     "Dissecting the Interplay of Attention Paths in a Statistical Mechanics Theory of Transformers",
     "用Transformer统计力学理论剖析注意力路径的相互作用", "theory_numerics", "c3305c4765375bc3", "Transformer Theory",
     {"doi":"10.52202/079017-2315","arxiv_id":"2405.15926","version":"arXiv v2 full text","title":"Dissecting the Interplay of Attention Paths in a Statistical Mechanics Theory of Transformers","authors":["Lorenzo Tiberi","Francesca Mignacco","Kazuki Irie","Haim Sompolinsky"],"journal":"Advances in Neural Information Processing Systems","volume":"37","pages":"72710–72753","published":"2024","abstract":"A finite-width Bayesian theory expresses a deep multi-head attention predictor as task-adapted combinations of kernels coupling pairs of attention paths.","comment":"ArXiv v2 full text cross-checked with NeurIPS proceedings metadata"},
     [sec("作者信息", "作者 Lorenzo Tiberi、Francesca Mignacco、Kazuki Irie、Haim Sompolinsky；NeurIPS 2024 / Advances in Neural Information Processing Systems 37, 72710–72753，DOI:10.52202/079017-2315。核验 arXiv:2405.15926v2 全文37页及公开代码。"),
      sec("研究问题", "深层multi-head attention形成许多跨层head序列，即attention paths；传统infinite-width GP极限会令隐藏权重独立，抹去路径间学习后的耦合。论文问：在训练样本P与宽度N共同趋大且P/N=O(1)时，能否精确描述路径怎样组合、哪些路径与任务相关，以及这种结构是否解释generalization和可剪枝性？"),
      sec("背景", "作者研究与Transformer相近但可解析的深层self-attention模型：query/key weights固定，Bayesian learning作用于value/readout weights。每条attention path选取每层一个head；任意两条路径形成path–path kernel，完整predictor由这些kernel加权求和。", "这不是标准Transformer全参数训练的精确理论。固定Q/K、Bayesian posterior、平方损失与thermodynamic limit使计算闭合；迁移到gradient descent模型只由实验定性支持。"),
      sec("模型与方法", "replica/statistical-mechanics推导给出posterior predictor mean和covariance的self-consistent saddle-point equations。order parameter U编码不同路径value weights的幅值与相关性，使总kernel根据labels重新加权；α=P/N→0时回到未学习组合的GP limit。", "验证包括synthetic hidden-Markov-chain序列分类和Omniglot one-shot classification，并在FashionMNIST等OOD集测试；比较理论、Bayesian sampling与gradient descent，另用理论head score做pruning。"),
      sec("核心结果与证据", "Figure 2的两层两头HMC模型含4条路径：一条good、一条denoising和两条adversarial。有限N时任务相关U压低adversarial路径、组合good与denoising kernel，分类准确率高于全部路径的GP极限；理论曲线与posterior samples吻合。", "Figure 3在Omniglot/FashionMNIST复现kernel-task alignment，并显示由learned weights估计的empirical order parameter与Bayesian理论趋势一致。该一致性是特定浅层attention模型证据，不证明大语言模型所有head具有相同机制。", "Appendix pruning实验以head score移除低相关head，在所测任务中可缩小网络而保持大部分accuracy；它是机制的应用演示，不是与现代结构化pruning方法的全面效率benchmark。"),
      sec("有效性与局限", "exact equations依赖N,P同时趋大、fixed ratio、Gaussian priors和固定attention maps；有限数据/宽度的近似误差在图中评估但无普适界。真实Transformer的softmax Q/K也学习、含MLP、layer norm、residual与cross-entropy，路径定义和耦合会改变。", "synthetic和小规模vision任务说明可控机制，不代表语言建模或大规模in-context learning。head score可能受参数ization和path冗余影响，单head移除的performance drop也不是因果功能的唯一度量。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2405.15926；代码：https://github.com/tiberilor/attention-paths-interplay。核验PDF SHA-256：94d7ba693600d3867071fdc1c0e351cba002bf1852b67d9ebf40e58d1561a317。", "复现需固定Q/K construction、prior variance、α、N、P、posterior sampler、gradient optimizer、task split和head-pruning顺序。Evidence status: full-text verified theory/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.2–3 Figure 1和path–path kernel定义；pp.4–6看predictor equations与U。p.7 Figure 2是最直观机制，pp.8–9 Figure 3看真实图像任务；pp.33–37核对噪声、OOD和pruning补充。")],
     "figure-2-attention-paths.webp","Figure 2",7,"comparison","HMC任务、四条attention paths、准确率、order parameter与kernel-label alignment。","有限宽度学习通过U组合good与denoising路径并抑制adversarial路径。","Figure 2在一个可控任务中同时连接路径结构、统计力学预测和分类性能。",
     [{"label":"Task-adapted kernel predictor","latex":r"\bar f(x)=\mathbf k_U(x)^T(\mathbf K_U+\lambda I)^{-1}\mathbf y,\qquad \mathbf K_U=\sum_{\pi,\pi'}U_{\pi\pi'}\mathbf K_{\pi\pi'}","role":"combine path-pair kernels according to learned task relevance","symbols":{"pi":"attention path","U":"path coupling order parameter","y":"training labels"},"evidence":"paper.pdf pp. 4–6, predictor statistics","interpretation":"The formula holds for the paper's Bayesian finite-width model with fixed query/key weights."}],
     ["paper.pdf pp. 2–6: attention paths and finite-width theory","paper.pdf p. 7, Figure 2: HMC mechanism test","paper.pdf pp. 8–9, Figure 3: one-shot and OOD tests","paper.pdf pp. 33–37, Figures 5–7: robustness and pruning","source PDF SHA-256 94d7ba693600d3867071fdc1c0e351cba002bf1852b67d9ebf40e58d1561a317","Evidence status: full-text verified theory/numerical study; no independent reproduction performed."]),

card("doi-10.52202-085713-2961", "arXiv v3 manuscript", "https://arxiv.org/pdf/2505.19350",
     "FlashMD: long-stride, universal prediction of molecular dynamics", "FlashMD：分子动力学的长步长通用预测",
     "theory_numerics", "cac2f42d53a43b72", "AI for Science",
     {"doi":"10.52202/085713-2961","arxiv_id":"2505.19350","version":"arXiv v3 full text (post-proceedings revision)","title":"FlashMD: long-stride, universal prediction of molecular dynamics","authors":["Filippo Bigi","Sanggyu Chong","Agustinus Kristiadi","Michele Ceriotti"],"journal":"Advances in Neural Information Processing Systems","volume":"38","pages":"98379–98416","published":"2025","abstract":"Equivariant direct propagators predict molecular positions and momenta over strides one to two orders larger than conventional integration, with physics filters and ensemble control.","comment":"Evidence uses arXiv v3 dated 2026-01-22, newer than the NeurIPS 2025 proceedings record"},
     [sec("作者信息", "作者 Filippo Bigi、Sanggyu Chong、Agustinus Kristiadi、Michele Ceriotti；NeurIPS 2025，DOI:10.52202/085713-2961。页码证据来自 arXiv:2505.19350v3（2026-01-22，31页），它晚于会议版本，故本卡明确按v3陈述。"),
      sec("研究问题", "ML interatomic potentials降低每次force evaluation成本，却仍受0.5–1 fs积分步长限制。论文问：能否直接从当前positions q和momenta p预测长stride后的状态，跳过中间force/integration，并仍保持equivariance、energy behavior、thermodynamic ensembles及平衡/动力学observable？"),
      sec("背景", "FlashMD学习phase-space propagator而非potential。MD确定、Markov但通常chaotic：误差随Lyapunov exponent放大，所以长stride target最终不可预测；作者把这一上限、symplecticity、rotation covariance和energy conservation列为架构约束与failure modes。", "‘universal’指训练于多化学体系的MAD/PET数据并迁移若干系统，不是对任意元素、相态或反应的保证；reference dynamics本身来自MLIP而非直接ab-initio on the fly。"),
      sec("模型与方法", "模型以equivariant graph network预测mass-scaled displacement和momentum increment；random-rotation filter修正非严格equivariant backbone，inference-time energy filter沿预测momentum方向调节以满足目标Hamiltonian。split-operator结构把长stride propagator嵌入Langevin thermostat/barostat，支持NVT/NpT。", "分别训练water-specific与universal models，stride覆盖1–64/128 fs量级；评估water RDF、temperature和density，以及alanine Ramachandran分布、Al(110) premelting和LiPS diffusion。附录检查uncertainty、energy drift、timing与Lyapunov尺度。"),
      sec("核心结果与证据", "Figure 2显示water-specific FlashMD在多个stride下复现O–O/O–H RDF；density较reference接近但并非统计等价。universal模型偏差更大，作者明确指出其误差仍小于更换电子结构方法的典型差异，这是一种尺度比较而非精确一致。", "Figure 3中alanine以8–16 fs再现主要Ramachandran basin（相对0.5 fs MD达16–32倍stride），Al表面捕捉soft-mode/premelting趋势，LiPS给出温度依赖diffusion的定性/定量测试。局部thermostat会破坏动力学，因此作者主要强调静态平衡observable。", "timing表显示实际加速低于stride倍率，且随system/GPU变化；长trajectory不能逐原子保持shadowing，只要求distributional observables。v3还警告所有FlashMD发现应以传统MD复核。"),
      sec("有效性与局限", "chaos给可学stride设置系统相关上限；out-of-domain uncertainty并不自动保证检测所有失败。energy projection可稳定NVE但不保证symplectic map或正确动力学相关函数，thermostat虽修正sampling也可能遮蔽propagator误差。", "训练target依赖PET-MAD/PET-OMATPES及其DFT functional偏差；化学反应、rare events和新composition需单独验证。模型输出轨迹是近似生成器，不能替代精确积分来确认新机制。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2505.19350；代码：https://github.com/lab-cosmo/flashmd；材料：https://doi.org/10.24435/materialscloud:b7-xq。PDF SHA-256：4834d435bf449c44ba5ccde36c6a2613ce5ba967e5b26d77f07194eb6db07368。", "复现需固定v3、flashmd/model checkpoint、reference MLIP、stride、ensemble operators、energy filter、initial conditions和observable block averaging。Evidence status: full-text verified theory/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.2–5问题与Figure 1，再读 pp.5–7架构/ensemble。p.8 Figure 2看water，pp.8–9 Figure 3看三类迁移；pp.24–31检查uncertainty、energy drift、timings与Lyapunov failure boundary。")],
     "figure-2-water-observables.webp","Figure 2",8,"comparison","传统MD与water-specific/universal FlashMD的径向分布函数和NpT密度。","长stride模型可保留主要平衡结构，但density尤其通用模型仍有可见偏差。","Figure 2同时呈现成功与偏差，适合作为distributional而非trajectory-exact主张的证据。",
     [{"label":"Long-stride propagator","latex":r"(\mathbf q_{t+\Delta\tau},\mathbf p_{t+\Delta\tau})=\mathcal F_\theta(\mathbf q_t,\mathbf p_t;\Delta\tau)","role":"skip intermediate force evaluations and integration steps","symbols":{"q":"positions","p":"momenta","Delta_tau":"learned stride"},"evidence":"paper.pdf pp. 2–5, problem definition and Figure 1","interpretation":"Distributional fidelity must be validated because chaotic trajectories cannot generally be pointwise shadowed at long horizons."}],
     ["paper.pdf pp. 2–7: direct-propagator theory and architecture","paper.pdf pp. 7–8, Figure 2 and Table 1: water equilibrium observables","paper.pdf pp. 8–9, Figure 3: universal case studies","paper.pdf pp. 24–31: uncertainty, energy, timing and Lyapunov checks","source PDF SHA-256 4834d435bf449c44ba5ccde36c6a2613ce5ba967e5b26d77f07194eb6db07368","Evidence status: full-text verified theory/numerical study; no independent reproduction performed."]),

card("doi-10.52202-085713-3124", "arXiv v3 manuscript", "https://arxiv.org/pdf/2505.22159",
     "ForceVLA: Enhancing VLA Models with a Force-aware MoE for Contact-rich Manipulation", "ForceVLA：用力感知混合专家增强接触丰富操作的VLA模型",
     "ai_empirical", "ccc9f854bd3d158f", "Robotics",
     {"doi":"10.52202/085713-3124","arxiv_id":"2505.22159","version":"arXiv v3 full text","title":"ForceVLA: Enhancing VLA Models with a Force-aware MoE for Contact-rich Manipulation","authors":["Jiawen Yu","Hairuo Liu","Qiaojun Yu","Jieji Ren","Ce Hao","Haitong Ding","Guangyu Huang","Guofan Huang","Yan Song","Panpan Cai","Cewu Lu","Wenqiang Zhang"],"journal":"Advances in Neural Information Processing Systems","volume":"38","pages":"103609–103639","published":"2025","abstract":"A force-aware mixture-of-experts fuses six-axis force feedback after visual-language encoding for five real contact-rich manipulation tasks.","comment":"ArXiv v3 full text cross-checked with NeurIPS proceedings metadata"},
     [sec("作者信息", "作者 Jiawen Yu、Hairuo Liu、Qiaojun Yu 等；NeurIPS 2025，DOI:10.52202/085713-3124。核验 arXiv:2505.22159v3 全文20页、实验appendix与项目声明。"),
      sec("研究问题", "VLA policy依赖视觉和语言，在插接、擦拭、剥皮等接触任务中会因遮挡、初始误差和物体移动而持续执行错误动作。论文问：把6轴force–torque作为一等模态，并用Mixture-of-Experts在action decoding阶段动态融合，能否比无力觉或简单拼接更可靠？"),
      sec("背景", "ForceVLA建立在π0 action-flow框架：SigLIP/PaliGemma式VLM编码多视角图像与instruction，proprioception和noisy action chunks参与迭代denoising。FVLMoE把force投影为tokens，经多个experts与gate生成与action horizon对齐的融合guidance。", "力信号来自腕部sensor，不是皮肤触觉；外部force包含接触、重力、惯性和校准误差。late fusion保持pretrained VLM分布，但性能归因还同时受新数据、模型容量和训练协议影响。"),
      sec("模型与方法", "ForceVLA-Data由5名operators在Flexiv Rizon 7-DOF robot上遥操作采集，共244 trajectories、约140k同步timesteps，覆盖USB/plug insertion、bottle pumping、whiteboard wiping和cucumber peeling；每任务约50 demonstrations。", "主实验各插接/按压任务20 trials，较复杂任务10 trials，报告success rate；剥皮另报每stroke长度与清洁所需strokes。基线为π0-base/π0-fast有无raw force，以及early/late fusion ablations；另测新object、高度、遮挡和unstable socket。"),
      sec("核心结果与证据", "Figure 5报告ForceVLA五任务平均success 60.5%，相对π0-base without force的37.3%提高23.2个百分点；plug insertion达80%。不同任务样本仅10–20 trials，柱高是有限频率估计，正文未给完整置信区间。", "raw force令π0-base仅从37.3%到40.2%，而FVLMoE达60.5%，支持‘融合方式重要’。剥皮平均每stroke 14.12 cm、最少7 strokes，优于表中基线；这些指标同时依赖工具、黄瓜与operator demonstrations。", "Table 2中ForceVLA在object、height、occlusion和unstable-socket variants总体领先，visual occlusion为90%；Figure 7展示失败后重定向/重抓。案例轨迹说明适应行为，但不能单独证明gate因果或大范围泛化。"),
      sec("有效性与局限", "仅一个robot platform、五个任务、244 demonstrations和有限trials；任务成功判据人工定义。测试variants仍接近训练装置，不包含跨robot、长期sensor drift、未知工具、危险碰撞或高速动态接触。", "MoE routing可视化显示phase差异但expert不必对应唯一物理技能。无force baseline可能因数据和training budget配置受限；23.2是百分点而非相对百分比。公开资源在稿中表述为将发布，应按实际仓库状态核验。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2505.22159；项目：https://sites.google.com/view/forcevla2025。PDF SHA-256：1327311916c59b84a866b2b2fd5849bd27bbbf68ccebe302560abfcb9e52e3ca。", "复现需固定robot/sensor calibration、camera poses、244-trajectory split、π0 checkpoint、force normalization、MoE experts/gate、action horizon、success criteria和逐trial视频。Evidence status: full-text verified real-robot study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.2–4 Figures 1–3理解failure与fusion位置；pp.6–7 Figures 4–5看任务和主结果，pp.8–9看generalization、ablation和trajectories；pp.13–20核对采集装置、routing及视频帧。")],
     "figure-5-success-rates.webp","Figure 5",7,"comparison","ForceVLA与π0-base/fast有无force的五任务success rates及平均值。","FVLMoE late fusion在该robot数据集上显著高于无force和简单force输入基线。","Figure 5直接展示主要23.2个百分点增益及任务间差异。",
     [{"label":"Force-aware expert fusion","latex":r"g=\mathrm{softmax}(W_g h_f),\qquad h_{\rm fuse}=\sum_e g_eE_e(h_{vl},h_f)","role":"route visual-language and force features through specialized experts","symbols":{"h_f":"force tokens","h_vl":"visual-language embeddings","g":"expert routing weights"},"evidence":"paper.pdf pp. 4–5, FVLMoE formulation","interpretation":"Routing specialization is learned from this dataset and does not guarantee physical semantics for each expert."}],
     ["paper.pdf pp. 3–5, Figures 2–3: problem and FVLMoE","paper.pdf pp. 6–7, Figures 4–5 and Table 1: tasks and main results","paper.pdf pp. 8–9, Tables 2–3 and Figure 7: generalization and ablations","paper.pdf pp. 13–20: data system, routing and video frames","source PDF SHA-256 1327311916c59b84a866b2b2fd5849bd27bbbf68ccebe302560abfcb9e52e3ca","Evidence status: full-text verified real-robot study; no independent reproduction performed."]),

card("doi-10.52202-085713-4294", "arXiv v1 manuscript", "https://arxiv.org/pdf/2510.16675",
     "Infinite Neural Operators: Gaussian processes on functions", "无限宽神经算子：函数上的高斯过程",
     "theory_numerics", "065095b8e507c6a1", "Neural Operators",
     {"doi":"10.52202/085713-4294","arxiv_id":"2510.16675","version":"arXiv v1 full text","title":"Infinite Neural Operators: Gaussian processes on functions","authors":["Daniel Augusto de Souza","Yuchen Zhu","Harry Jake Cunningham","Yuri Saporito","Diego Mesquita","Marc Peter Deisenroth"],"journal":"Advances in Neural Information Processing Systems","volume":"38","pages":"143033–143061","published":"2025","abstract":"Under Hilbert-space regularity assumptions, arbitrary-depth neural operators with Gaussian convolution kernels converge at infinite channel width to function-valued Gaussian processes.","comment":"ArXiv v1 full text cross-checked with NeurIPS proceedings metadata"},
     [sec("作者信息", "作者 Daniel Augusto de Souza、Yuchen Zhu、Harry Jake Cunningham、Yuri Saporito、Diego Mesquita、Marc Peter Deisenroth；NeurIPS 2025，DOI:10.52202/085713-4294。核验 arXiv:2510.16675v1 全文22页与公开实现。"),
      sec("研究问题", "宽度趋于无穷的普通NN常收敛为GP，但neural operator的输入输出本身是函数，卷积kernel也是随机函数。论文问：在什么空间与正则条件下，任意深度NO的通道极限是function-valued Gaussian element；如何递推其covariance，并为FNO构造可用于Bayesian regression的∞-FNO？"),
      sec("背景", "NO层将pointwise linear map与kernel integral operator相加后施加activation。证明需在L2或合适RKHS中控制随机函数的可测性、二阶矩与连续性；只有有限维分布高斯还不够，必须证明function space中的tightness/convergence。", "infinite width描述随机初始化prior和Bayesian posterior kernel method，不等同于有限FNO经gradient descent后的feature learning。"),
      sec("模型与方法", "作者逐层令channel widths趋于无穷，用Hilbert-space central-limit arguments证明输出收敛到function-valued GP，并给出跨输入函数与空间位置的covariance recursion。对FNO，Fourier truncation把随机spectral convolution转为可计算kernel。", "进一步提出Matérn-GP distributed integral kernels，引入可调smoothness/band-limit inductive bias；用Monte Carlo宽度扫描验证prior covariance，再在synthetic band-limited operator和1D Burgers终态预测上做GP posterior regression。"),
      sec("核心结果与证据", "Theorem 3.1在Gaussian independent kernels、有限moments及activation regularity等条件下给arbitrary-depth NO的iterated infinite-channel limit。结论是函数值GP，不只是每个grid point独立Gaussian；covariance保留输入函数与domain位置关系。", "Figures 1–2显示随width增大，有限NO输出分布和Monte Carlo variance趋近解析∞-NO。Figure 3在synthetic与Burgers回归中比较有限FNO和∞-FNO；正确band-limit通常较好，而band-limit超过ground truth会使synthetic误差恶化。", "∞-FNO posterior提供Bayesian mean/variance，但Figure 3也显示有限FNO与∞模型性能并不逐点一致，因为前者以Adam最小化empirical risk，后者做kernel Bayesian inference。"),
      sec("有效性与局限", "证明采用iterated width limits和指定Gaussian priors，不覆盖任意joint scaling、trained weights或非满足regularity的activation/kernel。FNO truncation与周期flat torus设定简化domain；复杂边界、irregular mesh及高维PDE需扩展。", "实验只有一个synthetic operator与下采样Burgers数据（100 functions、grid 103），主要验证理论而非SOTA PDE benchmark。GP posterior随训练函数数增长有立方代价，infinite-width不等于计算免费。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2510.16675；代码：https://github.com/spectraldani/infinite-neural-operator。PDF SHA-256：7813bda3e8d1b65cb74f1ae20d72c688ba1e485b77bf85faa5c6847c8c2af2d8。", "复现需固定function space、measure、Fourier band-limit B、width J、prior variance、Monte Carlo draws、Burgers subset、five-fold CV和optimizer。Evidence status: full-text verified theory/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.2–4 operator与Hilbert-space定义；pp.4–7看main theorem和covariance recursion。pp.8–9 Figures 1–3是数值核验，pp.13–22查完整assumptions/proofs与实验构造。")],
     "figure-3-regression-width.webp","Figure 3",9,"comparison","synthetic operator和1D Burgers上有限FNO与∞-FNO随width/band-limit的test L2 error。","无限宽kernel与有限训练网络反映相同band-limit归纳偏置，但预测性能并不等价。","Figure 3直接展示理论极限的回归用途及band-limit错配的失败模式。",
     [{"label":"Kernel integral operator","latex":r"\mathcal A_K[f](y)=\int_XK(y,x)f(x)\,d\mu_X(x)","role":"aggregate a function over its domain in a neural-operator layer","symbols":{"K":"matrix-valued random kernel","f":"input function","mu_X":"domain measure"},"evidence":"paper.pdf p. 2, Eq. (1)","interpretation":"Existence and GP convergence require the paper's integrability and regularity assumptions."}],
     ["paper.pdf pp. 2–4: operator and function-space setup","paper.pdf pp. 4–7: GP convergence theorem and covariance recursion","paper.pdf pp. 8–9, Figures 1–3: finite-width and regression checks","paper.pdf pp. 13–22: assumptions, proofs and experiments","source PDF SHA-256 7813bda3e8d1b65cb74f1ae20d72c688ba1e485b77bf85faa5c6847c8c2af2d8","Evidence status: full-text verified theory/numerical study; no independent reproduction performed."]),

card("record-003336f09dcac84a", "arXiv v2 manuscript", "https://arxiv.org/pdf/0910.5707",
     "The kinetic regime of the Vicsek model", "Vicsek模型的动力学弛豫区间",
     "theory_numerics", "003336f09dcac84a", "Active Matter",
     {"doi":"10.1063/1.3284421","arxiv_id":"0910.5707","version":"arXiv v2 full text","title":"The kinetic regime of the Vicsek model","authors":["A. A. Chepizhko","V. L. Kulinskii"],"journal":"AIP Conference Proceedings","volume":"1198","pages":"25–33","published":"2009","abstract":"A continuum-time Vicsek approximation separates fast single-particle alignment from slow hydrodynamic evolution and links low-speed ordering to Kuramoto synchronization.","comment":"ArXiv v2 author list used; Crossref metadata incorrectly mixes proceedings editors into the author array"},
     [sec("作者信息", "论文作者 A. A. Chepizhko、V. L. Kulinskii；AIP Conference Proceedings 1198, 25–33 (2009)，DOI:10.1063/1.3284421。核验 arXiv:0910.5707v2 全文8页；Crossref author数组混入多名proceedings editors，本卡按PDF标题页保留两位论文作者。"),
      sec("研究问题", "离散Vicsek update令粒子下一步方向瞬间等于邻域平均方向，掩盖局域弛豫时间。论文问：continuum-time analog如何分解fast kinetic alignment与slow hydrodynamic rotation；弛豫率怎样依赖邻居数/密度；scalar与vector noise为何给出不同的order-parameter transition形状？"),
      sec("背景", "固定速率粒子的局域平均方向ui由interaction radius R内速度和归一化得到。连续化后粒子angular velocity含ui自身慢旋转ωu和相对对齐A vi×ui两部分；前者描述domain间hydrodynamics，后者在局域方向近似冻结时给单粒子不可逆弛豫。", "模型是mean-field-like continuum approximation，不是从离散Vicsek链严格取极限；文中也指出低密度binary-collision kinetic theory未必适用于多粒子邻域update。"),
      sec("模型与方法", "二维时relative angle α满足αdot=−A sinα；加入scalar white noise得到Fokker–Planck方程，stationary distribution为von-Mises型exp[(λu/D)cosα]，并假设A=λu、λ=ρr²。模拟N=900、L=30、v=0.1估计log tan(α/2)斜率。", "动态邻域用Poisson neighbor count与characteristic functions构造self-consistency。vector noise则把随机向量加到local order parameter，推导非线性one-particle distribution与mean-field order equation。"),
      sec("核心结果与证据", "Figure 1显示kinetic interval内log tan(α/2)近线性，支持指数alignment；Figure 2把拟合relaxation rate A对λ作图，在所测低/中邻居数近似线性，支撑A≈λu。散点在小λ明显，不能视为精确law。", "零速度下angle equation与short-range Kuramoto形式相近，作者据此把低速度ordering联系到synchronization并预期continuous transition；这是机制类比和mean-field推断，不是critical exponent证明。", "scalar-noise self-consistency给supercritical onset；vector-noise方程在一段noise interval存在多解并产生subcritical/apparent discontinuity，Figure 4示意该bifurcation。该解释针对特定noise injection和mean-field closure。"),
      sec("有效性与局限", "会议论文篇幅短，simulation规模单一、无systematic finite-size scaling或error bars；A与λ线性只称在邻居数不太大时成立。连续化参数A的微观标定与离散time step关系未严格给出。", "density–velocity correlations经近似closure处理，动态邻域用Poisson分布；bands、giant density fluctuations和long-wavelength Toner–Tu modes不在验证范围。scalar/vector noise transition后来有更细致finite-size与banding研究，本卡不把早期mean-field结论当作最终共识。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/0910.5707；期刊：https://doi.org/10.1063/1.3284421。PDF SHA-256：277b85c7eb62883264e12770bc86dcaaef1a684c65b3f23f435b2bea130ab7b7。未给代码仓库。", "复现需固定N=900、L=30、v=0.1、R/λ扫描、initial angles、noise convention、kinetic fitting window与neighbor update；应增加seeds和finite-size tests。Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 Eqs. (1)–(13)看continuous-time与两尺度；pp.4–5 Figures 1–2看relaxation fit，pp.5–6看dynamic-neighborhood closure；pp.6–8比较scalar/vector noise与Figure 4。")],
     "figure-2-relaxation-density.webp","Figure 2",5,"data_plot","Vicsek模拟中局域对齐弛豫率A随平均邻居数λ=ρr²的散点与线性趋势。","在该有限模拟的kinetic interval内，对齐率随局域邻居数近似线性增长。","Figure 2直接检验论文用于Fokker–Planck closure的A≈λu假设，同时保留散点偏差。",
     [{"label":"Noisy angular relaxation","latex":r"\dot\alpha=-A\sin\alpha+L(t),\qquad \partial_tf=\partial_\alpha(A\sin\alpha\,f)+D\partial_\alpha^2f","role":"describe fast alignment to a slowly varying neighborhood direction","symbols":{"alpha":"particle-to-neighborhood angle","A":"relaxation rate","D":"angular diffusion"},"evidence":"paper.pdf p. 4, Eqs. (14)–(16)","interpretation":"The closure A=λu is empirical/mean-field and is supported only over the simulated range."}],
     ["paper.pdf pp. 1–3, Eqs. (1)–(13): continuum-time decomposition","paper.pdf pp. 4–5, Figures 1–2: kinetic relaxation and density scaling","paper.pdf pp. 5–6, Figure 3: dynamic-neighborhood mean field","paper.pdf pp. 6–8, Figure 4: scalar versus vector noise","source PDF SHA-256 277b85c7eb62883264e12770bc86dcaaef1a684c65b3f23f435b2bea130ab7b7","Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."])
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids=[]
    for item in CARDS:
        pid=str(item["arxiv_id"]); (OUT/f"{pid}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); ids.append(pid)
    print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__ == "__main__": raise SystemExit(main())
