#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 030."""

from __future__ import annotations

import json
from pathlib import Path

from install_full_collection_batch_014 import figure, provenance, sec

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"


CARDS: list[dict[str, object]] = [
    {
        "arxiv_id": "doi-10.1038-s41467-021-26434-1", "source_version": "version of record",
        "source_pdf": "https://www.nature.com/articles/s41467-021-26434-1.pdf",
        "title_en": "Physics-informed learning of governing equations from scarce data", "title_zh": "从稀缺数据中物理信息驱动地学习控制方程",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "ai_empirical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["3418e7b2e0b58e2b"], ["AI for Science"]),
        "verified_metadata": {"doi": "10.1038/s41467-021-26434-1", "version": "version of record", "title": "Physics-informed learning of governing equations from scarce data", "authors": ["Zhao Chen", "Yang Liu", "Hao Sun"], "journal": "Nature Communications", "volume": "12", "article": "6136", "published": "2021-10-21", "abstract": "PINN-SR combines neural field reconstruction, automatic differentiation and sparse regression to identify PDEs from scarce noisy measurements across initial and boundary conditions.", "comment": "Open-access version of record; no Crossref update notice found"},
        "sections": [
            sec("作者信息", r"作者 Zhao Chen、Yang Liu、Hao Sun；Nature Communications 12, 6136 (2021)，DOI:10.1038/s41467-021-26434-1，发表于 2021-10-21。核验 13 页开放期刊版、Crossref 元数据和代码/数据声明；未发现关联更正或撤稿通知。"),
            sec("研究问题", r"PDE-FIND/SINDy 一类方法需要从测量数据数值求导，数据稀疏且含噪时容易放大误差；纯神经网络又可能只能给黑箱演化。论文问：能否用神经网络连续重构场和自动微分得到导数，同时用稀疏回归选择少量候选项，从单个或多个初/边值条件下的稀缺观测恢复可解释的闭式 PDE？"),
            sec("背景", r"作者假设未知动力学可写为 u_t=ϕ(u,∂u,…)Λ，且真实方程在预设候选库中是稀疏的。PINN 在无标签 collocation points 上约束 PDE residual，测量点只负责数据拟合；不同初/边值条件使用共享 root、独立 branch 的网络，最终拼接候选库并寻找共同 Λ。", r"Figure 5 是真实 scratch-assay 例子：14k–20k 初始细胞的密度数据只有 0、12、24、36、48 h，算法保留扩散、ρ 和 ρ² 三项，并用识别方程模拟后续密度。"),
            sec("模型与方法", r"总损失由数据误差 Ld、残差物理误差 αLp 和 β||Λ||0 组成。由于 ℓ0 优化为组合问题，作者先以 ℓ1 预训练，再交替更新神经网络参数 θ 与稀疏系数 Λ：STRidge/hard thresholding 选择项，固定结构后 post-training 校准系数。自动微分避免直接对噪声数据做有限差分，但导数仍来自网络近似。", r"数值基准包括 Burgers、Kuramoto–Sivashinsky、非线性 Schrödinger、Navier–Stokes、λ–ω reaction–diffusion 与多初值 FitzHugh–Nagumo。实验例子提前施加扩散—反应先验 ρ_t=γρ_xx+F(ρ)，只在九项库中选择 F；因此它不是从任意 PDE 空间无先验发现。"),
            sec("核心结果与证据", r"Table 1 报告五个单数据集基准在 10% Gaussian noise 下，已识别非零系数相对误差约 0.08%–1.84%；采样比例依问题从 0.22% 到 37.5%。Burgers 例用 3.19% 网格点、10% 噪声，系数误差约 0.88%，full-field ℓ2 误差 1.32%。这些是已知真值的合成基准，不是一般误差保证。", r"多初值 FitzHugh–Nagumo 例恢复正确 active terms，未测时刻 stacked full-field ℓ2 error 为 5.02%；一个 diffusion coefficient 较不敏感。Figure 5 中四组细胞数据均得到 Fisher–Kolmogorov 形式 ρ_t=γρ_xx+λ1ρ+λ2ρ²，模拟曲线与 12–48 h 测量总体一致。", r"实验识别使用三个相同制备的 replicate 平均值和明确的 diffusion–reaction library。它支持在该先验与数据处理下恢复可预测的稀疏模型，但不证明该 PDE 是细胞迁移/增殖的唯一微观机制。"),
            sec("有效性与局限", r"候选库必须预先包含正确项；过大库增加共线性和优化困难，遗漏项则无法被发现。当前版本不能处理时空变化的系数。全连接 PINN 对三维域、尖锐波前和混沌场需要大量 collocation points，计算成本显著高于 SINDy，root–branch 结构也随独立数据集数量近线性扩张。", r"稀疏/噪声场重构的 wave-front error 会传递到系数；阈值、正则权重与传感器位置需调参。实验例的方程结构受领域先验限制，且没有独立实验、外部数据集或因果扰动验证。"),
            sec("复现与资源", r"期刊：https://doi.org/10.1038/s41467-021-26434-1；代码与数据：https://github.com/isds-neu/EQDiscovery。核验 PDF SHA-256：8e01d81c5cac6a7f0feec06bf5ae548595e5b6fa5fdac5783c93ec974482dca9。复现需固定候选库、采样点/噪声定义、网络宽深、activation、collocation points、α/β、ℓ1 预训练、STRidge threshold、ADO cycles、随机种子和重复次数。", r"细胞例还需保留三 replicate 平均、初值、Neumann boundary、密度单位和 segmentation 流程。Evidence status: full-text verified version of record; no independent reproduction performed."),
            sec("阅读指南", r"先读 pp.2–4 的 Eqs. (1)–(3) 与 Figure 1，确认“physics-informed”指候选 PDE residual。再读 pp.4–8 的合成基准及 Table 1；核心实验看 p.9 Figure 5。最后精读 pp.9–10 Discussion，把已知库内结构恢复与无约束物理定律发现区分开。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/doi-10.1038-s41467-021-26434-1/figure-5-cell-pde.webp", "label": "Figure 5", "visual_type": "comparison", "evidence": "paper.pdf p. 9, Figure 5", "alt_text": "不同初始细胞数下稀疏系数、识别 PDE 与细胞密度预测的对照。", "caption": "PINN-SR 从 scratch-assay 数据选择扩散、线性和二次反应项，并比较预测与测量。", "selection_rationale": "Figure 5 是全文唯一真实实验发现案例，同时显示结构选择、参数变化和外推拟合。"},
        "figure_refs": [figure("doi-10.1038-s41467-021-26434-1", "figure-5-cell-pde.webp", "Figure 5", 9, "show experimental PDE discovery for cell assays", "四个初始细胞数下的系数和密度曲线。", "识别结构与 Fisher–Kolmogorov 形式一致。", "The candidate library already encodes a diffusion–reaction prior and does not establish uniqueness.")],
        "equation_refs": [
            {"label": "Sparse PDE representation", "latex": r"u_t=\phi\Lambda", "role": "represent an unknown PDE with a candidate library and sparse coefficients", "symbols": {"phi": "candidate terms from the neural field and derivatives", "Lambda": "sparse coefficient matrix"}, "evidence": "paper.pdf p. 3, Eq. (2)", "interpretation": "Equation discovery becomes support selection inside a predefined function library."},
            {"label": "PINN-SR objective", "latex": r"\mathcal L=L_d+\alpha L_p+\beta\|\Lambda\|_0", "role": "balance measurement fit, PDE residual and sparsity", "symbols": {"L_d": "data loss", "L_p": "collocation residual loss", "alpha_beta": "loss weights"}, "evidence": "paper.pdf p. 3, Eq. (3)", "interpretation": "Alternating optimization is required because the exact sparsity term is not handled by ordinary gradient descent."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–4: PINN-SR formulation and Figure 1", "paper.pdf pp. 4–8: synthetic benchmarks, Table 1 and multi-I/BC tests", "paper.pdf p. 9, Figure 5: experimental cell-density discovery", "paper.pdf pp. 9–10: computational, library and variable-coefficient limitations", "source PDF SHA-256 8e01d81c5cac6a7f0feec06bf5ae548595e5b6fa5fdac5783c93ec974482dca9", "Evidence status: full-text verified version of record; no independent reproduction performed."],
    },
    {
        "arxiv_id": "doi-10.1038-s41467-023-36563-4", "source_version": "version of record", "source_pdf": "https://www.nature.com/articles/s41467-023-36563-4.pdf",
        "title_en": "Diverse behaviors in non-uniform chiral and non-chiral swarmalators", "title_zh": "非均匀手性与非手性 swarmalators 的多样行为",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "numerical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["29b449105ddea6a8"], ["Active Matter"]),
        "verified_metadata": {"doi": "10.1038/s41467-023-36563-4", "version": "version of record", "title": "Diverse behaviors in non-uniform chiral and non-chiral swarmalators", "authors": ["Steven Ceron", "Kevin O’Keeffe", "Kirstin Petersen"], "journal": "Nature Communications", "volume": "14", "article": "940", "published": "2023-02-20", "abstract": "A locally coupled swarmalator model with heterogeneous natural frequencies and chirality produces phase waves, bouncing clusters, radial oscillations and vortex arrays.", "comment": "Open-access version of record; no Crossref update notice found"},
        "sections": [
            sec("作者信息", r"作者 Steven Ceron、Kevin O’Keeffe、Kirstin Petersen；Nature Communications 14, 940 (2023)，DOI:10.1038/s41467-023-36563-4，发表于 2023-02-20。核验 13 页开放期刊版、Zenodo 数据/代码声明和 Crossref 状态；未发现关联更正或撤稿通知。"),
            sec("研究问题", r"经典 swarmalator 模型把空间聚集与 Kuramoto 相位同步耦合，但常假设全局耦合、相同频率和无手性。论文问：加入有限感知半径、自然频率分布以及相位与圆周运动方向相联的 chirality 后，会出现哪些稳态或动态集体态；少量全局参数能否在同一模型中切换 phase waves、clusters、径向振荡和 vortex arrays？"),
            sec("背景", r"每个 agent 有二维位置 x_i 和内部相位 θ_i。空间方程包含固有圆周速度、相位依赖吸引和短程排斥；相位方程为距离加权的 Kuramoto coupling。作者设置 F1 单频、F2 正负双频，以及 F3/F4 单/双均匀频率分布，并以 c_i=ω_iR_i 把频率符号映射成顺/逆时针运动。", r"Figure 2 在 K–J 平面展示非手性 F1/F2 的 order-parameter heat maps 与代表态，包括传播 phase wave、bouncing clusters、anti-phase、synchronized expansion 和 radial oscillation。"),
            sec("模型与方法", r"全局模型的吸引强度为 A+J cos(θ_j−θ_i−Q_x)，排斥随距离平方反比；相位耦合强度 K 也按距离衰减。局部模型再乘有限半径 σ 的 Heaviside step function，并加位置/相位噪声。主要扫描 J∈[−1,1]、K∈[−1,2]。", r"数值使用 Matlab Euler integration；正文非手性扫描常用 N=500、dt=0.1、T=1000，S heat maps 为 10 次 trial。相态通过 space–phase order S、Kuramoto order Z、完成旋转比例 γ、群体分离 β 等量分类；边界多为图上近似区域而非解析 bifurcation curves。"),
            sec("核心结果与证据", r"非手性系统即使没有固有空间运动，也因频率异质与相位依赖吸引产生 traveling/interacting phase waves、bouncing clusters、static anti-phase、同步膨胀和周期径向振荡。F2 的正负频率群分别同步但相对相位周期变化，从而交替吸引和排斥。", r"手性模型进一步产生单/多 vortex、double phase waves、revolving clusters 和 lattice-like structures；局部耦合半径改变相位相关与径向 pair correlation。Figure 2 的地图是有限步长、有限 N 数值观察；作者没有给所有态的稳定性证明或状态转移穷举。", r"Figure 8/9 把若干模拟形态与 slime mold、磁胶体、Quincke rollers 和 sperm vortices 并列。作者明确称这些为 qualitative resemblance：模型没有复现具体 hydrodynamic/mechanical coupling，部分磁胶体 crystal-like locking 也无法准确再现。因此这些图是启发性结构类比，不是实验拟合或物理等价。"),
            sec("有效性与局限", r"工作是确定性/加噪 toy-model 数值探索，没有实验参数反演。相态依赖 N、dt、积分时间、初值、σ、频率分布和经验 order-parameter threshold；Euler 收敛与系统尺寸标度未在正文系统展示。局部耦合用硬 step cutoff，真实感知或流体耦合通常连续且各向异性。", r"作者承认未穷举 state transitions，高频率 dispersion 下 clusters 更难形成。真实系统相似性只到形态/轨迹层面，缺少速度、作用核、噪声、守恒量和时间尺度的定量映射；不能据此宣称同一机制。"),
            sec("复现与资源", r"期刊：https://doi.org/10.1038/s41467-023-36563-4；数据与代码：https://doi.org/10.5281/zenodo.7554900。核验 PDF SHA-256：29b449105ddea6a80d49e2463284fbe7eb288f38cf149aabd0181f7ad69ecf07。复现需固定 N、dt、T、初值、A/B、K/J grid、σ、frequency distribution、chirality mapping、offset terms、噪声强度、transient cut 和每个 order parameter。", r"应做步长、系统尺寸、随机初值和相边界敏感性检查，并把未公开的大体量数据请求状态记录下来。Evidence status: full-text verified version-of-record numerics; no independent reproduction performed."),
            sec("阅读指南", r"先读 pp.2–3 的 Eqs. (1)–(7)，明确空间、相位和 chirality 的映射；再看 p.4 Figure 2 建立非手性相态词典。随后读 pp.6–8 的手性/局部耦合，最后读 pp.9–10 的真实系统类比，并把“qualitatively resembles”保留为最低证据等级。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/doi-10.1038-s41467-023-36563-4/figure-2-state-map.webp", "label": "Figure 2", "visual_type": "phase_diagram", "evidence": "paper.pdf p. 4, Figure 2", "alt_text": "非手性 swarmalator 在 K–J 平面中的相态图和代表结构。", "caption": "自然频率异质性把同步/phase-wave 图景扩展为 bouncing clusters、anti-phase 与 radial oscillation。", "selection_rationale": "Figure 2 直接给出模型参数、order parameter 和多种新状态的对应关系，是全文数值分类的入口。"},
        "figure_refs": [figure("doi-10.1038-s41467-023-36563-4", "figure-2-state-map.webp", "Figure 2", 4, "map non-chiral swarmalator states", "F1/F2 下 S(K,J) 与代表性动态图样。", "频率异质性产生 bouncing、anti-phase 和径向振荡区。", "Boundaries are empirical finite-simulation classifications, not analytic phase-transition curves.")],
        "equation_refs": [
            {"label": "Swarmalator position dynamics", "latex": r"\dot{\mathbf x}_i=\mathbf v_i+\frac1N\sum_{j\ne i}\left[\frac{\mathbf x_j-\mathbf x_i}{|\mathbf x_j-\mathbf x_i|}(A+J\cos(\theta_j-\theta_i-Q_x))-B\frac{\mathbf x_j-\mathbf x_i}{|\mathbf x_j-\mathbf x_i|^2}\right]", "role": "couple phase-dependent attraction, repulsion and intrinsic motion", "symbols": {"J": "space–phase coupling", "v_i": "chiral intrinsic velocity", "A_B": "attraction and repulsion scales"}, "evidence": "paper.pdf p. 2, Eq. (1)", "interpretation": "Changing phase relationships changes who attracts whom in physical space."},
            {"label": "Space–phase order", "latex": r"S_\pm=\left|N^{-1}\sum_j e^{i(\phi_j\pm\theta_j)}\right|", "role": "measure circumferential correlation between position and phase", "symbols": {"phi_j": "angular position about the centroid", "theta_j": "internal phase"}, "evidence": "paper.pdf p. 3, Eq. (7)", "interpretation": "The heat maps classify organization but do not alone distinguish every dynamic state."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–3: Eqs. (1)–(7), frequency and chirality definitions", "paper.pdf p. 4, Figure 2: non-chiral state map", "paper.pdf pp. 6–9: chiral/local-coupling simulations and correlations", "paper.pdf pp. 9–10: qualitative real-system parallels and discussion", "source PDF SHA-256 29b449105ddea6a80d49e2463284fbe7eb288f38cf149aabd0181f7ad69ecf07", "Evidence status: full-text verified numerical model; no independent reproduction performed."],
    },
    {
        "arxiv_id": "doi-10.1038-s41467-023-42633-4", "source_version": "version of record", "source_pdf": "https://www.nature.com/articles/s41467-023-42633-4.pdf",
        "title_en": "Spontaneous shock waves in pulse-stimulated flocks of Quincke rollers", "title_zh": "脉冲激励 Quincke 滚子群中的自发冲击波",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "theory_experiment", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["5e3bfc21bacde26a"], ["Active Matter"]),
        "verified_metadata": {"doi": "10.1038/s41467-023-42633-4", "version": "version of record", "title": "Spontaneous shock waves in pulse-stimulated flocks of Quincke rollers", "authors": ["Bo Zhang", "Andreas Glatz", "Igor S. Aranson", "Alexey Snezhko"], "journal": "Nature Communications", "volume": "14", "article": "7050", "published": "2023-11-03", "abstract": "Pulsed electric fields generate transient shock waves in Quincke rollers near the gas–vortex transition, reproduced by a shallow-water continuum model.", "comment": "Open-access version of record; no Crossref update notice found"},
        "sections": [
            sec("作者信息", r"作者 Bo Zhang、Andreas Glatz、Igor S. Aranson、Alexey Snezhko；Nature Communications 14, 7050 (2023)，DOI:10.1038/s41467-023-42633-4，发表于 2023-11-03。核验 8 页开放期刊版、Source Data/代码声明和 Crossref 状态。"),
            sec("研究问题", r"连续直流场下 Quincke rollers 可形成气体、flock 或 vortex。论文问：若以脉冲电场分别控制通电 τon 与断电 τoff，使平移和取向记忆具有可比分离时间，是否会出现没有固定边界支撑的瞬态密度冲击波；波前是普通 travelling band，还是由局域涡核失稳产生、传播速度超过粒子速度的新动态态？"),
            sec("背景", r"实验使用直径 4.8 μm 的 polystyrene spheres、AOT/hexadecane 弱导电液体和 95 μm 间隙 ITO cell。提高吸水量把 conductivity 调至 7.8×10^-8 S/m，增强 electrohydrodynamic flows；脉冲场幅固定为 3.2 V/μm。", r"Figure 1 在 τon–τoff 平面分出 clusters、gas、lattices、flocks、shock waves 和 vortices。Figure 2 连续快照显示少量高速粒子先聚成 transient vortex，随后因 meandering instability 展开为 spiral shock wave。"),
            sec("模型与方法", r"实验以 1057 fps 显微视频、Trackpy 和 particle-tracking velocimetry 得到速度/密度。Shock-wave regime 由速度 PDF 的第二峰和 |u|/|u0|>2 的快速粒子定义，并逐粒子跟踪波前通过前后的轨迹。", r"连续模型包含 roller density ρ、polarization/particle velocity u，以及 depth-averaged fluid velocity v 与高度 h；粒子方程有 convection、density-dependent pressure/alignment，流体用二维 shallow-water Navier–Stokes，并满足粒子和流体 continuity。脉冲记忆映射为平移/转动 diffusion 比 δ=D/Dr，数值用 Fourier quasi-spectral split-step。"),
            sec("核心结果与证据", r"Shock waves 位于 gas 与 global-vortex 之间的窄参数区。Figure 2 显示 0–0.1 s 内高速 aligned cluster 形成短寿命涡核，约 0.2 s 破裂为螺旋波、0.3 s 传播；多数初始 cluster 则直接消散。Figure 3 中单粒子速度最多升至基线约五倍并协同移动约 50 个粒径。", r"测得波速 u_wave=2.1 mm/s，比峰值粒子速度 1.5 mm/s 高约 40%，因此粒子不随波前等速平移。模型在 δ≈0.6–1.16 产生 waves；低于约 0.5 为均匀 gas，高于约 1.16 为单 vortex。Figure 4 的代表波速 0.97 比局部峰速 0.68 高 42%，与实验比例相近。", r"实验与连续模型共同支持“局域致密化→短寿命涡核→meandering→波前”的机制解释，但模型没有直接模拟三维 EHD flow，机制唯一性仍受 coarse-graining 限制。作者也区分 subcritical activity waves：本波在超阈值脉冲场和较稀 ϕ≈0.1 出现，而碰撞主导 activity waves 通常在 ϕ≈0.4。"),
            sec("有效性与局限", r"相图依赖特定粒径、溶剂含水/电导率、cell gap、面积分数 ϕ0=0.11、场幅和 pulse protocol；不能直接外推到其他 rollers 或三维体系。波是持续产生/消散的非稳态结构，不是 Burgers equation 的稳态 shock solution；与 Burgers 对流非线性的联系只是定性类比。", r"模型采用 quasi-2D shallow-water approximation，明确未包含垂直 3D electrohydrodynamic flows，且用 phenomenological pressure/interaction。边界碰撞也能制造局域热点。波速比较来自有限事件，需报告 event distribution 而非只用代表值。"),
            sec("复现与资源", r"期刊：https://doi.org/10.1038/s41467-023-42633-4；代码：https://github.com/activematerials/Shockwave_continuum；Source Data 随文章提供。核验 PDF SHA-256：4ca59b28a8f544b5fc0ee8f9fbba97e4ea29cc7f0bf85254329a34ffcd0ed81d。复现需固定 conductivity、humidity、AOT、gap、E、τon/τoff、ϕ、camera rate、tracking threshold 和 wave-speed estimator。", r"数值需固定 nondimensionalization、δ、pressure kernel、shallow-water parameters、domain/boundary、grid 和 spectral timestep。Evidence status: full-text verified experiment plus continuum simulation; no independent reproduction performed."),
            sec("阅读指南", r"先看 p.2 Figure 1 锁定实验参数区，再看 p.3 Figure 2 的事件序列和 p.4 Figure 3 的波速/粒子速度。p.5 Figure 4 是模型交叉验证；最后读 pp.5–6 Discussion/Methods，保留 quasi-2D、非稳态和 Burgers 仅定性类比三个边界。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/doi-10.1038-s41467-023-42633-4/figure-2-shock-emergence.webp", "label": "Figure 2", "visual_type": "real_space", "evidence": "paper.pdf p. 3, Figure 2", "alt_text": "高速 Quincke rollers 从局域簇形成涡核并展开为螺旋冲击波的快照。", "caption": "局域致密化先生成 transient vortex，随后 meandering instability 产生传播并消散的波前。", "selection_rationale": "Figure 2 直接逐时展示论文提出的冲击波生成机制，而非只给最终相图。"},
        "figure_refs": [figure("doi-10.1038-s41467-023-42633-4", "figure-2-shock-emergence.webp", "Figure 2", 3, "show spontaneous shock-wave nucleation", "0–0.3 s 的显微快照、速度方向和粒子轨迹。", "高速簇先成为 transient vortex，再破裂为 spiral wave。", "The sequence is a representative event; most small dynamic clusters dissipate without forming a wave.")],
        "equation_refs": [
            {"label": "Particle continuity", "latex": r"\partial_t\rho+\nabla\cdot(\rho\mathbf u)=0", "role": "conserve roller number in the continuum model", "symbols": {"rho": "coarse-grained roller density", "u": "roller velocity field"}, "evidence": "paper.pdf p. 6, Eq. (3)", "interpretation": "Density fronts arise from compressible particle transport even though the host fluid is treated separately."},
            {"label": "Fluid continuity", "latex": r"\partial_t h+\nabla\cdot(h\mathbf v)=0", "role": "evolve the depth-averaged host-fluid layer", "symbols": {"h": "fluid height", "v": "depth-averaged fluid velocity"}, "evidence": "paper.pdf p. 6, Eq. (4)", "interpretation": "The model retains in-plane hydrodynamic flow but omits the full three-dimensional velocity field."},
        ],
        "evidence_refs": ["paper.pdf p. 2, Figure 1: pulsed-field dynamic phase diagram", "paper.pdf p. 3, Figure 2: shock-wave nucleation sequence", "paper.pdf pp. 4–5, Figures 3–4: experimental and simulated wave speeds", "paper.pdf pp. 5–6: shallow-water limitations and model equations", "source PDF SHA-256 4ca59b28a8f544b5fc0ee8f9fbba97e4ea29cc7f0bf85254329a34ffcd0ed81d", "Evidence status: full-text verified experiment and simulation; no independent reproduction performed."],
    },
    {
        "arxiv_id": "doi-10.1038-s41467-024-50378-x", "source_version": "version of record", "source_pdf": "https://www.nature.com/articles/s41467-024-50378-x.pdf",
        "title_en": "Learning interpretable dynamics of stochastic complex systems from experimental data", "title_zh": "从实验数据学习随机复杂系统的可解释动力学",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "ai_empirical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["37ebcfc7f9e65194"], ["Complex Systems"]),
        "verified_metadata": {"doi": "10.1038/s41467-024-50378-x", "version": "version of record", "title": "Learning interpretable dynamics of stochastic complex systems from experimental data", "authors": ["Ting-Ting Gao", "Baruch Barzel", "Gang Yan"], "journal": "Nature Communications", "volume": "15", "article": "6029", "published": "2024-07-17", "abstract": "LaGNA separates self, interaction and diffusion terms of networked SDEs and applies symbolic sparsification to flocking and mouse tau-pathology data.", "comment": "Open-access version of record; no Crossref update notice found"},
        "sections": [
            sec("作者信息", r"作者 Ting-Ting Gao、Baruch Barzel、Gang Yan；Nature Communications 15, 6029 (2024)，DOI:10.1038/s41467-024-50378-x，发表于 2024-07-17。核验 10 页开放期刊版、Figshare/GitHub/Zenodo 声明和 Crossref 状态。"),
            sec("研究问题", r"网络化复杂系统既有节点自身动力学和邻接相互作用，也有状态依赖随机扩散。论文问：给定已知拓扑和节点活动序列，能否不预设具体 SDE 形式，先用 graph message passing 分离 self、interaction、diffusion 三个来源，再把每个神经模块压缩为可读的解析项；该方法在真实鸟群与 tau 病理数据上能否产生可预测的方程？"),
            sec("背景", r"目标 SDE 为 dx_i=[F(x_i)+Σ_jA_ijG(x_i,x_j)]dt+Φ(x_i)dW_t。普通 graph neural network 侧重预测，未必把随机扩散与确定性作用分离；常规 symbolic/SINDy 又难处理大网络和 intrinsic noise。LaGNA 第一阶段用三个网络分别估计 F、G、Φ 的 conditional Gaussian transition，第二阶段在各自候选库中做稀疏表达。", r"Figure 3 并列二阶 Vicsek 合成数据和四组 GPS pigeon flights：合成真值恢复几乎重合，真实 flock 的 inferred SDE 生成轨迹与 force field 与观测总体一致。"),
            sec("模型与方法", r"离散时间下 x_i(t+dt) 被建模为均值 μ_i=x_i+[f(x_i)+ΣA_ijg(x_i,x_j)]dt、方差由 ϕ²dt 给出的 Gaussian。message passing 按邻接聚合 interaction；negative log likelihood 同时训练三模块。随后把模块输出投影到预构造 elementary-function libraries，以 sparse regression 得到显式系数。", r"基准覆盖 signed/weighted networks 和多维、cross-dimensional diffusion，并与五种方法比较。鸟群数据来自四次 homing flights，GPS 原采样 0.2 s，经 spline 到 0.01、归一化、选择 collective 段和去除 outliers；第一群 8 只，另三群各 7 只。tau 数据为不同小鼠在 1/3/6/9 月 euthanized 后形成的 pseudo-longitudinal snapshots，160 brain regions 和 neuroanatomical/Euclidean networks。"),
            sec("核心结果与证据", r"合成系统中 LaGNA 恢复 self/interaction/diffusion force fields，并在作者选择的误差指标上优于五个比较方法。Figure 3 的二阶 Vicsek 测试中三类作用与真值 R²≈1，inferred stochastic trajectories 再现 flock；这是已知模型基准。", r"对第一组真实 pigeon data，识别式含 self-propulsion、distance-dependent cohesion、alignment 和 stochastic term，形式接近 second-order Vicsek model；固定方程形式、只微调 scaling coefficients 后也描述另三组飞行。它支持 Vicsek-like effective dynamics 与数据兼容，不证明个体鸟遵循唯一微观定律。", r"tau 例识别 initial retention、retrograde、anterograde、spatial diffusion 与 noise，预测 6/9 月 pathology；真实 injection seeds 在 500 组随机 seeds 中准确度最高。LRRK2G2019S mutant 使用同一形式但 retrograde coefficient 约 0.7–0.9、anterograde 约 0.1–0.3。结果依赖 pseudo-longitudinal aggregation、网络和阈值，不是单鼠纵向因果追踪。"),
            sec("有效性与局限", r"方法假设网络拓扑已知且节点序列可观察；缺失节点时所需最小 subnetwork 尚未解决。真实噪声混合 intrinsic dynamics 与 measurement noise，作者把全部噪声先视为 intrinsic；实验显示 extrinsic relative strength 低于约 10% 时较可靠，更强时需预处理，二者一般不可无先验区分。", r"第二阶段仍用预构造 library，可能遗漏真实项；同时学习大网络拓扑和动力学、higher-order interactions 都留待未来。pigeon 数据经过插值/归一化/筛选，tau 数据跨个体构造；预测成功和方程相似性不能替代干预、外部 cohort 和结构可识别性检验。"),
            sec("复现与资源", r"期刊：https://doi.org/10.1038/s41467-024-50378-x；代码：https://github.com/Ting-TingGao/Network-SDE-Inference；归档：https://doi.org/10.5281/zenodo.12112887；真实数据：https://doi.org/10.6084/m9.figshare.24804894.v4。PDF SHA-256：10396ed47a9c8b041f80c3131015ddf612a66011ac718329e7596f705098d16e。", r"复现需固定 topology、dt、trajectory segmentation、normalization、library、sparsity、likelihood、seed 和 splits；真实数据还需 outlier、pseudo-longitudinal 和 diffusion-threshold 规则。Evidence status: full-text verified version of record; no independent reproduction performed."),
            sec("阅读指南", r"先读 pp.2–3 Figure 1 与 Eqs. (1)–(2)，再读 p.4 synthetic benchmark。核心真实证据看 p.5 Figure 3 的 bird flocks 和 p.6 Figure 4 的 tau；最后读 p.7 Discussion 的四类限制。将“方程形式相似”“预测有效”和“机制被证明”严格分开。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/doi-10.1038-s41467-024-50378-x/figure-3-flock-inference.webp", "label": "Figure 3", "visual_type": "comparison", "evidence": "paper.pdf p. 5, Figure 3", "alt_text": "LaGNA 对二阶 Vicsek 合成数据和四组真实鸽群轨迹的动力学推断。", "caption": "合成基准恢复已知作用；真实 GPS 数据得到 Vicsek-like effective SDE 并生成相近轨迹。", "selection_rationale": "Figure 3 同时展示 ground-truth validation 与真实实验应用，最适合区分验证强度。"},
        "figure_refs": [figure("doi-10.1038-s41467-024-50378-x", "figure-3-flock-inference.webp", "Figure 3", 5, "compare inferred flock dynamics with synthetic truth and GPS data", "Vicsek 合成恢复与四组 empirical flock trajectories/force fields。", "识别 SDE 在数据处理后的鸟群轨迹上呈 Vicsek-like 结构。", "Agreement supports an effective description but does not establish a unique microscopic law.")],
        "equation_refs": [
            {"label": "Networked stochastic dynamics", "latex": r"d\mathbf x_i=\left[\mathbf F(\mathbf x_i)+\sum_jA_{ij}\mathbf G(\mathbf x_i,\mathbf x_j)\right]dt+\mathbf\Phi(\mathbf x_i)d\mathbf W_t", "role": "separate self, interaction and diffusion sources", "symbols": {"A": "known network", "F": "self dynamics", "G": "pair interaction", "Phi": "state-dependent diffusion"}, "evidence": "paper.pdf p. 7, Eq. (6); equivalent setup on p. 2, Eq. (1)", "interpretation": "LaGNA is structured around an additive source decomposition rather than an unconstrained black-box transition."},
            {"label": "Inferred flock equation", "latex": r"\dot{\mathbf v}_i=s_1(|\mathbf v_i|^2+s_2)+s_3+\sum_{j\ne i}[\widetilde C(r_{ij})\mathbf r_{ij}+\widetilde A(r_{ij})\mathbf v_{ij}]+\hat\epsilon\,d\mathbf W_t", "role": "give the effective empirical pigeon-flock SDE", "symbols": {"C_tilde": "cohesion function", "A_tilde": "alignment function", "epsilon_hat": "estimated stochasticity"}, "evidence": "paper.pdf p. 5, Eq. (4)", "interpretation": "Its resemblance to a second-order Vicsek model is an observational effective-model result."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–3: LaGNA pipeline and likelihood decomposition", "paper.pdf p. 4: synthetic signed/weighted-network validation", "paper.pdf p. 5, Figure 3: simulated and empirical flock inference", "paper.pdf pp. 6–7, Figure 4: tau-pathology equation, prediction and limitations", "source PDF SHA-256 10396ed47a9c8b041f80c3131015ddf612a66011ac718329e7596f705098d16e", "Evidence status: full-text verified version of record; no independent reproduction performed."],
    },
    {
        "arxiv_id": "doi-10.1038-s41467-024-52878-2", "source_version": "version of record", "source_pdf": "https://www.nature.com/articles/s41467-024-52878-2.pdf",
        "title_en": "Learning protocols for the fast and efficient control of active matter", "title_zh": "学习快速高效控制主动物质的协议",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "numerical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["b190514e354e6fa5"], ["Active Matter"]),
        "verified_metadata": {"doi": "10.1038/s41467-024-52878-2", "version": "version of record", "title": "Learning protocols for the fast and efficient control of active matter", "authors": ["Corneel Casert", "Stephen Whitelam"], "journal": "Nature Communications", "volume": "15", "article": "9128", "published": "2024-10-23", "abstract": "Neuroevolution learns rapid, discontinuous control protocols for simulated active Ornstein–Uhlenbeck and active Brownian particles, including work extraction.", "comment": "Version of record; no Crossref update notice found"},
        "sections": [
            sec("作者信息", r"作者 Corneel Casert、Stephen Whitelam；Nature Communications 15, 9128 (2024)，DOI:10.1038/s41467-024-52878-2，发表于 2024-10-23。核验 9 页期刊版、Supplementary Data 声明与 Crossref 状态；正文全部结果来自随机模拟及部分解析基线，没有新实验。"),
            sec("研究问题", r"被动过阻尼体系的最优控制常含端点跳跃和快速变化，但 active matter 难以解析求解，已有近似工作因慢变或固定函数形式而限制协议。论文问：把 time-dependent control parameters 编码为神经网络，再用 genetic algorithm 直接最小化热、时间、分布误差或功，能否找到更快/更省能的 active-particle state-to-state protocols，并扩展到相互作用多体 active engine？"),
            sec("背景", r"协议写成 g_θ(t/t_f)，输出 trap stiffness、activity 等控制量；网络的表达能力允许 discontinuities、non-monotonic variations 和多参数同步控制。每个候选协议通过随机动力学模拟评估目标，遗传算法只用最终 objective 更新 θ。作者强调得到的是 learned 而非 optimal protocols，因为非凸搜索不保证全局最优，并用多初始化一致性作为实践检查。", r"Figure 2 比较二维 harmonic trap 内 active Brownian particle 的 learned protocol 与先前参数化 BGT protocol；蓝色路径用约三分之一时间达到相同目标分布误差。"),
            sec("模型与方法", r"第一问题为一维 harmonic trap 中 active Ornstein–Uhlenbeck particle，控制 α(t) 并计算 trajectory-averaged heat；第二问题控制二维 active Brownian particle 的 activity λ(t) 和 confinement κ(t)，目标是把被动中心态变成 active annular steady state。", r"多体问题含 N 个 WCA 排斥 active Brownian particles，控制 λ、κ，以 10^3 independent trajectories 估计平均功；分布误差图使用 10^5 trajectories。forward Euler step 为 Δt=10^-3，参数受实验可达范围约束。目标函数对未达到 transformation tolerance 的协议施加罚项，达到后才最小化 work。"),
            sec("核心结果与证据", r"单 active OU particle 的 heat-minimizing protocols 随 t_f 从末端 jump 过渡到初端 jump，中间出现快速和非单调结构；在作者设定与约束内，它们比先前慢变解析协议耗热更低。Figure 2 中双参数 learned protocol 在 t_f≈0.16 达到参照误差，BGT 约需 0.44，因而“about three times”更快。", r"加入 work objective 后，learned protocol 先提高 κ 和 λ、付出少量功，再在分布扩张后降低 κ，实现最终平均净负功；这是有限模拟下的 control solution，不是违反热力学，因为 active drive 提供能量。", r"多体 N=1–40、t_f=1 的 Figure 4 显示每粒子 extracted work 对 N 非单调，N=12 最低，N>25 时比单粒子更高效；简化 steady-state estimate 只捕捉非单调性而非定量值。延长 t_f=10 的协议出现 passive→active→passive 两次 activity switch。"),
            sec("有效性与局限", r"所有控制结果来自理想化 OU/ABP simulations；论文只论证算法可直接用于实验所能测量的 objective，并未实际闭环实验。learned protocol 的优越性是相对特定 constrained analytical baselines、parameter bounds、timestep、trajectory count 和目标定义，不是对所有控制算法的排名。", r"神经网络与遗传算法不保证 global optimum；sharp jumps 在真实 actuator 中受 bandwidth、delay 和 energy overhead 限制。多体结果仅 N≤40、二维 harmonic trap、WCA interaction 和指定噪声参数；未计训练计算成本，也未把该 segment 闭合成完整 engine cycle。"),
            sec("复现与资源", r"期刊：https://doi.org/10.1038/s41467-024-52878-2；协议数据随 Supplementary Data 1 提供；示例优化代码由文中 ref.70 指向作者既有公开实现。核验 PDF SHA-256：0a2335dd20d82d081833caa3e5f2e65b1c08d60e2ac6423bd10a92cf08ca24d4。", r"复现需固定 SDE/nondimensionalization、Δt、trajectory seeds/count、network architecture、mutation/population、parameter bounds、penalty c、Δ0、t_f、initial steady-state sampling 和独立训练次数。Evidence status: full-text verified numerical study; no independent reproduction performed."),
            sec("阅读指南", r"先读 pp.1–3 的 neuroevolution 设定和 OU heat example，注意 learned≠optimal。核心速度证据看 p.5 Figure 2；净功看 p.6 Figure 3；多体尺度效应看 p.7 Figure 4。最后检查 Discussion，把模拟可行性、相对 baseline 改进和实验适用建议分开。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/doi-10.1038-s41467-024-52878-2/figure-2-control-protocol.webp", "label": "Figure 2", "visual_type": "comparison", "evidence": "paper.pdf p. 5, Figure 2", "alt_text": "learned 与参数化协议在 active Brownian particle 状态转换中的路径、时间和误差对比。", "caption": "允许快速跳跃和双参数协同后，该模拟任务约以参照协议三分之一时间达到目标误差。", "selection_rationale": "Figure 2 直接展示“fast control”的量化比较、目标分布和控制路径，而非只显示算法框图。"},
        "figure_refs": [figure("doi-10.1038-s41467-024-52878-2", "figure-2-control-protocol.webp", "Figure 2", 5, "compare learned and constrained state-transfer protocols", "λ–κ 路径、时间序列、分布演化和误差。", "learned protocol 在该模拟设定中约快三倍达到参照误差。", "The result is baseline- and constraint-specific and does not prove global optimality or experimental performance.")],
        "equation_refs": [
            {"label": "Active OU particle", "latex": r"\dot r=v-\mu\alpha r+\sqrt{2D}\,\eta(t)", "role": "define the single-particle controlled stochastic dynamics", "symbols": {"alpha": "time-dependent trap stiffness", "v": "OU self-propulsion", "D": "passive diffusion"}, "evidence": "paper.pdf p. 2, Eq. (1)", "interpretation": "The protocol changes confinement while activity supplies an additional nonequilibrium degree of freedom."},
            {"label": "Mean work under stiffness control", "latex": r"\langle W\rangle=\frac12\int_0^{t_f}dt\,\dot\kappa\,\langle r^2\rangle", "role": "score energy input or extraction during the protocol", "symbols": {"kappa": "controlled stiffness", "r": "particle radius"}, "evidence": "paper.pdf p. 5, Eq. (15); N-particle extension on p. 6, Eq. (18)", "interpretation": "Negative mean work is enabled by active energy injection and protocol timing, not by an equilibrium free-energy cycle."},
        ],
        "evidence_refs": ["paper.pdf pp. 1–3: neuroevolution and active-OU heat protocols", "paper.pdf p. 5, Figure 2: threefold state-transfer comparison", "paper.pdf p. 6, Figure 3: state transfer with net work extraction", "paper.pdf p. 7, Figure 4: finite-N many-body engine segment", "source PDF SHA-256 0a2335dd20d82d081833caa3e5f2e65b1c08d60e2ac6423bd10a92cf08ca24d4", "Evidence status: full-text verified numerical study; no independent reproduction performed."],
    },
]


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    installed: list[str] = []
    for card in CARDS:
        card_id = str(card["arxiv_id"]).replace("/", "-")
        (OUT / f"{card_id}.json").write_text(
            json.dumps(card, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        installed.append(card_id)
    print(json.dumps({"installed": installed}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
