#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 049."""
from __future__ import annotations

import json
from pathlib import Path

from install_full_collection_batch_014 import sec
from install_full_collection_batch_032 import card

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"

CARDS = [
card("record-8d02528b4e10e2a4", "arXiv manuscript", "https://arxiv.org/pdf/1509.03580",
     "Discovering governing equations from data by sparse identification of nonlinear dynamical systems", "通过非线性动力系统稀疏辨识从数据发现控制方程",
     "theory_numerics", "8d02528b4e10e2a4", "Active Matter",
     {"doi":"10.1073/pnas.1517384113","arxiv_id":"1509.03580","version":"arXiv full text","title":"Discovering governing equations from data by sparse identification of nonlinear dynamical systems","authors":["Steven L. Brunton","Joshua L. Proctor","J. Nathan Kutz"],"journal":"Proceedings of the National Academy of Sciences","volume":"113","pages":"3932–3937","published":"2016","abstract":"SINDy identifies parsimonious nonlinear dynamical systems by sparse regression over a library of candidate functions evaluated on measured trajectories.","comment":"PNAS article with extended arXiv manuscript and supplementary examples"},
     [sec("作者信息", "作者 Steven L. Brunton、Joshua L. Proctor、J. Nathan Kutz；PNAS 113(15), 3932–3937 (2016)，DOI:10.1073/pnas.1517384113。核验 arXiv:1509.03580 全文26页，其中包含主文与扩展补充材料。"),
      sec("研究问题", "仅给定多变量状态随时间的测量X(t)，能否自动发现满足ẋ=f(x)的低维控制方程？核心困难是候选非线性数量很快爆炸、数值微分放大噪声，而一般黑箱预测器又不直接给出可解释方程。"),
      sec("背景", "论文提出后来被称为SINDy的框架：许多物理系统虽然非线性，但真正控制动力学的项在合适函数库中是稀疏的。将常数、多项式、三角函数等候选列组成Θ(X)，每个状态分量的导数只需少数非零系数。", "目录把本文归入Active Matter，但原文是通用数据驱动动力系统方法，例子包括Lorenz、圆柱尾流和参数化系统，并未研究活性粒子；本卡保留目录标签，同时明确其真实范围。"),
      sec("模型与方法", "先由时间序列构造状态矩阵X和导数矩阵Ẋ，再解Ẋ=Θ(X)Ξ。作者采用sequentially thresholded least squares：拟合后删除小于阈值的系数，并在剩余support上反复回归，以近似l0稀疏选择。", "圆柱绕流例子先用POD把高维流场压缩为少量modal coordinates，再加入mean-shift mode；稀疏模型恢复Landau型振幅动力学与slow manifold。参数化logistic map与Hopf normal form则把控制参数作为额外变量或候选项。"),
      sec("核心结果与证据", "Figure 1把完整流程画成数据矩阵、候选函数库、逐列稀疏系数与恢复方程，直接说明算法为何可解释。Lorenz实验在低噪声下精确恢复三个方程；噪声增大时短时轨迹仍贴合，但chaos使长期逐点误差不可避免地指数增长。", "Figures 7–10展示圆柱尾流：POD轨迹位于抛物slow manifold，含shift mode的稀疏模型能描述从不稳定定点到limit cycle的transient；只用吸引子上的训练数据则无法可靠外推off-attractor dynamics。", "补充材料还测试linear/cubic systems、logistic bifurcation与Hopf parameter discovery。证据说明稀疏结构在设计例子中可恢复，并不证明任意隐藏变量、非Markov或高噪声观测都存在唯一稀疏方程。"),
      sec("有效性与局限", "成功依赖候选library包含真实项、坐标选择合适、采样覆盖关键transient且导数估计足够稳定。高度相关的library columns会破坏identifiability；阈值是bias–variance超参数，论文没有给一般自动选择准则或finite-sample support-recovery保证。", "流体例子依赖POD和物理启发的shift mode，说明表示学习并非由SINDy自动完成。测量噪声、outliers、控制输入、hidden variables和weak-form differentiation需要后续扩展；chaotic trajectory的长期不重合也不能简单判为方程错误。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/1509.03580；期刊：https://doi.org/10.1073/pnas.1517384113。PDF SHA-256：018edd169c3057304a5a09e5b42622ef6e5eeb350c8e912730e5bc7e5a507255。原文补充材料给出算法与数据细节；现代维护实现可参考 PySINDy，但其版本并非本文原始实验环境。", "复现应固定sampling interval、derivative scheme、library degree、column normalization、sparsity threshold、training window、noise realization及POD truncation，并同时报告equation support、coefficient error与trajectory metrics。Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–6 概念、Figure 1与算法；pp.7–14看Lorenz和cylinder-wake主证据；pp.15–21读补充数值例子；pp.22–26看实现与参数细节。")],
     "figure-1-sindy-workflow.webp","Figure 1",5,"schematic","从状态与导数数据构造非线性候选库，再逐状态变量求稀疏系数并恢复控制方程。","真正活跃的少数library terms在系数矩阵中形成稀疏support，使输出保持可解释。","Figure 1把原始轨迹、候选函数库、稀疏回归和最终方程放在同一流程中，是理解SINDy核心机制最直接且信息完整的原文图证。",
     [{"label":"Sparse dynamics regression","latex":r"\dot X=\Theta(X)\Xi","role":"represent each state derivative with a sparse combination of candidate nonlinearities","symbols":{"X":"sampled state matrix","Theta(X)":"candidate nonlinear feature library","Xi":"sparse coefficient matrix"},"evidence":"paper.pdf p. 5, Eqs. (6)–(7) and Figure 1","interpretation":"Equation discovery is conditional on a suitable library, coordinates and derivative estimates."}],
     ["paper.pdf pp. 1–6, Figure 1: SINDy formulation and algorithm","paper.pdf pp. 7–12, Figures 3–6: Lorenz recovery and noise","paper.pdf pp. 12–15, Figures 7–10: cylinder-wake reduced dynamics","paper.pdf pp. 15–21: parameterized and supplementary systems","source PDF SHA-256 018edd169c3057304a5a09e5b42622ef6e5eeb350c8e912730e5bc7e5a507255","Evidence status: full-text verified analytical/numerical study; no independent reproduction performed."]),

card("record-9185034ca2d581a8", "arXiv manuscript", "https://arxiv.org/pdf/2011.14687",
     "The renormalization group and the diffusion equation", "重整化群与扩散方程",
     "theory_numerics", "9185034ca2d581a8", "Renormalization Group",
     {"doi":"10.1093/ptep/ptaa175","arxiv_id":"2011.14687","version":"arXiv full text","title":"The renormalization group and the diffusion equation","authors":["Masami Matsumoto","Gota Tanaka","Asato Tsuchiya"],"journal":"Progress of Theoretical and Experimental Physics","volume":"2021","pages":"023B02","published":"2021","abstract":"A generalized diffusion equation determined by the cutoff and quadratic seed action reproduces exact-renormalization-group correlators of diffused fields.","comment":"PTEP article cross-checked with arXiv full text"},
     [sec("作者信息", "作者 Masami Matsumoto、Gota Tanaka、Asato Tsuchiya；Progress of Theoretical and Experimental Physics 2021, 023B02，DOI:10.1093/ptep/ptaa175。核验 arXiv:2011.14687 全文17页。"),
      sec("研究问题", "gradient flow或diffusion会把bare field平滑到有限flow time，而exact renormalization group会随cutoff积掉短程自由度。两者是否不仅直觉相似，而能在任意cutoff function及带quadratic seed action的ERG中建立精确correlator关系？"),
      sec("背景", "标准heat equation的solution是Gaussian kernel convolution，flow time提供平滑长度。Wilson/Polchinski型ERG的effective action则满足功能微分方程；seed action改变blocking scheme但不应改变物理。作者把此前特定cutoff下的gradient-flow联系推广到更一般设置。", "这里的diffused field不是额外随机动力学，也不是数值RG近似。结论比较的是bare-action平均下的广义扩散场与effective-action平均下的未扩散场，并包含cutoff-dependent normalization/contact terms。"),
      sec("模型与方法", "从含quadratic seed action的ERG equation出发，作者构造momentum-space kernel，使flowed fieldϕ(τ,p)满足线性generalized diffusion equation。kernel K(p)和seed quadratic form共同决定damping factor；适当匹配τ与cutoff scale后，对任意n-point correlator导出恒等式。", "证明采用generating functional与functional derivatives，而非数值积分。随后将形式应用于scalar field anomalous dimension，并讨论nonlinear diffusion/general seed action时为何简单线性对应需要修正。"),
      sec("核心结果与证据", "核心结论是：diffused fields在bare theory中的相关函数，乘上指定wave-function factors并处理二点contact term后，等于ERG effective theory中bare fields的相关函数。因而large diffusion time对应向IR coarse graining。", "Eqs. (2.12)–(2.18)给出一般cutoff与seed下的kernel、diffusion equation和solution；Section 3把它们代入correlator identity。论文几乎完全是解析推导，没有数值曲线，证据强度来自逐式构造与特殊情形回收。", "作者指出gradient flow可帮助定义renormalized composite observables，但本文只处理标量场及主要为quadratic seed的情形；更一般nonlinear flow、gauge theory和非平衡RG需要额外结构。"),
      sec("有效性与局限", "等价依赖ERG kernels可逆、cutoff regular且boundary conditions合适。它是scheme-aware的correlator identity，不意味着任意扩散过程都执行同一个物理RG，也不自动证明universality、fixed-point stability或numerical efficiency。", "推导以Euclidean scalar field为主，未展示lattice Monte Carlo、finite-volume或discretization误差。异常维数通过field rescaling进入；若seed action含更复杂相互作用，线性generalized diffusion不再足够。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2011.14687；期刊：https://doi.org/10.1093/ptep/ptaa175。PDF SHA-256：06f3efec5880a3658f24e53adc97fd85b69b0c255459508a4bcddb147104f32c。解析论文未提供或需要代码仓库。", "复核应固定Fourier convention、cutoff K、seed quadratic kernel、RG time与diffusion time映射、functional measure及二点contact subtraction；逐一验证Eqs. (2.12)–(3.10)和standard heat-kernel limit。Evidence status: full-text verified analytical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3动机和标准diffusion；pp.4–8看一般ERG与广义扩散构造；pp.9–13读correlator identity；pp.14–17看anomalous dimension、范围和结论。")],
     "equations-generalized-diffusion.webp","Eqs. (2.10)–(2.15)",5,"schematic","由cutoff与quadratic seed定义的广义扩散kernel、初值问题及其momentum-space解。","damping kernel把diffusion time与ERG coarse-graining scale精确对应，而非仅作类比。","这组连续方程集中展示广义扩散初值问题、kernel解及其与ERG的对应，是没有数据图的解析论文中最能代表中心构造的页面证据。",
     [{"label":"Generalized diffusion flow","latex":r"\partial_\tau\varphi(\tau,p)=-\mathcal{K}_\tau(p)\varphi(\tau,p)","role":"smooth bare fields with a kernel fixed by the ERG cutoff and seed action","symbols":{"tau":"diffusion or flow time","K_tau":"scheme-dependent momentum kernel","varphi":"diffused scalar field"},"evidence":"paper.pdf pp. 4–5, Eqs. (2.12)–(2.18)","interpretation":"The familiar heat equation is a special choice of the kernel."}],
     ["paper.pdf pp. 1–3: diffusion and ERG motivation","paper.pdf pp. 4–8, Eqs. (2.12)–(2.18): generalized diffusion construction","paper.pdf pp. 9–13: correlator identity","paper.pdf pp. 14–17: anomalous dimension and scope","source PDF SHA-256 06f3efec5880a3658f24e53adc97fd85b69b0c255459508a4bcddb147104f32c","Evidence status: full-text verified analytical study; no independent reproduction performed."]),

card("record-94bdcd00b170e8be", "arXiv v2 manuscript", "https://arxiv.org/pdf/2410.07799",
     "Mind the Gap: a Spectral Analysis of Rank Collapse and Signal Propagation in Attention Layers", "注意谱隙：注意力层秩坍缩与信号传播的谱分析",
     "theory_numerics", "94bdcd00b170e8be", "Transformer Theory",
     {"doi":None,"arxiv_id":"2410.07799","version":"arXiv v2 full text","title":"Mind the Gap: a Spectral Analysis of Rank Collapse and Signal Propagation in Attention Layers","authors":["Alireza Naderi","Thiziri Nait Saada","Jared Tanner"],"journal":"Proceedings of The 28th International Conference on Artificial Intelligence and Statistics","volume":"PMLR 267","pages":None,"published":"2025","abstract":"Random-matrix analysis links attention's outlier singular value and spectral gap to width- and depth-wise rank collapse, and motivates removing the uniform-token component.","comment":"AISTATS 2025 paper; PMLR volume verified from manuscript metadata"},
     [sec("作者信息", "作者 Alireza Naderi、Thiziri Nait Saada、Jared Tanner；AISTATS 2025, PMLR 267；对应 arXiv:2410.07799v2。核验全文32页。正文元数据未稳定给出页码或DOI，本卡不推测。"),
      sec("研究问题", "self-attention为何会让token representations逐层趋同并丢失有效rank？既有分析常只看深度乘积或特殊初始化。本文问：单层在width增加时是否已出现rank collapse，决定collapse rate的谱结构是什么，能否用一个直接的谱修正同时缓解width与depth问题？"),
      sec("背景", "softmax attention matrix是row-stochastic Markov matrix，因此总有特征值1及接近uniform token direction的outlier singular component。其余singular values随token width缩小，形成spectral gap；反复相乘便把信号偏向相同方向。", "作者区分width collapse（单层输出随embedding width增大趋于rank one）和depth collapse（多层迭代造成token uniformity）。LayerNorm、residual和MLP会改变完整Transformer，但不能消除分析所指出的attention谱偏置。"),
      sec("模型与方法", "在随机Gaussian key/query/value与近isometric token输入下，作者用random matrix theory刻画attention spectrum，并证明Frobenius stable rank与token covariance的收缩率。理论同时覆盖softmax矩阵及一类i.i.d. Markov attention surrogates。", "修正方法从attention matrix减去rank-one uniform component，即移除对应outlier/spectral gap；实验在synthetic layers、BERT/TinyBERT初始化及带residual/LayerNorm的deep stacks中比较vanilla、gap removal与更昂贵的full outlier removal。"),
      sec("核心结果与证据", "Theorem 1给出width趋于无穷时attention输出rank collapse的速率，并把它与outlier singular value分离。Figure 1显示softmax与多类random attention均出现相同gap；Figure 2用Markov surrogate核对理论scaling。", "Figures 3–4展示BERT-family初始化以及随width/depth的rank下降：vanilla curves快速坍缩，减去uniform rank-one项后stable rank与signal propagation明显保持。Figure 5进一步显示deep product中该修正避免梯度范数爆炸。", "Figure 6追踪真实softmax attention跨层的spectrum，Figure 7说明便宜的uniform-component removal接近逐层精确移除principal component的效果。附录在non-isometric和tokenized sentence输入上复核spectral gap。"),
      sec("有效性与局限", "主要定理依赖随机初始化、独立Gaussian weights、宽度/长度渐近和输入近isometry；训练后的attention、causal masks、multi-head correlations与positional structure可能显著改变spectrum。rank preservation不等价于下游accuracy提升。", "实验多为初始化和synthetic propagation，模型与任务规模有限。减uniform component改变row sums与概率解释，实际架构需考虑residual scaling和optimization；论文未给大规模预训练的quality/compute对照。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2410.07799。PDF SHA-256：2d54a86b555c40851eae45c863fa09203313afc41c0c2da1e3c0ce93c7cb51a0。正文给出公开实现链接：https://github.com/thizirinait/Spectral-Analysis-of-Attention-Layers.git 。", "复现需固定T、width d、depth L、Q/K/V scaling、softmax temperature、normalization/residual variant、random seeds及stable-rank/gradient-norm定义，并分别报告single-layer spectrum与multi-layer product。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4 Figure 1和问题；pp.5–9看谱定理；pp.9–13读Figures 3–7与修正；pp.14–20看讨论和证明；pp.21–32为附录与额外实验。")],
     "figure-4-rank-collapse.webp","Figure 4",10,"comparison","vanilla attention与remove-the-gap修正在width和depth方向的rank collapse对比。","移除uniform-token谱分量后，stable rank随宽度与层数保持得更好。","Figure 4在同一组实验中并列width与depth两种rank collapse，并直接展示谱隙修正后的变化，是连接理论机制和数值结果的关键图证。",
     [{"label":"Remove-the-gap attention","latex":r"A_\perp=A-\frac{1}{T}\mathbf{1}\mathbf{1}^{\top}","role":"remove the uniform-token rank-one component associated with the spectral outlier","symbols":{"A":"row-stochastic attention matrix","T":"number of tokens","1":"uniform token direction"},"evidence":"paper.pdf pp. 8–10, proposed spectral-gap removal and Figure 4","interpretation":"The operation targets the dominant uniform direction; architecture-level effects still require empirical validation."}],
     ["paper.pdf pp. 1–4, Figure 1: spectral-gap mechanism","paper.pdf pp. 5–9: random-matrix theorems","paper.pdf pp. 9–13, Figures 3–7: width/depth and gradient experiments","paper.pdf pp. 21–32, Figures 8–11: non-isometric and model checks","source PDF SHA-256 2d54a86b555c40851eae45c863fa09203313afc41c0c2da1e3c0ce93c7cb51a0","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-982fc46bbe09aee7", "arXiv manuscript", "https://arxiv.org/pdf/2505.19458",
     "Recurrent Self-Attention Dynamics: An Energy-Agnostic Perspective from Jacobians", "循环自注意力动力学：基于雅可比矩阵的能量无关视角",
     "theory_numerics", "982fc46bbe09aee7", "Transformer Theory",
     {"doi":None,"arxiv_id":"2505.19458","version":"arXiv full text","title":"Recurrent Self-Attention Dynamics: An Energy-Agnostic Perspective from Jacobians","authors":["Akiyoshi Tomihari","Ryo Karakida"],"journal":"Advances in Neural Information Processing Systems","volume":"38","pages":None,"published":"2025","abstract":"Jacobian spectra and Lyapunov exponents characterize recurrent self-attention beyond symmetric energy models, explaining how normalization promotes near-critical stable computation.","comment":"NeurIPS 2025 manuscript metadata; DOI not asserted"},
     [sec("作者信息", "作者 Akiyoshi Tomihari、Ryo Karakida；NeurIPS 2025论文，对应 arXiv:2505.19458。核验全文34页。当前可核验文本未给稳定DOI或页码，本卡不推测。"),
      sec("研究问题", "把同一个self-attention block循环T次可产生iterative inference，但已有Hopfield/energy解释通常要求对称权重、单头或特殊activation。对一般multi-head、非对称recurrent SA，如何判断轨迹收敛、振荡或chaos，并解释normalization为何改善长循环计算？"),
      sec("背景", "离散动力系统x_{t+1}=F(x_t)的局部行为由Jacobian J=∂F/∂x控制：谱半径、复特征值与Lyapunov exponent分别决定扰动收缩、旋转/振荡和长期稳定性。该视角不需要先构造单调下降的energy。", "作者研究recurrent/iterative SA，不是普通Transformer每层参数都不同的深度网络。把loop数增加带来的accuracy变化解释为同一map的动力学性质，不能直接外推到任意trained transformer。"),
      sec("模型与方法", "论文推导single-与multi-head SA Jacobian，分析attention、value projection和normalization的谱贡献；用maximum/mean Lyapunov exponents量化循环轨迹对微扰的放大。实验覆盖Sudoku、CIFAR-10与文本summarization式任务，并比较LayerNorm、RMSNorm、无归一化及AKOrN等迭代模型。", "作者还提出ItrSA表述和pseudo-energy/contribution index，用以分析不存在严格energy function时的计算进度；并测试energy-inspired regularization是否真的改善accuracy。"),
      sec("核心结果与证据", "Figure 1显示normalization压低recurrent SA Jacobian最大spectral norm；Figure 2从模型、几何示意和complex-plane eigenvalues说明归一化把谱推向临界附近，而非简单让所有mode强收缩。", "Figure 3把mean Lyapunov exponent与accuracy关联：高性能模型多集中在接近零的区域，过正导致不稳定、过负导致快速遗忘。Figure 4显示ItrSA在不同normalization下随loops增加稳定提升，而缺少控制时可能退化。", "Figure 5显示强制energy-style regularization反而弱于原模型，支持Jacobian框架比特定能量假设更普适。Figure 6及附录用test-time trajectories、pseudo-energy与多头扫描补充，但这些仍是所选架构与任务上的经验关联。"),
      sec("有效性与局限", "Jacobian是局部线性化，non-normal transient growth可能不由eigenvalues单独捕捉；finite-time Lyapunov estimates依赖trajectory、loop horizon和numerical precision。接近零exponent与accuracy相关，不构成因果充分条件。", "实验规模和任务有限，训练protocol、normalization位置与residual parameterization都会改变结论。论文不保证循环无限次收敛，也没有证明pseudo-energy单调；计算完整Jacobian在大模型中昂贵，需要近似估计。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2505.19458。PDF SHA-256：fae7c03225d387c7bf0fa8ef31d52acd10638e584ff2d74b3d230b5c098c2d94。正文未给本文自身的公开代码仓库；补充材料仅为比较方法AKOrN列出外部实现。", "复现需固定loop T、heads、normalization placement/epsilon、residual scaling、Jacobian evaluation point、Lyapunov horizon、datasets、training seeds及accuracy aggregation；谱图与task metrics应配对报告。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–4问题与Jacobian视角；pp.5–7看Figures 1–3和谱机制；pp.8–10看loops与regularization；pp.11–14读讨论；pp.15–34为推导、实验细节与补充图。")],
     "figure-2-jacobian-spectrum.webp","Figure 2",6,"comparison","归一化对最大Lyapunov exponent、轨迹几何与Jacobian复特征值分布的影响。","normalization把不稳定谱压向接近临界的区域，同时保留可用于循环推理的非平凡模式。","Figure 2是论文energy-agnostic Jacobian解释的直接证据。",
     [{"label":"Recurrent local dynamics","latex":r"\delta x_{t+1}=J(x_t)\,\delta x_t,\qquad J=\frac{\partial F}{\partial x}","role":"track perturbation propagation through repeated applications of the same attention map","symbols":{"F":"recurrent self-attention update","J":"state-dependent Jacobian","delta_x":"infinitesimal perturbation"},"evidence":"paper.pdf pp. 3–6, Jacobian formulation and Figures 1–2","interpretation":"Eigenvalues describe local modes, while finite-time Lyapunov exponents summarize products along a trajectory."}],
     ["paper.pdf pp. 1–4: recurrent-SA problem and energy limitations","paper.pdf pp. 5–7, Figures 1–3: normalization, spectra and Lyapunov exponents","paper.pdf pp. 8–10, Figures 4–6: iterative inference and regularization","paper.pdf pp. 15–34: derivations and supplementary experiments","source PDF SHA-256 fae7c03225d387c7bf0fa8ef31d52acd10638e584ff2d74b3d230b5c098c2d94","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."]),

card("record-9f515671e11b49f1", "AISTATS 2024 manuscript", "https://arxiv.org/pdf/2307.03672",
     "Simulation-Free Schrödinger Bridges via Score and Flow Matching", "通过得分匹配与流匹配实现免模拟薛定谔桥",
     "theory_numerics", "9f515671e11b49f1", "Flow Matching",
     {"doi":None,"arxiv_id":"2307.03672","version":"arXiv v3 full text","title":"Simulation-Free Schrödinger Bridges via Score and Flow Matching","authors":["Alexander Y. Tong","Nikolay Malkin","Kilian Fatras","Lazar Atanackovic","Yanlei Zhang","Guillaume Huguet","Guy Wolf","Yoshua Bengio"],"journal":"Proceedings of The 27th International Conference on Artificial Intelligence and Statistics","volume":"PMLR 238","pages":"1279–1287","published":"2024","abstract":"[SF]2M trains Schrödinger bridge vector fields and scores from static endpoint couplings, avoiding simulation of the learned process during training.","comment":"AISTATS 2024 PMLR 238 article; arXiv v3 includes appendices"},
     [sec("作者信息", "作者 Alexander Y. Tong、Nikolay Malkin、Kilian Fatras、Lazar Atanackovic、Yanlei Zhang、Guillaume Huguet、Guy Wolf、Yoshua Bengio；AISTATS 2024, PMLR 238, 1279–1287；对应 arXiv:2307.03672v3。核验全文29页。"),
      sec("研究问题", "Schrödinger bridge在两个任意分布之间寻找entropy-regularized最优随机过程，但许多算法训练时要反复模拟当前SDE并拟合其marginals，代价高且误差累积。能否只采样静态endpoint pairs和解析conditional paths，同时学习probability-flow ODE与stochastic bridge SDE？"),
      sec("背景", "conditional flow matching可从简单的条件路径回归marginal velocity；score matching可学习同一路径的score。若endpoint coupling取Schrödinger/entropic OT coupling，对每对(x0,x1)使用Brownian-bridge-like Gaussian conditional，混合后的marginals就是目标bridge。", "‘simulation-free’限定于training objective不需从当前learned process rollout；生成或评估动态时仍要数值积分ODE/SDE。真实Schrödinger coupling通常未知，论文用minibatch entropic OT近似，因此仍有batch bias和Sinkhorn计算。"),
      sec("模型与方法", "[SF]²M联合回归conditional probability-flow velocity与score，边缘化后得到同一marginal path的ODE和正/反向SDE。源—目标pair由static entropic OT coupling采样；作者证明在全局optimum下目标等价于对应Schrödinger bridge。", "实验包括二维distribution transport、Gaussian ground truth、single-cell time-course interpolation/trajectory、Waddington landscape和gene regulatory network recovery；与DSB、IPF、OT-CFM等方法比较Wasserstein、NPE、MMD与生物指标。"),
      sec("核心结果与证据", "Figure 1显示8-Gaussians到moons的ODE与SDE trajectories，并说明同一网络体系可产生deterministic flow和stochastic bridge。Table 1突出训练时无需模拟或预训练score的算法差异。", "Figure 2从scRNA-seq bridge提取time-dependent Waddington landscape；Tables 4–5在多套单细胞数据上比较distribution fit与held-out timepoint interpolation。[SF]²M整体有竞争力，但并非每个指标都统一最佳。", "Figure 3从给定cell模拟多条未来轨迹，并将velocity-derived Granger关系用于GRN recovery；后续表格显示在synthetic networks上可恢复部分边。结果支持方法兼顾分布与动态推断，但生物因果解释仍依赖模型与观测时间分辨率。"),
      sec("有效性与局限", "理论等价要求函数类达到global optimum且endpoint coupling正确；minibatch OT并非全数据Schrödinger coupling，regularization、batch size与cost选择都会改变bridge。score/velocity estimation误差及ODE/SDE discretization仍影响结果。", "single-cell snapshots没有真实cell lineage，识别的trajectory和landscape是模型解释而非直接观察。GRN recovery由velocity derivatives推断，不能替代干预因果验证；高维Sinkhorn成本、feature metric和时间不等间隔也是实践限制。"),
      sec("复现与资源", "全文：https://arxiv.org/abs/2307.03672；PMLR：https://proceedings.mlr.press/v238/tong24a.html；代码：https://github.com/atong01/conditional-flow-matching。PDF SHA-256：4b492b1d7b03f377e04c91d672578a4708b5bb908a7a7cc1bd311e5de2750a55。", "复现需固定OT cost/ε、minibatch size、conditional variance schedule、ODE/SDE solver与steps、network/optimizer、cell preprocessing/PCA、timepoint split、seeds及各benchmark metric。Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."),
      sec("阅读指南", "先读 pp.1–3 Figure 1与贡献；pp.3–6看score/flow matching推导；pp.6–10读Tables 1–5和细胞结果；pp.11–15看结论与实验细节；pp.16–29为证明和补充实验。")],
     "figure-1-ode-sde-paths.webp","Figure 1",2,"comparison","8-Gaussians到moons的deterministic ODE paths、stochastic SDE paths及单个条件bridge示意。","同一静态pair-conditioned训练目标可恢复共享marginals的流与随机桥。","Figure 1最直接说明[SF]²M训练对象和ODE/SDE双重输出。",
     [{"label":"Joint flow-score objective","latex":r"\mathcal{L}_{[SF]^2M}=\mathcal{L}_{FM}(v_\theta)+\lambda(t)\mathcal{L}_{SM}(s_\theta)","role":"learn marginal velocity and score from analytically sampled conditional bridges","symbols":{"v_theta":"learned probability-flow velocity","s_theta":"learned marginal score","lambda":"time-dependent weighting"},"evidence":"paper.pdf pp. 3–5, Eqs. (5)–(8)","interpretation":"At the ideal optimum, the two regressions define ODE and SDE representations of the selected bridge marginals."}],
     ["paper.pdf pp. 1–3, Figure 1: simulation-free bridge overview","paper.pdf pp. 3–6: score and flow matching theory","paper.pdf pp. 6–10, Figure 2 and Tables 1–5: benchmarks and cell dynamics","paper.pdf pp. 9–11, Figure 3: trajectories and GRN recovery","source PDF SHA-256 4b492b1d7b03f377e04c91d672578a4708b5bb908a7a7cc1bd311e5de2750a55","Evidence status: full-text verified theoretical/numerical study; no independent reproduction performed."])
]

def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    ids = []
    for item in CARDS:
        pid = str(item["arxiv_id"])
        (OUT / f"{pid}.json").write_text(json.dumps(item, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        ids.append(pid)
    print(json.dumps({"installed": ids}, ensure_ascii=False))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
