#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 033."""
from __future__ import annotations
import json
from pathlib import Path
from install_full_collection_batch_032 import card
from install_full_collection_batch_014 import sec

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"data"/"collection_cards"
CARDS=[
card("doi-10.1038-s41598-026-47071-y","version of record","https://www.nature.com/articles/s41598-026-47071-y.pdf","Gauge-covariant stochastic neural fields: stability and finite-width effects","规范协变随机神经场：稳定性与有限宽度效应","theory_numerics","6e321ad478528686","Flow Matching",
{"doi":"10.1038/s41598-026-47071-y","version":"version of record","title":"Gauge-covariant stochastic neural fields: stability and finite-width effects","authors":["Rodrigo Carmo Terin"],"journal":"Scientific Reports","volume":"16","article":"16386","published":"2026-04-06","abstract":"A classical gauge-covariant stochastic effective field theory organizes neural stability, two-replica response and finite-width corrections.","comment":"Version of record; no Crossref update relation found"},
[sec("作者信息","作者 Rodrigo Carmo Terin；Scientific Reports 16, 16386 (2026)，DOI:10.1038/s41598-026-47071-y，发表于2026-04-06。核验18页期刊版、附录和Crossref；未发现关联更正或撤稿。论文是神经网络稳定性的经典随机有效场论，不主张神经网络与基本粒子规范场物理等价。"),
sec("研究问题","无限宽神经网络可由Gaussian process或kernel描述，但有限宽度涨落、深度传播稳定性和edge of chaos常用不同工具处理。论文问：能否用局域U(1)协变的经典随机场统一表示feature amplitude、structured couplings和随机深度演化，并从两副本响应定义Lyapunov增长与有限宽度修正？"),
sec("背景","模型包含复matter field、实Abelian connection和虚构stochastic depth time；所有场均为commuting variables。局域相位变换要求普通导数换成covariant derivative，从而约束admissible kernels与longitudinal fluctuations。", "作者反复限定有效坐标与d=4只是continuum/kernel geometry，不是物理时空；gauge language是共享形式结构。MSRJD functional把Langevin noise写成response-field path integral，便于计算correlators与linear response。"),
sec("模型与方法","从协变Langevin equations构造MSRJD action，并以Ward-type identity检查局域冗余。两个近邻replicas在相同noise下传播，其difference covariance给amplification kernel；最大特征值跨过1时定义mean-field marginality。", "数值一是随机初始化finite-width MLP，测量扰动随层的经验Lyapunov exponent；二是线性随机effective sector，比较解析dressed spectrum和Monte Carlo spectrum。finite-width expansion按1/N组织，但长观察窗引入T/N，因此只在该比值小的perturbative regime受控。"),
sec("核心结果与证据","两副本构造给出full amplification factor而非只看单点variance；在固定kernel geometry下，论文所保留阶的finite-width correction改变spectral shape，但不移动mean-field marginality condition。这是模型内perturbative consequence，不是所有architecture的exact theorem。", "有限宽MLP数值的instability threshold接近mean-field预测，偏差随宽度减小；线性随机sector中Figure 2显示simulation-averaged power spectrum与theoretical X(ω)在低频修正区吻合。该图验证的是专门线性测试模型，不直接验证完整gauge field theory。", "局域对称性限制observable必须gauge invariant或covariant；这避免把参数化相位当成物理自由度。论文没有展示训练后大型网络、真实任务accuracy或optimizer dynamics，因此结论停留在初始化/有效模型稳定性层。"),
sec("有效性与局限","continuum coordinates、connection field与noise covariance是phenomenological ansatz，未从唯一微观architecture推导。fixed kernel geometry假设排除了有限宽度引起kernel family本身变化的情形；更高阶loops可能移动阈值。", "T/N expansion对深度或观测窗随宽度增长时可能失效。MLP实验规模、activation和初始化有限；edge-of-chaos与泛化、可训练性或最优性能不是同一命题。形式上的Ward identity保证内部一致性，不证明经验模型是神经网络的唯一有效描述。"),
sec("复现与资源","期刊：https://doi.org/10.1038/s41598-026-47071-y。核验PDF SHA-256：9bad6e6d9b90b90972142874ad2a555ae8989c2edee47ce56b9abf97ad508212。复现需固定action、gauge fixing、noise normalization、kernel geometry、N、T、activation、weight variance、layer count、replica perturbation和spectral estimator。", "应分别报告mean-field threshold、finite-N drift、T/N范围与seed uncertainty。Evidence status: full-text verified version of record, perturbation theory and finite simulations; no independent reproduction performed."),
sec("阅读指南","先读 pp.2–4 Eqs. (1)–(7)确认场与局域变换，再读 pp.5–8 MSRJD和two-replica kernel。核心数值看 pp.9–11 Figure 2与Table 1；最后读Appendices C–D，检查1/N与T/N counting，并保留‘fixed kernel geometry’限定。")],
"figure-2-spectrum.webp","Figure 2",10,"comparison","线性随机有效模型的模拟功率谱与理论dressed spectrum对比。","有限宽修正在所测低频范围改变谱形，模拟与受控线性sector预测一致。","Figure 2是全文把有限宽度解析修正与数值频谱直接比较的核心证据。",
[{"label":"Covariant derivative","latex":r"D_\mu=\partial_\mu-iqA_\mu","role":"enforce local phase covariance","symbols":{"A_mu":"effective Abelian connection","q":"effective charge"},"evidence":"paper.pdf p. 3, Eq. (7) and surrounding definitions","interpretation":"The connection tracks phase transport in the effective representation, not a fundamental electromagnetic field."},{"label":"Finite-width spectrum","latex":r"X(\omega)=X^{(0)}(\omega)+\frac{\gamma T}{N}X^{(1)}(\omega)+O[(T/N)^2]","role":"organize the leading spectral correction","symbols":{"N":"width","T":"observation window","X1":"subleading correction"},"evidence":"paper.pdf Appendix D, Eq. (D49)","interpretation":"The perturbative parameter is T/N, so large depth or observation time can invalidate the truncation."}],
["paper.pdf pp. 2–4: gauge-covariant stochastic model","paper.pdf pp. 5–8: MSRJD and replica response","paper.pdf pp. 9–11, Figure 2 and Table 1: numerical tests","paper.pdf Appendices C–D: finite-width expansion","source PDF SHA-256 9bad6e6d9b90b90972142874ad2a555ae8989c2edee47ce56b9abf97ad508212","Evidence status: full-text verified version of record; no independent reproduction performed."]),

card("doi-10.1038-s42005-023-01173-5","arXiv manuscript","https://arxiv.org/pdf/2302.09439","Emergence of synchronised rotations in dense active matter with disorder","无序致密主动物质中同步旋转的涌现","numerical","89ea39dd881336b0","Active Matter",
{"doi":"10.1038/s42005-023-01173-5","arxiv_id":"2302.09439","version":"arXiv full text","title":"Emergence of synchronised rotations in dense active matter with disorder","authors":["Danial Vahabli","Tamas Vicsek"],"journal":"Communications Physics","volume":"6","article":"56","published":"2023-03-31","abstract":"A two-dimensional soft active-particle simulation develops directional, mixed, globally synchronized rotating and locally rotating states as quenched obstacle density increases.","comment":"arXiv full text cross-checked with version-of-record metadata; no Crossref update relation found"},
[sec("作者信息","作者 Danial Vahabli、Tamas Vicsek；Communications Physics 6, 56 (2023)，DOI:10.1038/s42005-023-01173-5；全文取arXiv:2302.09439，共27页含补充分析。核验Crossref状态；未发现关联更正或撤稿。全部核心结果来自二维particle simulations，没有实验。"),
sec("研究问题","极性active particles在均匀环境中倾向形成全局定向运动，而随机障碍提供isotropic quenched disorder。论文问：随着obstacle density增大，定向流是否只被逐渐破坏，还是会经由局域混合态形成全局同手性旋转；quenched disorder与temporal shot noise同时存在时谁主导相态？"),
sec("背景","模型粒子以恒速自推进，短程alignment和soft repulsion决定方向；固定随机障碍也产生排斥/转向。周期边界下没有外加手性，因此clockwise或anticlockwise全局旋转的选择是spontaneous chiral symmetry breaking。", "Figure 3给出directional、labyrinth、synchronized rotation、bidirectional local rotation、random和meander六类motion patterns。颜色同时编码瞬时方向与旋转手性，是后续order parameters的视觉词典。"),
sec("模型与方法","作者扫描obstacle density、particle density、alignment radius、rotational noise与system size，Euler式更新位置/方向。定义global polarization、局部/全局rotation fraction和angular momentum-like order，通常对160次simulation ensemble统计。", "状态分类结合order-parameter阈值和movie inspection；障碍位置quenched但不同realizations重采样。所谓non-reciprocal transition是对coexisting/moving phases形态的解释，模型的pair rules并未系统推导完整nonreciprocal field theory。"),
sec("核心结果与证据","低障碍密度为directional flow；增加障碍后进入局部定向/旋转共存的labyrinth。窄参数区出现几乎所有粒子同向绕各自局部中心旋转的global synchronized state，尽管没有全局中心或显式chirality bias。", "Figure 4中polar order下降后global rotation order突然上升，再在更高障碍密度下降为CW/CCW局域domains。Figure 3/4是有限L、有限时间数值观察；作者的finite-size scans支持状态不完全是小系统伪影，但未给thermodynamic critical exponents。", "同时加入angular shot noise时，相图主要随quenched obstacle density组织，说明在所扫参数中quenched disorder主导。该结果不是一般定理；若改变noise amplitude、interaction ranges或obstacle dynamics，竞争可改变。"),
sec("有效性与局限","soft particles、固定速度、短程alignment和理想随机障碍是最小模型；没有hydrodynamics、inertia、真实碰撞形状或实验参数映射。rotation center与synchrony metrics依赖轨迹窗口和阈值。", "global chirality可能在更大尺度形成domains而非真正long-range order；模拟sizes不足以严格区分phase transition与crossover。‘non-reciprocal’只表示某些phase-coupling相似性，不能从图样直接推断action–reaction violation或universality class。"),
sec("复现与资源","原文：https://arxiv.org/abs/2302.09439；期刊：https://doi.org/10.1038/s42005-023-01173-5。PDF SHA-256：ebe5e034506d6e18f36d9fffd09ba868d0f85da3cced2df4b5938445bd7c83ba。复现需固定L、N、speed、radii、alignment/repulsion strengths、obstacle ensemble、dt、run length、transient、noise与state thresholds。", "应报告seed distributions和size scaling而非只给代表movie。Evidence status: full-text verified numerical manuscript; no independent reproduction performed."),
sec("阅读指南","先读 pp.4–7 Eqs. (1)–(5)和Figure 1确认相互作用；再看 p.13 Figure 3建立状态分类，pp.14–17 Figures 4–6核查order parameters、noise与size effects。最后将作者的nonreciprocal analogy与直接数值结果分开。")],
"figure-3-motion-states.webp","Figure 3",13,"phase_diagram","六种二维active-particle运动图样及方向/手性色标。","各向同性quenched disorder把极性流依次重组为混合态、全局同步旋转和局域双手性旋转。","Figure 3是全文状态分类的直接视觉证据，并为后续序参量曲线定义图样。",
[{"label":"Heading update","latex":r"\theta_i(t+\Delta t)=\arg\!\sum_{j\in\mathcal N_i}e^{i\theta_j}+\text{repulsion}+\eta_i","role":"combine alignment, obstacle repulsion and angular noise","symbols":{"theta_i":"particle heading","N_i":"neighbors","eta_i":"shot noise"},"evidence":"paper.pdf pp. 5–7, model equations","interpretation":"The rotational phases emerge numerically from achiral local rules plus quenched disorder."}],
["paper.pdf pp. 4–7: particle and obstacle model","paper.pdf p. 13, Figure 3: motion-state atlas","paper.pdf pp. 14–17, Figures 4–6: order parameters and robustness","source PDF SHA-256 ebe5e034506d6e18f36d9fffd09ba868d0f85da3cced2df4b5938445bd7c83ba","Evidence status: full-text verified numerical manuscript; no independent reproduction performed."]),

card("doi-10.1038-s42254-020-0152-1","arXiv manuscript","https://arxiv.org/pdf/1910.02528","Computational models for active matter","主动物质的计算模型","theory_numerics","1db9d90525affb02","Active Matter",
{"doi":"10.1038/s42254-020-0152-1","arxiv_id":"1910.02528","version":"arXiv full text","title":"Computational models for active matter","authors":["M. Reza Shaebani","Adam Wysocki","Roland G. Winkler","Gerhard Gompper","Heiko Rieger"],"journal":"Nature Reviews Physics","volume":"2","pages":"181–199","published":"2020-03-10","abstract":"A review organizes microscopic and continuum models for dry and wet active matter across particles, fluids, cells and tissues.","comment":"Review article; arXiv full text cross-checked with version-of-record metadata"},
[sec("作者信息","作者 M. Reza Shaebani、Adam Wysocki、Roland G. Winkler、Gerhard Gompper、Heiko Rieger；Nature Reviews Physics 2, 181–199 (2020)，DOI:10.1038/s42254-020-0152-1；全文取arXiv:1910.02528，共23页。它是综述卡，不把二手总结写成新实验发现。"),
sec("研究问题","active matter跨越分子马达、细菌、合成微泳者、群体动物与组织；模型可按microscopic/continuum、dry/wet、generic/system-specific划分。综述问：不同层级的方程和numerical methods各保留哪些自由度、相互作用与守恒律，在哪些现象和尺度上适用？"),
sec("背景","dry systems把动量耗散给substrate，常用Vicsek、active Brownian particles、cellular Potts或phase fields；wet systems必须解析或近似solvent hydrodynamics，可用Stokesian dynamics、multiparticle collision、lattice Boltzmann或active continuum stresses。", "Figure 1把dry/wet与micro/macro组成二维模型地图，并用箭头表示coarse-graining或增加复杂度。它是导航框架，不声称不同模型严格等价。"),
sec("模型与方法","综述比较agent-based equations、kinetic closures、continuum PDEs、deformable-cell与tissue models，同时列出integration、collision、fluid solver和boundary techniques。Table II汇总代表性continuum equations及fields。", "每次降维都会丢信息：ABP保留位置与orientation但忽略推进机制；Toner–Tu型field theory保留density/polarization；active nematohydrodynamics还耦合Q tensor与solvent flow。模型选择应由observable、scale、geometry和momentum conservation决定。"),
sec("核心结果与证据","综述的主要贡献是taxonomy与适用性比较，而非单一数值结果。dry microscopic models能产生MIPS、flocking与boundary accumulation；wet particle models揭示hydrodynamic synchronization、clusters与rheology；continuum models适合instability、defects和large-scale flows。", "对细胞/组织，vertex、Voronoi、phase-field与cellular Potts模型在形变、拓扑更新、adhesion和计算成本间取舍。没有一个模型同时从分子尺度精确覆盖组织尺度，参数可识别性和实验校准是共同瓶颈。", "Figure 1的桥接箭头是概念路线；从particle model到continuum通常需kinetic closure、symmetry expansion或phenomenological constitutive law。相似pattern不证明相同微观机制，特别是dry/wet模型的momentum conservation不同。"),
sec("有效性与局限","文献截止约2019年，之后的ML、large-scale differentiable simulation和新active field theories不在覆盖内。综述选取代表方法而非系统综述，没有预注册检索或穷尽性保证。", "模型对比常跨不同nondimensionalization、boundary和observable，不能直接按计算速度或图样丰富度排名。continuum closure在强密度梯度/缺陷core可能失效；microscopic模型的参数也未必能从实验唯一反演。"),
sec("复现与资源","原文：https://arxiv.org/abs/1910.02528；期刊：https://doi.org/10.1038/s42254-020-0152-1。PDF SHA-256：9a7abe98b860bf7181d4215c800b6bd5da94c62cd556026b30ee8a6d8cb47219。复用时应按目标系统记录dry/wet、dimension、fields、conservation、boundary、noise、solver与validation observable。", "Evidence status: full-text verified review; underlying primary results not independently re-audited or reproduced."),
sec("阅读指南","先看 p.3 Figure 1锁定模型象限；再读dry microscopic/continuum与wet microscopic/continuum四段。细胞组织部分按individual-based到continuum阅读，最后用Tables I–II查方程和算法。引用具体结果时返回原始论文，不只引用本综述。")],
"figure-1-model-map.webp","Figure 1",3,"schematic","dry/wet与microscopic/continuum四象限的active-matter模型、典型场和桥接路线。","模型选择由是否保留溶剂动量及描述尺度共同决定；粗粒化箭头不代表无条件等价。","Figure 1是综述的核心taxonomy，能防止把不同守恒结构和分辨率的模型混为一谈。",
[{"label":"Active Brownian orientation","latex":r"\dot\theta=\sqrt{2D_r}\,\eta(t)","role":"represent rotational diffusion of a dry active particle","symbols":{"D_r":"rotational diffusivity","eta":"unit white noise"},"evidence":"paper.pdf p. 2, Eq. (1)","interpretation":"Together with constant self-propulsion this is a minimal kinematic model, not a resolved propulsion mechanism."}],
["paper.pdf pp. 1–3, Figure 1: modeling taxonomy","paper.pdf pp. 3–12: dry and wet models","paper.pdf pp. 12–19: cells, tissues and computational tradeoffs","source PDF SHA-256 9a7abe98b860bf7181d4215c800b6bd5da94c62cd556026b30ee8a6d8cb47219","Evidence status: full-text verified review; no independent reproduction performed."]),

card("doi-10.1038-s42256-024-00810-0","arXiv manuscript","https://arxiv.org/pdf/2307.08529","Synthetic Lagrangian turbulence by generative diffusion models","生成扩散模型合成拉格朗日湍流","ai_empirical","1bd7871c7b0bf022","Fluid Dynamics",
{"doi":"10.1038/s42256-024-00810-0","arxiv_id":"2307.08529","version":"arXiv full text","title":"Synthetic Lagrangian turbulence by generative diffusion models","authors":["T. Li","L. Biferale","F. Bonaccorso","M. A. Scarpolini","M. Buzzicotti"],"journal":"Nature Machine Intelligence","volume":"6","pages":"393–403","published":"2024-04-17","abstract":"Diffusion models generate one- and three-component Lagrangian velocity trajectories matching DNS intermittency statistics across resolved scales.","comment":"arXiv full text cross-checked with open-access version-of-record metadata"},
[sec("作者信息","作者 T. Li、L. Biferale、F. Bonaccorso、M. A. Scarpolini、M. Buzzicotti；Nature Machine Intelligence 6, 393–403 (2024)，DOI:10.1038/s42256-024-00810-0；全文取arXiv:2307.08529，共14页。核验期刊元数据与开放状态。"),
sec("研究问题","高Reynolds-number拉格朗日轨迹的velocity increments具有跨尺度anomalous scaling和极端intermittency，传统低维stochastic models难同时复现PDF、flatness与vortical geometry。论文问：无显式Navier–Stokes约束的diffusion model能否从DNS轨迹学习联合分布并高效生成统计可信的新轨迹？"),
sec("背景","训练数据来自三维homogeneous isotropic turbulence DNS，Taylor-scale Reynolds number约310；每条velocity trajectory长度约1.3 large-eddy turnover time，sampling解析Kolmogorov time。DM-1c生成单分量，DM-3c联合生成三个相关分量。", "Figure 1比较DNS与DM在多个time lag的standardized increment PDFs、velocity traces和三维轨迹局部结构；10%训练子集模型也作为data-scaling检查。"),
sec("模型与方法","forward diffusion逐步向trajectory signal加Gaussian noise，U-Net学习每个noise level的score/noise；reverse process从noise采样完整时间序列。模型直接学习fixed-length signal distribution，不积分fluid equations或particle acceleration equation。", "评估包括increment PDFs、acceleration tails/correlation、structure functions至8阶、generalized flatness、local scaling exponents、component cross-correlations与u-turn/vortex trapping。error bars来自有限ensemble统计，高阶矩对rare events尤其敏感。"),
sec("核心结果与证据","Figure 1中DM-1c/3c在resolved lags重现从近Gaussian large-scale到fat-tailed dissipative increments；三分量模型生成弯折和vortex-trapping-like轨迹。Figure 2的acceleration PDF匹配至约50–60 standard deviations，但最小尺度仍有偏差。", "Figures 4–5显示二至八阶structure functions与generalized flatness在大部分尺度吻合，DM-3c能保留cross-component intermittency。高阶统计的agreement是在DNS distribution和给定Rλ下，不是跨Reynolds number预测。", "模型偶尔生成训练样本中未见的更强events且总体tail statistics仍连续，作者称generalization。由于有限训练集本就可能漏采母分布尾部，这支持但不证明模型创造了真实新物理事件；需独立DNS/实验验证。"),
sec("有效性与局限","训练只覆盖homogeneous isotropic turbulence与单一Rλ，不能直接外推到walls、shear、inhomogeneity或inertial particles。generated trajectories不保证energy budget、Navier–Stokes consistency、multi-particle dispersion或正确conditional dynamics。", "固定length sampling限制long-time correlations；小于dissipative scale的acceleration/flatness偏差被正文承认。速度统计相符不意味着空间field可重建。生成成本比较也应包含DNS训练数据与model training，而不仅是inference。"),
sec("复现与资源","原文：https://arxiv.org/abs/2307.08529；期刊：https://doi.org/10.1038/s42256-024-00810-0。PDF SHA-256：e1f87f18d786a39010c70cb044d46b2474e825645d5e1297146df23d645bd51a。复现需固定DNS grid、Rλ、tracker interpolation、trajectory length/sampling、normalization、U-Net、noise schedule、epochs、seeds与moment estimators。", "Evidence status: full-text verified arXiv manuscript with DNS-based numerical evaluation; no independent reproduction performed."),
sec("阅读指南","先看 p.2 Figure 1建立trajectory与increment目标，再读 p.3的DNS和diffusion process；p.3–7 Figures 2–6逐项检查acceleration、flatness和scaling。最后读Discussion，将distribution matching、极端样本与物理方程一致性分开。")],
"figure-1-turbulence.webp","Figure 1",2,"comparison","DNS与单/三分量diffusion models的velocity increments、time traces和三维轨迹比较。","扩散模型重现多尺度非Gaussian速度增量，并联合生成带强弯折的三分量轨迹。","Figure 1同时覆盖主统计目标、代表轨迹和10%数据控制，是全文最完整的入口证据。",
[{"label":"Lagrangian structure function","latex":r"S_\tau^{(p)}=\langle|V(t+\tau)-V(t)|^p\rangle","role":"measure multiscale velocity-increment statistics","symbols":{"tau":"time lag","p":"moment order"},"evidence":"paper.pdf p. 8, Eq. (7)","interpretation":"Agreement across p and tau probes intermittency more stringently than visual trajectory similarity."}],
["paper.pdf pp. 1–3, Figures 1–3: DNS data and diffusion model","paper.pdf pp. 4–7, Figures 4–6: multiscale and intermittent statistics","source PDF SHA-256 e1f87f18d786a39010c70cb044d46b2474e825645d5e1297146df23d645bd51a","Evidence status: full-text verified arXiv manuscript; no independent reproduction performed."]),

card("doi-10.1038-s42256-024-00918-3","version of record","https://discovery.ucl.ac.uk/id/eprint/10200652/1/s42256-024-00918-3.pdf","Efficient rare event sampling with unsupervised normalizing flows","用无监督归一化流高效采样稀有事件","numerical","dbc55830c3a61a1d","Active Matter",
{"doi":"10.1038/s42256-024-00918-3","version":"version of record","title":"Efficient rare event sampling with unsupervised normalizing flows","authors":["Solomon Asghar","Qing-Xiang Pei","Giorgio Volpe","Ran Ni"],"journal":"Nature Machine Intelligence","volume":"6","pages":"1370–1381","published":"2024-11-19","abstract":"FlowRES trains normalizing-flow proposals inside path-space MCMC without prior transition data or collective variables for passive and active Brownian benchmarks.","comment":"Open-access repository copy of version of record; no Crossref update relation found"},
[sec("作者信息","作者 Solomon Asghar、Qing-Xiang Pei、Giorgio Volpe、Ran Ni；Nature Machine Intelligence 6, 1370–1381 (2024)，DOI:10.1038/s42256-024-00918-3。核验UCL开放仓储18页期刊版、代码与Crossref；未发现关联更正或撤稿。"),
sec("研究问题","metastable transitions随barrier增大呈指数稀少，直接Langevin integration几乎看不到；TPS仍可能因proposal不能连接端点而失效。论文问：能否在path space中用normalizing flow从MCMC已接受样本自举训练非局域proposal，无需预先transition data或手工collective variable，并保持对更稀事件的效率？"),
sec("背景","路径W含固定初态到终态时间序列，target distribution是满足动力学action并到达目标区域的transition-path ensemble。FlowRES以Gaussian basis经invertible affine coupling flow生成proposal，再用Metropolis–Hastings acceptance校正，因此network只改善proposal，不替代目标权重。", "Figure 1展示two-particle rare path和训练闭环：当前accepted paths训练flow，flow proposal经MCMC接受后更新distribution，逐步逼近target。"),
sec("模型与方法","基准含passive Brownian double well、带不可穿墙或双通道potential，以及active Brownian particles的非平衡转移。active case同时生成position与periodic orientation，角噪声用von Mises base处理。", "作者与direct integration、TPS比较Jensen–Shannon distance、target paths per proposal、wall time/force evaluations及barrier scaling。多个parallel chains减少相关性；normalizing flow训练本身计入成本的方式需结合Methods理解。"),
sec("核心结果与证据","Figure 2中barrier从1增至18 kBT_eff时，direct integration与TPS所需proposals快速增加，而FlowRES生成收敛path ensemble的成本近似保持常数；marginal path densities与直接模拟在可比较barrier吻合。", "Figure 3的active Brownian benchmark在非平衡且orientation隐藏于简单位置CV时仍重现transition ensemble；Figure 4的双通道potential同时发现两条route，不需要事先指定channel coordinate。", "所谓无监督是没有预先rare-event dataset或label；算法仍知道初/终区域、dynamics和path action，并从MCMC acceptance获得目标信号。近常数效率只在所测低维benchmark/barrier范围成立，不是维度无关复杂度证明。"),
sec("有效性与局限","测试主要是一到两粒子的低维Brownian systems，normalizing flow对长路径、多粒子与stiff molecular coordinates的训练/内存可能恶化。固定path length与已知transition endpoints排除了未知事件发现问题。", "MH correction保证stationary target需proposal support、detailed implementation和chain mixing；有限JSD不能排除mode遗漏。non-equilibrium action、periodic angles和constraints必须正确编码。多route样例支持能力但不能证明任意topology都被覆盖。"),
sec("复现与资源","期刊：https://doi.org/10.1038/s42256-024-00918-3；代码：https://github.com/SolomonAsghar/FlowRES。PDF SHA-256：2be64689df4e3e076fbfe121ca464caf4b2b6a436b1cd15ba46e0a0b92cd873c。复现需固定SDE discretization、path length、endpoint sets、flow layers、base distribution、parallel chains、MH ratio、training schedule、barrier与JSD estimator。", "Evidence status: full-text verified version of record with simulated benchmarks; no independent reproduction performed."),
sec("阅读指南","先看 p.2 Figure 1理解flow proposal仍受MH校正；再读 pp.3–5 Figure 2的barrier scaling。active和multi-route证据看 pp.6–8 Figures 3–4，最后读Methods核查path action、acceptance与成本口径，避免把benchmark scaling写成普适保证。")],
"figure-1-flowres.webp","Figure 1",2,"schematic","稀有转移路径、Gaussian basis、normalizing-flow proposal与MCMC接受后的FlowRES训练循环。","FlowRES在path-space MCMC内学习非局域proposal，目标分布仍由动力学权重和接受率校正。","Figure 1明确区分生成网络、MCMC校正与target path ensemble，是理解算法有效性的关键。",
[{"label":"Active Brownian dynamics","latex":r"\dot{\mathbf r}_i=v_0\mathbf u_i-\mu\nabla_iU+\sqrt{2D}\,\boldsymbol\xi_i","role":"define a non-equilibrium rare-event benchmark","symbols":{"v_0":"self-propulsion speed","U":"potential and interactions","D":"translational diffusion"},"evidence":"paper.pdf p. 2, Eq. (1)","interpretation":"The active drive breaks equilibrium structure, so the sampler must use the correct path probability rather than a Boltzmann coordinate density."}],
["paper.pdf p. 2, Figure 1: FlowRES workflow","paper.pdf pp. 3–5, Figure 2: barrier-crossing efficiency","paper.pdf pp. 6–8, Figures 3–4: active and multi-route tests","source PDF SHA-256 2be64689df4e3e076fbfe121ca464caf4b2b6a436b1cd15ba46e0a0b92cd873c","Evidence status: full-text verified version of record; no independent reproduction performed."])
]

def main()->int:
    OUT.mkdir(parents=True,exist_ok=True); ids=[]
    for c in CARDS:
        pid=str(c["arxiv_id"]); (OUT/f"{pid}.json").write_text(json.dumps(c,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); ids.append(pid)
    print(json.dumps({"installed":ids},ensure_ascii=False)); return 0
if __name__=="__main__": raise SystemExit(main())
