#!/usr/bin/env python3
"""Install full-text v2.3 Collection cards for backfill batch 015."""

from __future__ import annotations

import json
from pathlib import Path

from install_full_collection_batch_014 import figure, meta, provenance, sec

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "collection_cards"


CARDS: list[dict[str, object]] = [
    {
        "arxiv_id": "2410.04263", "source_version": "v3",
        "source_pdf": "https://arxiv.org/pdf/2410.04263",
        "title_en": "DeFoG: Discrete Flow Matching for Graph Generation",
        "title_zh": "DeFoG：用于图生成的离散流匹配",
        "curation_status": "full_text_verified", "card_standard_version": "2.3",
        "paper_profile": "theory_numerics", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["af0b5a5bd95c883c"], ["Flow Matching"]),
        "verified_metadata": meta("2410.04263", "v3", "DeFoG: Discrete Flow Matching for Graph Generation", ["Yiming Qin", "Manuel Madeira", "Dorina Thanou", "Pascal Frossard"], ["cs.LG"], "cs.LG", "2024-10-05T18:52:54Z", "Discrete flow matching decouples graph noising from CTMC sampling and exposes time distortion, rate-matrix and guidance choices at inference."),
        "sections": [
            sec("作者信息", r"作者：Yiming Qin、Manuel Madeira、Dorina Thanou、Pascal Frossard；arXiv:2410.04263v3，ICML 2025。全文 59 页，覆盖 synthetic graphs、QM9/GuacaMol/MOSES molecules 与 digital pathology conditional generation。"),
            sec("研究问题", r"离散 graph diffusion 往往把训练 noise schedule 与推理 rate matrix 绑定，任何采样改动都可能要求重训。论文问：能否只学习 clean-graph posterior，再在推理时独立选择 time distortion、CTMC stochasticity 与 target guidance，同时保持 node-permutation symmetry 和可控的分布误差？"),
            sec("背景", r"图被写成 node labels 与 edge labels 的 categorical variables。forward path 直接规定 (p_{t|1}(z_t|z_1))，reverse CTMC 的 marginal rate 则对 learned posterior (p_{1|t}^\theta(z_1|z_t)) 做平均；网络用逐变量 cross-entropy 学 clean endpoint。", r"Figure 1 左侧对比 diffusion 的耦合训练/采样与 DeFoG 的解耦；右侧展示从 initial noise graph 经离散跳变逐步去噪到目标 graph。"),
            sec("模型与方法", r"基础 path 是 data 与 noise categorical laws 的线性插值；sampling 通过 Euler-discretized CTMC 更新。训练/推理均可用 monotone distortion (t'=f(t)) 重分配时间区域；推理还可加入满足 detailed balance 的额外 rate (R_t^{DB}) 或 target-guidance rate (R_t^\omega)。", r"graph transformer 对 node permutation equivariant，并用 RRWP positional features 提升超越基本 message passing 的表达力。Theorem 1 把 CE loss 连接到 rate-matrix estimation error upper bound；Theorem 2 再把 total-variation deviation 分解为有限步 discretization 与 rate estimation 两部分。"),
            sec("核心结果与证据", r"Figure 1 是机制图：训练只学习 endpoint posterior，推理侧的 distortion、rate design 和 guidance 成为可替换模块；这正是效率改进的来源，而不是把连续坐标硬套到图上。", r"synthetic Planar 数据的 valid-unique-novel（V.U.N.）达到 99.5%。作者报告 DeFoG 常用 diffusion baselines 仅 5–10% 的 sampling steps；在 GuacaMol 用 25 steps 已超过 500-step DiGress。", r"target guidance 可显著提高 validity，但过强会降低 novelty 和 graph-statistics ratio；最佳 training/sampling distortion 又随 dataset 改变。因而论文展示的是可调设计空间，不是一个跨数据集统一最优 schedule。"),
            sec("有效性与局限", r"理论界限依赖 posterior/rate estimation assumptions，并显式包含有限 (K) 的 discretization error；它不保证一个有限网络用 25 steps 精确复制真实 graph law。V.U.N. 接近 1 只检查指定 validity、uniqueness、novelty，不等同于科学用途或 chemical quality。", r"rate-matrix/guidance 搜索使用验证数据和 dataset-specific choices；不同 baselines 的 steps、architectures 和 metrics protocol 不完全等价。fully connected edge variables 与 transformer attention 对大图仍有二次尺度压力。"),
            sec("复现与资源", r"原文：https://arxiv.org/abs/2410.04263；代码：https://github.com/manuelmlmadeira/DeFoG。全文 59 页，PDF SHA-256：8baeebbfc76eea8808aa67c7b37460ce46d506595de1a3dbb4c5177a507f6aba。", r"复现需固定 categorical encoding、noise distribution、training/sampling distortions、Euler steps、(R_t^{DB})、guidance magnitude、RRWP features、five-run sampling seeds 与各数据集 validity/FCD/MMD 实现。", r"Evidence status: full-text verified; no independent reproduction performed."),
            sec("阅读指南", r"先看 Figure 1 与 Eqs. (2)–(6)，分清 learned posterior、conditional rate 与 marginal CTMC；再读 Theorems 1–2 的误差链。随后用 Figure 2/Appendix ablations 检查 distortion、guidance、stochasticity 的 trade-off，最后才比较 Tables 1–2。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/2410.04263/figure-1-defog-overview.webp", "label": "Figure 1", "visual_type": "schematic", "evidence": "paper.pdf p. 2, Figure 1", "alt_text": "耦合 diffusion 与解耦 DeFoG 训练流程，以及离散 graph denoising trajectory。", "caption": "DeFoG 只在训练中学习 clean endpoint posterior，把时间扭曲、rate matrix 与 guidance 留给推理阶段。", "selection_rationale": "Figure 1 是全文核心训练-采样解耦机制图，优先于 V.U.N. 表格。"},
        "figure_refs": [figure("2410.04263", "figure-1-defog-overview.webp", "Figure 1", 2, "show training-sampling decoupling and graph denoising", "DeFoG workflow and discrete graph trajectory.", "Posterior learning is shared while the sampler design remains adjustable.", "Decoupling enlarges the design space; finite-step fidelity remains bounded rather than exact.")],
        "equation_refs": [
            {"label": "Endpoint-posterior training", "latex": r"\mathcal L_{\rm CE}(\theta)=-\mathbb E_{t,z_1,z_t}\log p_{1|t}^{\theta}(z_1\mid z_t)", "role": "learn the clean categorical graph endpoint", "symbols": {"z_t": "noised node or edge state", "z_1": "clean endpoint"}, "evidence": "paper.pdf pp. 3–5 and Appendix D", "interpretation": "The learned posterior can be inserted into multiple CTMC rate designs without retraining."},
            {"label": "Time distortion", "latex": r"t'=f(t),\qquad \phi_{t'}(t')=\phi_t(f^{-1}(t'))\left|\frac{d f^{-1}}{dt'}\right|", "role": "reallocate training samples or sampling steps in time", "symbols": {"f": "monotone distortion", "phi": "time density"}, "evidence": "paper.pdf p. 17, Appendix B.1", "interpretation": "The same mathematical transformation has different roles during training and sampling, and its optimum is dataset dependent."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–8: formulation, architecture and main experiments", "paper.pdf pp. 33–44: rate and generated-distribution error bounds", "source PDF SHA-256 8baeebbfc76eea8808aa67c7b37460ce46d506595de1a3dbb4c5177a507f6aba", "Evidence status: full-text verified; no independent reproduction performed."],
    },
    {
        "arxiv_id": "2410.06885", "source_version": "v3", "source_pdf": "https://arxiv.org/pdf/2410.06885",
        "title_en": "F5-TTS: A Fairytaler that Fakes Fluent and Faithful Speech with Flow Matching", "title_zh": "F5-TTS：基于流匹配的流畅、忠实语音合成",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "ai_empirical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["5a5c48abbfd99710"], ["Flow Matching"]),
        "verified_metadata": meta("2410.06885", "v3", "F5-TTS: A Fairytaler that Fakes Fluent and Faithful Speech with Flow Matching", ["Yushen Chen", "Zhikang Niu", "Ziyang Ma", "Keqi Deng", "Chunhui Wang", "Jian Zhao", "Kai Yu", "Xie Chen"], ["eess.AS", "cs.SD"], "eess.AS", "2024-10-09T13:46:34Z", "A non-autoregressive DiT uses text-guided speech infilling, ConvNeXt text refinement and inference-only Sway Sampling."),
        "sections": [
            sec("作者信息", r"作者：Yushen Chen、Zhikang Niu、Ziyang Ma、Keqi Deng、Chunhui Wang、Jian Zhao、Kai Yu、Xie Chen；arXiv:2410.06885v3。全文 18 页；base model 336M parameters，训练数据约 95k h 英中 Emilia speech。"),
            sec("研究问题", r"E2 TTS 已证明把字符 padding 到 mel length、以 speech infilling 做无显式 duration/alignment 的非自回归 TTS 可行，但 convergence 慢且长文本 alignment 不稳。论文问：能否保持“text in, speech out”的极简 pipeline，同时提高对齐鲁棒性并减少 ODE function evaluations？"),
            sec("背景", r"模型在 mel-spectrogram space 学 conditional flow，从 Gaussian noise 到目标 speech；给定 prompt speech/text 后只生成未遮挡区之后的 mel，再经 Vocos/BigVGAN vocoder。没有 phoneme duration model 不代表没有长度信息：推理时仍需估计目标 duration。", r"Figure 1 并排展示训练的随机 speech mask/CFM loss 与推理的 prompt continuation、CFG、Sway timesteps 和 ODE solver。"),
            sec("模型与方法", r"字符序列用 filler token 扩到 acoustic sequence 长度，先经 ConvNeXt V2，再与 noisy/masked mel concatenation 输入 DiT。训练 (t\sim U[0,1])；Sway Sampling 仅在推理把 uniform (u) 映射为非均匀 (t=f_{\rm sway}(u;s))，默认 (s=-1) 加密早期 steps。", r"作者解释早期 flow 决定语音轮廓与 text alignment，后期补细节，因此左偏 sampling 可用更少 NFE 保持可懂度；CFG 需要 conditional/unconditional 两次 forward，实际成本不能只看 NFE。"),
            sec("核心结果与证据", r"Figure 1 把关键简化画清楚：同一个 DiT 完成 infilling flow，ConvNeXt 只为 text 建模，推理侧 schedule 可不重训替换。", r"LibriSpeech-PC test-clean 上，32 NFE 的 WER/SIM-o/RTF 为 2.42/0.66/0.31；16 NFE 为 2.53/0.66/0.15。RTF 是 RTX 3090 上生成 10 s speech 的测量，不能当硬件无关常数。", r"Seed-TTS test-en 的 16/32 NFE WER 为 1.89/1.83，test-zh 为 1.74/1.56；Sway ablations 支持其也能改善 E2 TTS，但不同 solver、vocoder 与 ASR evaluator 会改变数值。"),
            sec("有效性与局限", r"论文明确指出 mel sequence 仍远长于 text，计算瓶颈没有从表示层消失；模型也缺少 emotion 等 paralinguistic fine control。zero-shot voice cloning 带来冒用风险，WER/SIM/MOS 不能覆盖身份授权和滥用。", r"对商业/闭源 baselines 有些分数来自原论文，训练数据量、vocoder、prompt 与 ASR/SV evaluators 不完全一致；CFG doubles forward evaluation。项目网页样例不能代替盲听统计，且 reference prompt 质量强烈影响输出。"),
            sec("复现与资源", r"原文：https://arxiv.org/abs/2410.06885；代码/模型：https://github.com/SWivid/F5-TTS。全文 18 页，PDF SHA-256：ee2aa766bd6ad9395967dfdaed70f948713cba9859d6fcbb6283908714b899f3。", r"复现需固定 text normalization/tokenization、mel/Vocos or BigVGAN、mask policy、ConvNeXt/DiT config、EMA、CFG=2、Sway (s=-1)、Euler solver/NFE、duration estimate、prompt 与 WER/SIM evaluator。", r"Evidence status: full-text verified; no independent reproduction performed."),
            sec("阅读指南", r"先看 Figure 1 和 Eq. (5)，确认 filler padding 与 infilling condition；再读 Eq. (7) 及 Figure 3 理解 Sway 只是 timestep reparameterization。最后逐行读 Tables 1–2，并把 WER、speaker similarity、subjective MOS 与 hardware RTF 分开。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/2410.06885/figure-1-f5tts-overview.webp", "label": "Figure 1", "visual_type": "schematic", "evidence": "paper.pdf p. 2, Figure 1", "alt_text": "F5-TTS training 与 inference 的双栏 architecture diagram。", "caption": "字符 padding、ConvNeXt text refinement、DiT infilling 与 inference-only Sway Sampling 构成完整 F5-TTS pipeline。", "selection_rationale": "Figure 1 是最重要的方法总览，优先于 WER/RTF 表格。"},
        "figure_refs": [figure("2410.06885", "figure-1-f5tts-overview.webp", "Figure 1", 2, "explain the training and inference pipeline", "F5-TTS training and inference blocks.", "The same flow model learns masked speech completion and is sampled with a nonuniform time grid.", "The diagram omits evaluator and hardware dependence of reported quality and speed.")],
        "equation_refs": [
            {"label": "OT conditional flow matching", "latex": r"\mathcal L_{\rm CFM}=\mathbb E\left\|v_t((1-t)x_0+t x_1)-(x_1-x_0)\right\|^2", "role": "train the mel-spectrogram velocity field", "symbols": {"x0": "Gaussian mel noise", "x1": "target mel"}, "evidence": "paper.pdf p. 3, Eq. (3)", "interpretation": "The DiT predicts a continuous transport velocity under text and prompt-speech conditioning."},
            {"label": "Sway Sampling", "latex": r"f_{\rm sway}(u;s)=u+s\left[\cos\!\left(\frac{\pi u}{2}\right)-1+u\right]", "role": "redistribute ODE evaluation times without retraining", "symbols": {"u": "uniform grid variable", "s": "sway coefficient"}, "evidence": "paper.pdf p. 5, Eq. (7)", "interpretation": "Negative s places more evaluations near the noise-dominated start where alignment is established."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–6: architecture, CFM and Sway Sampling", "paper.pdf pp. 7–9: benchmarks, ablations and limitations", "source PDF SHA-256 ee2aa766bd6ad9395967dfdaed70f948713cba9859d6fcbb6283908714b899f3", "Evidence status: full-text verified; no independent reproduction performed."],
    },
    {
        "arxiv_id": "2410.12119", "source_version": "v3", "source_pdf": "https://arxiv.org/pdf/2410.12119",
        "title_en": "Scaling Laws for Post Training Quantized Large Language Models", "title_zh": "后训练量化大语言模型的缩放律",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "ai_empirical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["effa8dc9d83b5b5f"], ["Scaling Laws"]),
        "verified_metadata": meta("2410.12119", "v3", "Scaling Laws for Post Training Quantized Large Language Models", ["Zifei Xu", "Alexander Lan", "Wanzin Yazar", "Tristan Webb", "Sayeh Sharify", "Xin Wang"], ["cs.LG", "cs.CL"], "cs.LG", "2024-10-15T23:34:22Z", "Post-training quantization loss is predicted from pretrained loss, local radial flatness, tensor format, SQNR and the PTQ algorithm."),
        "sections": [
            sec("作者信息", r"作者：Zifei Xu、Alexander Lan、Wanzin Yazar、Tristan Webb、Sayeh Sharify、Xin Wang；arXiv:2410.12119v3。全文 19 页，研究 5 个 LLM families、36 种 MX tensor formats，并以 Pythia-1B 和 MPT-7B 做 held-out family tests。"),
            sec("研究问题", r"pretraining NLL 随参数量近似可预测，但量化后 loss 可能在相邻 bit-width 间突变，单靠 model size/bit count 无法选择部署点。论文问：能否把 PTQ 看作 weight-space perturbation，并用局部 loss landscape、SQNR、format geometry 与 GPTQ effect 恢复可预测性？"),
            sec("背景", r"量化写作 (w\to Q(w)=w+\Delta w)。若 minima 近似二次，Hessian 已足够；实际 radial NLL profile 却先平坦、随后快于 quadratic 上升、最后 plateau，因此 20 dB 以下的简单 Taylor fit 常失败。", r"Figure 1 左侧复现 float NLL 对 weight count 的 family scaling，右侧把随机方向 radial landscape 与 Taylor approximations 放在一起，直接显示 PTQ 可预测性为何需要 landscape shape。"),
            sec("模型与方法", r"作者以 (\mathrm{SQNR}=20\log_{10}(\|w\|/\|Q(w)-w\|)) 统一比较不同维数；对每个 family/size/format 测 RTN 与 enhanced GPTQ 前后 loss，并提取 RTN 点的 radial slope。", r"random-forest inputs 包括 parameter count、float NLL、RTN SQNR/NLL、landscape slope、precision/exponent bits/block size；训练来自 GPT-2、OPT、BLOOM、Llama-2/3，测试留出 Pythia-1B、MPT-7B。"),
            sec("核心结果与证据", r"Figure 1 把两条尺度关系并置：更大模型通常 float loss 更低，同 family 内也通常有更宽 flat basin；因此同一 SQNR perturbation 对不同 model size 的 NLL 代价不同。", r"36 种 MX formats 覆盖 block size 16–128、element precision 2–6 bits。GPTQ 可同时降低 SQNR（离原 weight 更远）和 NLL，且 mxint3 可能显著改善而 2/4/6 bit 仅小幅改变；这排除了“更小 perturbation 必然更好”的单变量解释。", r"held-out Pythia/MPT prediction 与 observation 接近对角线，支持 landscape features 跨 family 有信息；Figure 6 给出 memory–NLL Pareto frontier。但论文没有把一个封闭解析 power law 拟合为普适定律，最终 predictor 是有限数据 random forest。"),
            sec("有效性与局限", r"最大模型 13B，远小于当前最大 LLM；主要指标是 WikiText-2 validation NLL，不能直接外推到 instruction following、reasoning 或 downstream accuracy。held-out models 只有两个，且均仍属于 decoder-only transformer。", r"128 calibration sequences、enhanced GPTQ、MX formats 和 family-specific tokenizers 都会改变结果。随机径向 landscape 不是 quantization direction 的完整 Hessian geometry；random forest 可预测不等于揭示因果缩放机制。"),
            sec("复现与资源", r"原文：https://arxiv.org/abs/2410.12119。全文 19 页，PDF SHA-256：7bb63fd9519596f3deca175ad21a10c6109f6376eb02d9925d4547a701e7b8d3。", r"复现需固定 exact checkpoints/tokenizers、WikiText-2 split、128 calibration sequences、MX block/element formats、RTN/GPTQ damping grid、half/single precision、radial directions/repeats 与 random-forest split/hyperparameters。", r"Evidence status: full-text verified; no independent reproduction performed."),
            sec("阅读指南", r"先看 Figures 1–2，把 model-size scaling 与 radial flatness 分开；再读 SQNR 定义和 Figure 3，理解 GPTQ 为何可能降低 SQNR 却改善 NLL。最后审查 Figure 5 的 held-out design 与 Figure 6 Pareto frontier，并保留 13B/WikiText-2 边界。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/2410.12119/figure-1-loss-landscape.webp", "label": "Figure 1", "visual_type": "data_plot", "evidence": "paper.pdf p. 2, Figure 1", "alt_text": "float NLL scaling curve 与 weight-space radial loss landscape。", "caption": "量化损失同时取决于 float scaling 与局部 basin 形状；bit count 本身不足以预测 PTQ 后 NLL。", "selection_rationale": "文章没有机制示意图；Figure 1 是最重要的物理景观可视化，优先于最终 Pareto 表。"},
        "figure_refs": [figure("2410.12119", "figure-1-loss-landscape.webp", "Figure 1", 2, "connect model scaling to local loss geometry", "Float-loss scaling and radial landscape plots.", "A quantization perturbation of fixed relative norm can cross different basin shoulders as model scale changes.", "Random radial profiles summarize typical local geometry, not all structured quantization directions.")],
        "equation_refs": [
            {"label": "Signal-to-quantization-noise ratio", "latex": r"\operatorname{SQNR}(w)=20\log_{10}\frac{\|w\|_2}{\|Q(w)-w\|_2}", "role": "normalize quantization displacement across model sizes", "symbols": {"Q": "tensor quantizer", "w": "flattened quantized weights"}, "evidence": "paper.pdf p. 4", "interpretation": "SQNR measures displacement magnitude but cannot by itself predict loss without local landscape geometry."},
            {"label": "Local loss expansion", "latex": r"\operatorname{NLL}(w+\Delta w)=\operatorname{NLL}(w)+g^T\Delta w+\frac12\Delta w^T H\Delta w+O(\|\Delta w\|^3)", "role": "motivate landscape-aware PTQ scaling", "symbols": {"g": "gradient", "H": "Hessian"}, "evidence": "paper.pdf p. 3", "interpretation": "Measured landscapes become step-like beyond the local basin, so low-order expansions fail for aggressive quantization."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–6: landscape, SQNR, GPTQ and predictor", "paper.pdf pp. 7–8: experiment protocol, Pareto frontier and limitations", "source PDF SHA-256 7bb63fd9519596f3deca175ad21a10c6109f6376eb02d9925d4547a701e7b8d3", "Evidence status: full-text verified; no independent reproduction performed."],
    },
    {
        "arxiv_id": "2410.13027", "source_version": "v1", "source_pdf": "https://arxiv.org/pdf/2410.13027",
        "title_en": "Geometric Trajectory Diffusion Models", "title_zh": "几何轨迹扩散模型",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "theory_numerics", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["9b4652cee4d4eb75"], ["Generative Models"]),
        "verified_metadata": meta("2410.13027", "v1", "Geometric Trajectory Diffusion Models", ["Jiaqi Han", "Minkai Xu", "Aaron Lou", "Haotian Ye", "Stefano Ermon"], ["cs.CV", "cs.LG"], "cs.CV", "2024-10-16T20:36:41Z", "GeoTDM generates joint spatiotemporal geometric trajectories using SE(3)-equivariant denoising kernels and a learnable equivariant conditional prior."),
        "sections": [
            sec("作者信息", r"作者：Jiaqi Han、Minkai Xu、Aaron Lou、Haotian Ye、Stefano Ermon；arXiv:2410.13027v1。全文 30 页，实验含 N-body、MD17、ETH-UCY，模型称 GeoTDM，backbone 称 EGTN。"),
            sec("研究问题", r"静态 3D generative models 保证 \(SE(3)\) symmetry，却没有建模同一粒子跨时间的 correspondence；frame-to-frame rollout 又积累误差。论文问：能否直接生成整条 \(T\times N\times3\) trajectory，并让 unconditional density invariant、conditional law equivariant？"),
            sec("背景", r"对物理等价的整体旋转/平移，unconditional probability 应不变；若 condition trajectory 同样变换，预测轨迹应协变。单纯 isotropic Gaussian prior 对 unconditional case 合适，但 conditional forecasting 还需 prior 随 observed geometry 一起变换。", r"Figure 1 展示 trajectory-level forward diffusion、EGTN reverse denoising 与由 condition 构造的 equivariant prior。"),
            sec("模型与方法", r"EGTN 交替使用 \(SE(3)\)-equivariant graph convolution 表示同一 frame 的 interactions，以及 temporal attention 表示同一 node 跨 frames 的相关；relative temporal embeddings 给出 time-shift invariance。", r"conditional prior 由 lightweight EGTN 学习，可包含 center-of-mass 和 point-wise priors。理论说明：invariant prior 加 equivariant Markov kernels 保持 invariant marginal；conditional prior/kernel 同时 equivariant 时保持 conditional equivariance。"),
            sec("核心结果与证据", r"Figure 1 是模型的物理结构图：噪声作用于整条轨迹而非逐帧 rollout，condition 同时进入 prior 与 reverse kernel；因此 temporal joint distribution 与 geometry symmetry 在同一生成过程中处理。", r"MD17 conditional forecasting 相对 EqMotion 的平均 ADE/FDE 改善 23.1%/15.3%，八个 molecules 均最低；N-body Particle/Spring/Gravity 的 ADE 为 0.110/0.0030/0.256。", r"unconditional Charged Particle 的 marginal/classification/prediction scores 为 0.0055/0.556/0.00978。ablation 中去 equivariance 把 Charged ADE/FDE 从 0.110/0.258 恶化至 0.251/0.542；100-step GeoTDM sampling 约比 EGVAE 慢 10×。"),
            sec("有效性与局限", r"MD17 是短小分子的有限 DFT trajectories；模型学习数据分布，不积分 force field，也不保证 energy conservation、symplecticity、detailed balance 或绝对 kinetics。ADE/FDE 与 discriminative scores 不能证明 rare-event rates 正确。", r"diffusion cost 随 steps 与 trajectory length 增长；论文建议分段 composition，但这会重新引入跨段 drift。symmetry theorem 保证群变换一致性，不保证 learned dynamics 满足真实方程。"),
            sec("复现与资源", r"原文：https://arxiv.org/abs/2410.13027；代码：https://github.com/hanjq17/GeoTDM。全文 30 页，PDF SHA-256：cd17681726d0a392dffdd7a2dbe29e4a93b67f1744197308faea976dcca43b58。", r"复现需固定 trajectory splits/frames、graph edges/features、CoM removal、diffusion steps/schedule、EGTN depth/attention、prior parameterization、five-run seeds、ADE/FDE sampling \(K\) 与 generation-score classifiers。", r"Evidence status: full-text verified; no independent reproduction performed."),
            sec("阅读指南", r"先看 Figure 1 与 symmetry definitions；再读 Section 4 的 invariant/equivariant kernel propositions和 prior construction。随后对照 Tables 1–4 与 Table 6 ablations，最后读 runtime Table 9，把 distribution quality 与 physical simulator fidelity 分开。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/2410.13027/figure-1-geotdm-overview.webp", "label": "Figure 1", "visual_type": "schematic", "evidence": "paper.pdf p. 2, Figure 1", "alt_text": "多帧几何轨迹的 forward diffusion、equivariant prior 与 EGTN reverse process。", "caption": r"GeoTDM 对整条几何轨迹扩散，并让 condition-dependent prior 与 reverse kernel 同时满足 \(SE(3)\) equivariance。", "selection_rationale": "Figure 1 是全文时空扩散与几何对称性的核心机制图，优先于单数据集误差表。"},
        "figure_refs": [figure("2410.13027", "figure-1-geotdm-overview.webp", "Figure 1", 2, "show trajectory-level equivariant diffusion", "Forward corruption and EGTN reverse denoising across frames.", "The model generates the joint trajectory instead of recursively predicting one frame.", "Equivariance constrains symmetry but does not enforce conservation laws.")],
        "equation_refs": [
            {"label": "SE(3)-equivariant trajectory map", "latex": r"f(h,Rx+r)=(h',Rx'+r)\quad\text{when}\quad f(h,x)=(h',x')", "role": "state the geometric symmetry constraint", "symbols": {"R": "3D rotation", "r": "translation"}, "evidence": "paper.pdf p. 4, equivariance section", "interpretation": "Rotating or translating every frame rotates or translates the generated trajectory consistently."},
            {"label": "Trajectory diffusion objective", "latex": r"\mathcal L_{\rm simple}=\mathbb E_{x_0,\epsilon,\tau}\lambda(\tau)\|\epsilon-\epsilon_\theta(x_\tau,\tau)\|^2", "role": "train reverse denoising on the entire trajectory tensor", "symbols": {"x_tau": "noised geometric trajectory", "epsilon": "Gaussian noise"}, "evidence": "paper.pdf p. 4, Eq. (1)", "interpretation": "Equivariant EGTN parameterization makes the standard noise-prediction loss respect trajectory geometry."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–6: geometric trajectory diffusion and symmetry construction", "paper.pdf pp. 7–10: N-body, MD17, pedestrian and ablation results", "source PDF SHA-256 cd17681726d0a392dffdd7a2dbe29e4a93b67f1744197308faea976dcca43b58", "Evidence status: full-text verified; no independent reproduction performed."],
    },
    {
        "arxiv_id": "2410.13720", "source_version": "v2", "source_pdf": "https://arxiv.org/pdf/2410.13720",
        "title_en": "Movie Gen: A Cast of Media Foundation Models", "title_zh": "Movie Gen：一组媒体基础模型",
        "curation_status": "full_text_verified", "card_standard_version": "2.3", "paper_profile": "ai_empirical", "style_reference": "physicist_daily_arxiv",
        "provenance": provenance(["10188947fb0a358a"], ["Video Generation"]),
        "verified_metadata": meta("2410.13720", "v2", "Movie Gen: A Cast of Media Foundation Models", ["Adam Polyak", "Amit Zohar", "Andrew Brown", "Andros Tjandra", "Animesh Sinha", "Ann Lee", "Apoorv Vyas", "Bowen Shi", "Chih-Yao Ma", "Ching-Yao Chuang", "David Yan", "Dhruv Choudhary", "Dingkang Wang", "Geet Sethi", "Guan Pang", "Haoyu Ma", "Ishan Misra", "Ji Hou", "Jialiang Wang", "Kiran Jagadeesh", "Kunpeng Li", "Luxin Zhang", "Mannat Singh", "Mary Williamson", "Matt Le", "Matthew Yu", "Mitesh Kumar Singh", "Peizhao Zhang", "Peter Vajda", "Quentin Duval", "Rohit Girdhar", "Roshan Sumbaly", "Sai Saketh Rambhatla", "Sam Tsai", "Samaneh Azadi", "Samyak Datta", "Sanyuan Chen", "Sean Bell", "Sharadh Ramaswamy", "Shelly Sheynin", "Siddharth Bhattacharya", "Simran Motwani", "Tao Xu", "Tianhe Li", "Tingbo Hou", "Wei-Ning Hsu", "Xi Yin", "Xiaoliang Dai", "Yaniv Taigman", "Yaqiao Luo", "Yen-Cheng Liu", "Yi-Chiao Wu", "Yue Zhao", "Yuval Kirstain", "Zecheng He", "Zijian He", "Albert Pumarola", "Ali Thabet", "Artsiom Sanakoyeu", "Arun Mallya", "Baishan Guo", "Boris Araya", "Breena Kerr", "Carleigh Wood", "Ce Liu", "Cen Peng", "Dimitry Vengertsev", "Edgar Schonfeld", "Elliot Blanchard", "Felix Juefei-Xu", "Fraylie Nord", "Jeff Liang", "John Hoffman", "Jonas Kohler", "Kaolin Fire", "Karthik Sivakumar", "Lawrence Chen", "Licheng Yu", "Luya Gao", "Markos Georgopoulos", "Rashel Moritz", "Sara K. Sampson", "Shikai Li", "Simone Parmeggiani", "Steve Fine", "Tara Fowler", "Vladan Petrovic", "Yuming Du"], ["cs.CV", "cs.AI", "cs.LG", "eess.IV"], "cs.CV", "2024-10-17T16:22:46Z", "A family of video, personalization, editing and audio models scales flow-matching Transformers on compressed media tokens."),
        "sections": [
            sec("作者信息", r"Movie Gen Team（Adam Polyak 等 86 位作者）；arXiv:2410.13720v2。全文 97 页。最大 video Transformer 为 30B parameters，audio model 为 13B；论文是系统报告而非单一算法消融。"),
            sec("研究问题", r"视频生成需同时扩展时空 context、分辨率、identity consistency、instruction editing 与同步音频。论文问：能否以统一的 flow-matching Transformer/latent pipeline 训练基础 video model，再通过 post-training 分化出 personalization、editing 和 video-to-audio 能力？"),
            sec("背景", r"原始 1080p 视频 token 数过大，Movie Gen 先用 temporal autoencoder 把时间/空间各压缩 8 倍，在 768 px latent 上生成，再用独立 spatial upsampler 到 1080p。最大 73K-token context 对应 256 frames，即 16 s、16 FPS。", r"Figure 1 直接展示 text-to-video、reference-image personalization、instruction editing 和 synchronized video-to-audio，是整套系统能力边界的最重要可视化。"),
            sec("模型与方法", r"30B Llama-style Transformer 以 flow matching 从 Gaussian latent 生成 image/video，线性路径写作 \(x_t=(1-t)\epsilon+t x\)；训练从 text-to-image 开始，再 joint image-video progressive resolution pretraining，最后用高 aesthetic/motion 数据 finetune。数据规模为约 100M video-text pairs 与 1B image-text pairs。", r"TAE 的时间压缩为 \(T_{\rm latent}=\lceil T_{\rm RGB}/8\rceil\)。personalization 用 reference identity post-training；editing 在缺少真实 edit-pair 数据时构造 synthetic paired supervision；13B audio model 在约 1M hours audio 上学习 text/video-conditioned waveform latent，并支持长视频分段 extension。"),
            sec("核心结果与证据", r"Figure 1 用真实输出帧代替长篇能力罗列：同一组模型覆盖 prompt-conditioned motion、人物一致性、局部/全局 instruction edits，以及水声、雷声等同步谱图。", r"Movie Gen Video Bench 有 1,003 prompts，并公开 non-cherry-picked outputs。pairwise human evaluation 的 overall-quality net win rate 相对 Runway Gen3 为 35.02%，相对 Sora 为 8.23%（作者定义为 moderate），相对 Kling1.5 为 3.87%（on par）。", r"1080p 是 768 px base output 经 separate upsampler 得到；16 s/16 FPS 是最大 context setting，不代表所有功能或 aspect ratios 都在该长度、分辨率、速度上统一评估。"),
            sec("有效性与局限", r"模型权重、训练代码和训练数据未公开，论文主要可复核的是 benchmarks、样例与方法描述，而非 exact reproduction。internet-scale data 的来源/授权、人物 reference consent、deepfake 和 audio impersonation 都是系统级风险。", r"human A/B 受 prompt set、five-sample selection、downsampling 和 closed commercial baseline access 影响；net win rate 不是绝对质量。视频仍会在复杂 object interactions、physics、counting、文字和长时一致性上失败；Figure 1 是精选能力展示。"),
            sec("复现与资源", r"原文：https://arxiv.org/abs/2410.13720；研究视频：https://go.fb.me/MovieGenResearchVideos。全文 97 页，PDF SHA-256：60fd60a970245ec8e8fda77f04cf6ca0322b8eff5174da8faf28477a035075e5。", r"可复核项需固定 Movie Gen Bench prompts、released non-cherry-picked outputs、pairwise rubric/raters、net-win confidence rule、resolution/fps normalization 与 competitor snapshots；完整训练不可由公开材料独立复现。", r"Evidence status: full-text verified; no independent reproduction performed; training artifacts not publicly available."),
            sec("阅读指南", r"先看 Figure 1 建立四类能力，再读 Figures 2–8 理解 TAE、flow Transformer、upsampler 与 parallelism。随后检查 data curation 和 Table 6 human evaluation protocol；最后分别读 personalization、editing、audio sections，避免把“cast of models”误当成单模型原生全能。"),
        ],
        "cover": {"mode": "source_figure", "asset_path": "assets/collection-figures/2410.13720/figure-1-moviegen-capabilities.webp", "label": "Figure 1", "visual_type": "comparison", "evidence": "paper.pdf p. 2, Figure 1", "alt_text": "多行视频帧展示 text-to-video、个性化、指令编辑与同步音频能力。", "caption": "Movie Gen 是一组共享媒体基础设施但经不同 post-training 得到的模型，而不是一个单模型完成所有任务。", "selection_rationale": "Figure 1 是全文最重要且最具可视性的能力总览，优先于架构表和人评数据图。"},
        "figure_refs": [figure("2410.13720", "figure-1-moviegen-capabilities.webp", "Figure 1", 2, "visualize the model family's four media capabilities", "Video frames and spectrograms for generation, personalization, editing and audio.", "The figure reveals that Movie Gen is a cast of task-specialized post-trained models.", "These are illustrative outputs; benchmark claims require the separate non-cherry-picked evaluation set.")],
        "equation_refs": [
            {"label": "Conditional flow-matching path", "latex": r"x_t=(1-t)\epsilon+t x,\qquad \mathcal L_{\rm FM}=\mathbb E\|v_\theta(x_t,t,c)-(x-\epsilon)\|_2^2", "role": "train the media latent velocity field", "symbols": {"epsilon": "Gaussian latent", "x": "image or video latent", "c": "text conditioning"}, "evidence": "paper.pdf pp. 7–8, Section 3.1.3", "interpretation": "The Transformer generates compressed spatiotemporal latents by integrating a learned conditional velocity."},
            {"label": "Temporal compression", "latex": r"T_{\rm latent}=\left\lceil\frac{T_{\rm RGB}}{8}\right\rceil", "role": "relate RGB video length to TAE latent length", "symbols": {"T_RGB": "input frames", "T_latent": "temporal latent frames"}, "evidence": "paper.pdf p. 6, Figure 4", "interpretation": "The decoder emits eight frames per latent frame and discards any padding frames at the end."},
        ],
        "evidence_refs": ["paper.pdf pp. 2–11: system capabilities, TAE, flow model and upsampler", "paper.pdf pp. 18–25: Movie Gen Video Bench and human comparisons", "source PDF SHA-256 60fd60a970245ec8e8fda77f04cf6ca0322b8eff5174da8faf28477a035075e5", "Evidence status: full-text verified; no independent reproduction performed."],
    },
]


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for card in CARDS:
        (OUT / f"{card['arxiv_id']}.json").write_text(json.dumps(card, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"installed": [card["arxiv_id"] for card in CARDS]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
